### ISSUE TITLE
[ feature ] Support `Power Lora Loader (rgthree)` node

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#106]
This is one of these nodes you could consider supporting the future. 
But it will probably be hard to do. 

This node has a toggle button, a COMBO box, and value widget, all in the same line !
And it has a button to add more lines !

![pwr1](https://github.com/user-attachments/assets/ed1510cb-75d1-47be-a6e5-24cbf1242624)

**Comment by chrisgoringe** [comment]
(added at PR to rgthree - https://github.com/rgthree/rgthree-comfy/pull/379 - to avoid the need for special-casing)

**Comment by chrisgoringe** [comment]
Seems as if the Power Lora Loader node doesn't work with the @latest front end?

**Comment by LukeG89** [comment]
> Seems as if the Power Lora Loader node doesn't work with the @latest front end? So I'm pausing support for it until that gets clarified!

Yes, there is a problem with the button that adds LoRAs to the node, rgthree raised an issue in Litegraph repo because of that.
The problem is caused by the Canvas Pointer API PR btw

**Comment by LukeG89** [comment]
@chrisgoringe They fixed the issue in 1.4.11 frontend

**Comment by LukeG89** [comment]
@tampadesignr Open separate feature requests for the nodes you want Controller to support

**Comment by tampadesignr** [comment]
> @tampadesignr Open separate feature requests for the nodes you want Controller to support

ohh.. i was just testing figured more info about same issue more code to look at and find a unified solution
my wish .. all nodes worked together perfectly..lol i want no issues .. i just want to create art
anyway my best to coders that are coders at heart

**Comment by LukeG89** [comment]
> > @tampadesignr Open separate feature requests for the nodes you want Controller to support
> 
> ohh.. i was just testing figured more info about same issue more code to look at and find a unified solution my wish .. all nodes worked together perfectly..lol i want no issues .. i just want to create art anyway my best to coders that are coders at heart

@tampadesignr Sorry, I didn't mean to be rude, it's just the way to request support for specific custom nodes. If you need a node to be supported by Controller, feel free to open a feature request about it!

**Comment by JorgeR81** [comment]
When support was added for the `Trung0246` switch, other nodes from the same node pack also started working.

Lets see if support for the `Power Lora Loader`, also brings other rgthree nodes like `Fast Groups Muter` and `Fast Groups Bypasser`.

We can already mute/bypass groups in the Controller, but these rgthree nodes have extra features.

For instance we can select 2 or more groups, and bypass/mute only one at a time, with a single click ( with the `toggleRestriction` property ).

---

![rg0](https://github.com/user-attachments/assets/feefd93c-4190-4dec-9499-c6022264d197)

**Comment by tampadesignr** [comment]
as a fine artist i assimilate as much general info as possible to try and comprehend a fraction of what going on...
my latest thing is finding complex workflows and stretching them out till i can see the connections

i look forward to every advancement you all make. good luck with this

**Comment by chrisgoringe** [comment]
So the way it works is that support gets added for a particular custom
widget, in order to support a particular node.

Often other nodes in the same pack use the same widget, so they also start
working.

So once the LoRA loader works (soon…) check to see if the ones you want
also work! If not, raise a new issue to request them.

**Comment by tampadesignr** [comment]
oh this node aka future of comfy
is on my watchlist

**Comment by chrisgoringe** [comment]
This is now done (as far as I intend to do it). Please raise issues as new bugs.
