### ISSUE TITLE
Highlight node in workflow when you hover over the controller version and vica versa

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#109]

**Comment by JorgeR81** [comment]
Great Idea !

**Comment by chrisgoringe** [comment]
Needs to be an option, I think, default on.

**Comment by chrisgoringe** [comment]
done on dev

**Comment by chrisgoringe** [comment]
Considerably more complicated... and less value, I think

**Comment by JorgeR81** [comment]
> Considerably more complicated... and less value, I think

Yeah, I agree it's not that useful.

 In the Controller nodes can be better organized, so they would be easier to find.
