### ISSUE TITLE
[ feature ] option to don't show Controller, when loading workflows without controls nodes 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#110]
Now the Controller shows up every time I drag an image / workflow to Comfy UI, even if it has no control nodes. 

Sometimes I'm just checking the workflow of an old image ( to copy the prompt or something ) and I don't need to add control nodes.

Can you add an option to disable this behavior? 

This option could still be enabled, by default, for new users. It could be good for discoverability.

**Comment by chrisgoringe** [comment]
"Hide controller when no control nodes" (default off)

**Comment by JorgeR81** [comment]
Just tried the new Controller sidebar. Looks great !

And I just realized this feature is not needed anymore.
The only thing this feature will do is to close the Controler Sidebar.

But this is not normal ComfyUI behavior.
The Sidebar stays open until the user closes it. 

When we drag a JSON or a PNG to ComfyUI, while the Sidebar is open.
And the Sidebar that is open could be the Controller sidebar or any other sidebar.
