### ISSUE TITLE
[ feature ] support for toggle ( true/false ) widgets 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#112]
Some nodes have toggle ( true/false ) widgets, but they are not included in the Controller.

This example is from ComfyUI-KJNodes, but I've seen this same widget in other custom nodes.
https://github.com/kijai/ComfyUI-KJNodes

Can this be added ?

![kj](https://github.com/user-attachments/assets/6149577e-94d5-4ac6-89aa-6e62bae53228)

**Comment by chrisgoringe** [comment]
Ah, yes, this is a standard type. Needs to be added.

**Comment by JorgeR81** [comment]
This still has some issues:

https://github.com/chrisgoringe/cg-controller/issues/135
https://github.com/chrisgoringe/cg-controller/issues/136

**Comment by LukeG89** [comment]
Both issues are fixed now
