### ISSUE TITLE
[ bug ] `Load Image` does not update the image, if the Controller COMBO box is used

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#114]
The image name changes but not the image. Neither on the controller nor the node. 

We need to refresh the browser to fix this.

Refreshing the Controller ( hide it and show again ) does not fix it.

**Comment by chrisgoringe** [comment]
No, it should be automatic. I think there may be a fix I haven't pushed yet - I had to do a change because seeds broke everything.

**Comment by LukeG89** [comment]
This issue is _almost_ fixed: The image is updated, but not the image name.
