### ISSUE TITLE
[ feature ] store image and prompt sizes with and without advanced controls 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#118]
**Problem:**

In this example, if I enable the advanced controls, the controller will use 2 columns, and most of the space is wasted. 

<img src="https://github.com/user-attachments/assets/bdb739ea-9be9-4c89-8dc5-60bbc632bafe" width="75%" height="75%">

---

**Solution:**

I want to be able to manually set an image height, with and without advanced controls.
And the next I toggle the advanced controls, the image size would change, according to my preferences.

This could also be used for the prompt panel.

<img src="https://github.com/user-attachments/assets/f2a7b50d-5657-4b4b-8cc5-8b8dabad3eac" width="85%" height="85%">

**Comment by chrisgoringe** [comment]
This is probably redundant in the single-column mode?
