### ISSUE TITLE
[ bug ] Controller text is selected, when we click and drag on sliders 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#122]
In this example, while dragging the steps slider, it selected the numeric value, and all the text above it.

![26](https://github.com/user-attachments/assets/e24b0c8d-afb0-4765-a976-41543bb26053)

**Comment by chrisgoringe** [comment]
pushed fix to 0.9.7

**Comment by JorgeR81** [comment]
It's working.

**Comment by LukeG89** [comment]
@chrisgoringe It's not fixed yet (0.9.9 branch)


https://github.com/user-attachments/assets/71e3984d-834d-41b3-98c2-1e17c53f94a1

**Comment by JorgeR81** [comment]
Yes, I also have this issue in again in 0.9.9
