### ISSUE TITLE
[ feature ] multiple controller instances

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#123]
I think it could a be pretty intuitive, and very powerful feature.

We could have a `+` icon/button to add another Controller instance. And an `x` button to delete it ( see mockup ! )

Why would I want this, instead of showing "All Groups" ?

- This would allow me to show only 2 groups. I could have 10 groups, which would make the "All Groups" option, unpractical. 
- It perverses the panel configuration, for each group ( e.g. with the image panels on top )
- It's also better to have separation between groups ( e.g. I will have 1 group per column )

---

This would be, for example, an Image2Image workflow, with a different image for the for ControlNet.

This looks so good !

I wouldn't mind extra CPU usage to have this.  

![dual](https://github.com/user-attachments/assets/f9b5a7c3-1d6a-4100-91ed-272bf594e296)

**Comment by JorgeR81** [comment]
If multiple instances are too complex, you can have just a "dual column mode", with 2 controllers.

This would be enough for most use cases.  

I would use the 2nd column to navigate the extra groups ( ControlNet, Refiner, etc, ...  )
While having the main group always accessible

**Comment by chrisgoringe** [comment]
> If multiple instances are too complex, you can have just a "dual column mode", with 2 controllers.

In general, n is not much harder than 2. 2 rather than 1 is the non-trivial step!

**Comment by chrisgoringe** [comment]
basic implementation on 1.2 branch...
