### ISSUE TITLE
[ feature ] option for the prompt box to have the full panel width

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#124]
The current way looks good, but it wastes about % 25 of the available space.  

This could be a good option, for users that like long prompts. 

---

**original:**

![t1](https://github.com/user-attachments/assets/5415faaa-60fc-437b-807c-29bd6e9d625c)

---

**mockup:**

![t3](https://github.com/user-attachments/assets/91e282af-aaca-492b-80d0-79a14191aefc)

**Comment by JorgeR81** [comment]
Or, for simplicity, use only full width, and forget about the current layout.
 
I think the full width also looks good, and it's more similar to the node layout.   

----

**original** ( node )

For reference, this is the default ComfyUI workflow.
The node also does not have the "text" label and it gives plenty of space for the prompt.

![node](https://github.com/user-attachments/assets/0f3ff86b-9de9-45cf-be42-2e60c7f2fdb9)

**Comment by chrisgoringe** [comment]
There's an issue if there are more than one text areas on a node.

Perhaps a hover text tooltip with the input name.

**Comment by JorgeR81** [comment]
> Perhaps a hover text tooltip with the input name.

That would work. 

Another alternative would be doing the same as Comfy UI.
ComfyUI, has the label in the empty text box ( in a grey font ).
But then it's gone, when you type. 

![flux](https://github.com/user-attachments/assets/ca5da00d-cef8-42ee-9e35-17c0dabf1ea7)

![flux1](https://github.com/user-attachments/assets/7b1a3dfd-355f-4851-9e80-fa0c86e5cdd2)

**Comment by JorgeR81** [comment]
By the way, the panels work so much better than the node here !

With the panels you can change the size of each text box individually. 

Bun on the node, you can only change the global node size, and both text boxes are always the same size. 

![flux 3](https://github.com/user-attachments/assets/74f4499a-7701-4511-a7c0-4ed0fa69adda)

**Comment by LukeG89** [comment]
Prompt boxes work perfectly! This issue can be closed
