### ISSUE TITLE
[ bug ] Controller text is selected if we click the header "dot" and drag. 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#129]
**Version: 0.9.8**

In this example, I was trying to move the blue panel up, but I clicked the dot instead, by accident. 

![txd](https://github.com/user-attachments/assets/a599f6be-ce0a-4557-9afb-085462d886b4)

**Comment by chrisgoringe** [comment]
thanks. I'd seen this, but not identified the cause was starting a drag by clicking the button!

**Comment by JorgeR81** [comment]
Yes, header text selection is fixed. 

We can still select text if we try click and drag on the option name area.

But anyways, this will also be fixed, if full width widgets are added ( https://github.com/chrisgoringe/cg-controller/issues/140 )

![sel](https://github.com/user-attachments/assets/d4fc3013-fac5-4c49-b73c-22a69d0c61e0)
