### ISSUE TITLE
[ feature ] Consider replacing the multi column layout with single column + scrollbar

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#134]
I believe there are many reasons for this:

- Multi column seems to create more bugs: 
https://github.com/chrisgoringe/cg-controller/issues/125
https://github.com/chrisgoringe/cg-controller/issues/132 

- Even when it works correctly, it's annoying to use ( e.g., if a 2nd, full size, column is created just to fit 1 extra node ). 
I would rather have a single column with scrollbar. It would be less invasive. 

- The scrollbar would be very easy to use. People are used to it. 
We could use Controller mouseover + scroll wheel, to quickly access all the panels. 
The ComfyUI new Sidebar, also works like this.

- The scroll bar would just be a last resort. Most of the time it will not be necessary.
Fitting all nodes in a single column is now easier, with the group selection and collapsible panels.

- The `All Groups` view would be more usable in large workflows. 
 If we have many control nodes, in many different groups, we can fit all nodes in one column, per group. 
But the `All Groups` view will create 4 or 5 columns, and it will hide the graph canvas. 

- It's confusing having nodes changing position between multiple columns. 
I'd love to use multiple columns, but only if the columns were independent ( e.g., 1 group per column  ) 
See here: https://github.com/chrisgoringe/cg-controller/issues/123

**Comment by chrisgoringe** [comment]
I think this is worth the experiment. I will create a separate branch today.
