### ISSUE TITLE
[Bug] Seed (rgthree) is not updated

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#137]
0.9.9 branch.
When adding Seed (rgthree) to the Controller, the seed is not immediately updated; you have to click outside of the controller to trigger the update.

https://github.com/user-attachments/assets/76295d4b-0ea2-4023-a36f-71b17a96fd2e

**Comment by JorgeR81** [comment]
Yes, I'm also having this issue.
