### ISSUE TITLE
[single column branch] dynamically hide scrollbar

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#138]

**Comment by LukeG89** [comment]
Just a little issue when resizing the latest Controller (refreshing the page resolves it) 

https://github.com/user-attachments/assets/b5db7170-9399-4248-b218-ac13b257351d




And also a couple of times the window expanded when resizing the textbox, but I can't reproduce it.

**Comment by LukeG89** [comment]
Maybe an auto-hide like the other windows is less troublesome.  
The scrollbar space is still there, only the scrollbar is hidden.


https://github.com/user-attachments/assets/f4723006-c1ff-49af-8f26-03519adaa781

**Comment by chrisgoringe** [comment]
I'm going to close this, but create a new issue to do a custom scroll bar in a future version (to allow horizontal drag as well as vertical scrolling, and to have full control rather than being browser dependent)
