### ISSUE TITLE
Integrate with menu bar (toggle with click)

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#139]
![Screenshot 2024-10-16 075803](https://github.com/user-attachments/assets/3c21811d-64ff-41fc-92da-08cc1bb8aaeb)

**Comment by JorgeR81** [comment]
Do you mean a button in the Top bar ? 
Yeah, that would be great !

Other extensions also have this, like rgthree or the Manager itself.

![Topbar](https://github.com/user-attachments/assets/bc372094-f423-4b52-bda4-1a960341e6df)
