### ISSUE TITLE
[ aesthetics ] make all widgets full width ( was make "true/false" toggles same width )

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#140]
If would fit better with the rest of the GUI, if you:

- make the "true/false" toggle widget the same width as the other widgets. 
- put the label outside of the widget

----

**Original :**

![tf](https://github.com/user-attachments/assets/22bead48-9ae4-4f4a-9021-a83f5e5a2c51)

---

**Mockup:**

![tf2](https://github.com/user-attachments/assets/0d59c74c-6103-4642-8050-8e789d6653c7)

**Comment by chrisgoringe** [comment]
I did it as it is because I've got several nodes with very long titles for the toggles which don't fit in the label space... 

So not sure the best solution. Maybe all widgets should be full width, and the title just done as a tooltip?

**Comment by JorgeR81** [comment]
You mean sliders too ?

Yeah that could work ! 

You could align the option name to the left ( maybe with a less bright font ) and leave the value in the center of the slider.

**Comment by chrisgoringe** [comment]
yes, that could work.

**Comment by JorgeR81** [comment]
Consider adding this in version 1.0, instead of 1.1

This way you'll have the prettier GUI in the documentation :)  

And the GUI version 1.0, will probably be the first image people will find, when they search for this extension. 

If I search for "InvokeAI", in Google Images, I find mostly images of v3 ( which was a major stable release ) instead of the latest v5.

**Comment by JorgeR81** [comment]
It seems ComfyUI already has "native" sliders, but they are not enabled ( https://github.com/chrisgoringe/cg-controller/issues/61#issuecomment-2424974260 )

They are just used by custom extensions ( with harcoded min/max ), 
Or used as an input device, for regular nodes ( see image ).

![sl0](https://github.com/user-attachments/assets/f933cb59-c0e3-4015-8558-f0c625eaf2ec)

---

I don't like the centered values. They are less readable, if we have many sliders.

But I like the more muted color scheme.
I think it's pretty readable, and it makes the GUI less distracting ( so that we can focus more on the images ).
That bright blue color worked better on the "Blender style" sliders. But with full width sliders, it may be too strong. 

**new mockup:**
- negative slider area with the same color as COMBO box
- positive area with pale blue / grey color
- no vertical line between the positive and negative areas

![color1](https://github.com/user-attachments/assets/89cc95fe-4321-4416-ab87-f625293e362d)

----

**old mockup:**

![376834355-84f7d7cd-fd63-47f7-817e-993b8615f12b](https://github.com/user-attachments/assets/20848390-65b9-4d8b-aade-7decbae7a245)
