### ISSUE TITLE
Select which widgets to show or hide

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#143]

**Comment by JorgeR81** [comment]
When you think about this, consider that it would be especially useful for big nodes like `Face Detailer`.

It requires the full column. I can put this in a group, to show only this node at a time.
But it would be nice to have fewer widgets and more space for a `Image Preview` here.

![face](https://github.com/user-attachments/assets/f884b2ab-69d4-44e8-bc72-6cca06d0363f)

**Comment by JorgeR81** [comment]
It's great that you can hide the Hub's widgets in the Controller !

But also about the Hub, 

Could it be possible to hide part of the sole widget name, to save space ?
These names are very long.

Im not asking to change the widgets names, just to hide some redundant parts of the name, in the Controller's GUI.

It's a similar problem to hiding the widgets.
Maybe it could be solved in the Hub's side, but it's the Controller that really needs to save the screen space. 

![sw1](https://github.com/user-attachments/assets/89badc87-affc-4289-a1ab-819e889afadf)

**Comment by chrisgoringe** [comment]
ctrl-click the nodeblock header for this on 1.5

This has the same issue #375 with changes not always being saved - I've raised an issue with ComfyUI front end about it but will look for a workaround.

You can always just move a node to trigger the need for data to be saved.

**Comment by chrisgoringe** [comment]
One option for the long names would be #386

**Comment by JorgeR81** [comment]
> ctrl-click the nodeblock header for this on 1.5

It's working. And it looks gorgeous ! So clean !

Once a node has hidden widgets, could it be possible to add a button to toggle all hidden widgets at once ?

Maybe also with the `bolt` icon in the node header ( https://github.com/chrisgoringe/cg-controller/issues/303#issuecomment-2486574895 )


![ad1](https://github.com/user-attachments/assets/6f11cb8f-1756-49ed-a8f0-680a6ae20ad3)


---

![h1](https://github.com/user-attachments/assets/2ef5b4b7-255d-4bb9-bf5c-bed5c695e655)

**Comment by chrisgoringe** [comment]
Added #387 for showing all the hidden widgets

**Comment by LukeG89** [comment]
Works great! 🚀 
Nice that you also add the option to remove the controller!

Anyway, there are the same issues as there were with the mask editor menu, you can open more than 1 menu and the menu only disappears if you click on the canvas (or select an option).

**Comment by chrisgoringe** [comment]
> Anyway, there are the same issues as there were with the mask editor menu, you can open more than 1 menu and the menu only disappears if you click on the canvas (or select an option).

now fixed on dev I think

**Comment by JorgeR81** [comment]
It seems to be working.

**Comment by LukeG89** [comment]
Yes, works perfectly!
