### ISSUE TITLE
[ feature ] [ single_column ] Increase the Controller scaling drag area

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#146]
Increase the Controller scaling area to the whole bottom border ( not just the bottom right corner ).

**Comment by chrisgoringe** [comment]
The rescale is provided by the browser.  The cost/risk/benefit of replacing it seems unlikely

**Comment by JorgeR81** [comment]
Yeah, these features may not be necessary.

I think this is a better alternative: https://github.com/chrisgoringe/cg-controller/discussions/142#discussioncomment-10957554
