### ISSUE TITLE
minor graphical things in integration with left menu 

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#147]

**Comment by LukeG89** [comment]
This is going to the right direction! 

I just report some minor graphical issues to improve integration:

- The distances between the other icons is different:

![controller_icon_sidebar_icons_distances](https://github.com/user-attachments/assets/6d8ae9f8-b98d-49c2-8a67-6011e48760a6)

- There is a slighlty offset change on the icon when opening Controller:

![controller_icon_open_tab_offset](https://github.com/user-attachments/assets/4a291f24-c99e-4caf-8e69-bbabcbbfe7fe)


- It appears a "block" on mouseover:

![controller_icon_mouseover_block](https://github.com/user-attachments/assets/52ed5c45-ab0b-4387-bbae-74eabd75eb6f)

- There is no bluebar as in the other opened icons:

![controller_icon_blubar](https://github.com/user-attachments/assets/61502018-b70a-41f5-a35e-c21b4a180ff4)


## Requests:

Can the scrollbar be as in the other windows?

![controller_scrollbars_differences](https://github.com/user-attachments/assets/01af57d4-8c6f-4a44-a024-649ed9f3bfa1)

And maybe you can also add the label on mouseover:

![workflows_ref_mouseover](https://github.com/user-attachments/assets/e4dbc7f1-b62e-4ef6-9d53-be8feef1570b)

**Comment by JorgeR81** [comment]
> I just report some minor graphical issues to improve integration:
> 
> - The distances between the other icons is different:
> - It appears a "block" on mouseover:
> - There is no bluebar as in the other opened icons:
>

Has this fixed alredy ?

I don't have these issues. 
I updated about 2 hours ago ( about the same time as @LukeG89's comment )

I use Google Chrome.
Here's how it looks for me:

![sb](https://github.com/user-attachments/assets/a940a54a-09f8-41b3-a2c5-48ef13e31bec)

**Comment by LukeG89** [comment]
Found other problems when moving the sidebar on the right. The Controller still appears on the left side and the bluebar appears on the wrong side of the button:

![sidebar_right_position](https://github.com/user-attachments/assets/cc5d9179-63e7-4708-a613-8cb97217e655)

**Comment by LukeG89** [comment]
@chrisgoringe Last detail: the bluebar should be on the opposite side when sidebar is on the right.

![bluebar_opposite_side](https://github.com/user-attachments/assets/d489443e-c1f6-4841-b3ee-a0b1052fc084)

![ref](https://github.com/user-attachments/assets/4bf5283c-e6e2-4cb5-82c8-f3ef59fecb6c)
