### ISSUE TITLE
[Bug] The slider stops changing values when the mouse leaves the sliding area

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#148]
### Branch:
single_column

### Expected behavior:
When I change the slider values with the mouse, the slider should keep changing values even if the cursor is not on the slider.

### Actual behavior:
The slider stops changing values when the cursor leaves the sliding area.

https://github.com/user-attachments/assets/b8ab91a5-76f5-460d-a33a-b84cedb1ad18

**Comment by JorgeR81** [comment]
Yeah, I agree with this.

It should only stop changing values, on clickup.

**Comment by chrisgoringe** [comment]
This has been done as part of stopping the text selection issues... however other fixes to that may have made it possible. Will check.
