### ISSUE TITLE
Allow width of controller to change

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#149]

**Comment by chrisgoringe** [comment]
if in single column mode

**Comment by JorgeR81** [comment]
This this working ?

I can't drag the sidebar border to scale it. 

The Controller is narrow in one of my workflows, but I think that's an issue with the workflow ( https://github.com/chrisgoringe/cg-controller/issues/195#issuecomment-2432189479 )

**Comment by LukeG89** [comment]
@JorgeR81 😅  https://github.com/chrisgoringe/cg-controller/issues/197

**Comment by JorgeR81** [comment]
> @JorgeR81 😅 https://github.com/chrisgoringe/cg-controller/issues/197

I was wondering if this was added, because it shows as `completed on branch` and @chrisgoringe mentioned ( in #195 ) :

> This is https://github.com/chrisgoringe/cg-controller/issues/197 related to horizontal rescalingof the controller. I believe it is now fixed (and you can change the controller width...)

**Comment by LukeG89** [comment]
> I was wondering if this was added, because it shows as completed on branch and @chrisgoringe mentioned ( in https://github.com/chrisgoringe/cg-controller/issues/195 )

@JorgeR81 I didn't see the resize handle because I have rgthree Progress Bar that is covering it. But the resize is working


https://github.com/user-attachments/assets/6b2f3ced-d63b-442f-9d91-1d82af4ebb1f

**Comment by LukeG89** [comment]
@chrisgoringe Is it possible to resize the window by grabbing the side instead of the corner? (like the other sidebar windows)

**Comment by JorgeR81** [comment]
OK, it's working. 

I didn't realise the dragging area was only at the bottom :)

Probably this should be included in the documentation. 

---

About the rgtree bar, it was disabled.

But when I enabled it ( on top ), my Controller got resized down.

Can you check If this also happens for you, with the progress bar on top. 

![rg3](https://github.com/user-attachments/assets/dc392e7d-9c45-4cbb-8ec9-fb2eecdccb12)

**Comment by LukeG89** [comment]
> But when I enabled it ( on top ), my Controller got resized down.
> 
> Can you check If this also happens for you, with the progress bar on top.

@JorgeR81 It works fine to me

![ok](https://github.com/user-attachments/assets/6a6b4c6e-f394-4ce6-9322-cd22b6136e90)

**Comment by JorgeR81** [comment]
> @JorgeR81 It works fine to me

OK, I just enabled the rgthree bar again, and it works. 

Maybe it's another issue.

On a couple of occasions, the Controller resized automatically ( that was one of these occasions ).

But this seems to be fixed, once I resized manually.
