### ISSUE TITLE
[ bug ] Controller sidebar visible, behind the current sidebar ( when workflow is opened )

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#150]
When we open a workflow while another Sidebar in open the Controler Sidebar is still visible.

But this is not consistent behavior because the Controller icon is not blue.

**How it should work :**

- Only one Sidebar should be enabled at a time. If another Sidebar is opened, the Controller does not show up.
- After loading the workflow, the user just needs to click on the Controller icon, in order to switch to the Controller Sidebar.
- And to hide all Sidebars, the user would instead, click again in the current Sidebar icon
- Also, this feature is not needed anymore ( see my new comment ) : https://github.com/chrisgoringe/cg-controller/issues/110 

![branch](https://github.com/user-attachments/assets/64d7ed9d-6615-44fd-80fb-230eccad9b52)

**Comment by chrisgoringe** [comment]
Yes, I noticed this.

I think it should start closed whenever you load.

**Comment by JorgeR81** [comment]
> I think it should start closed whenever you load.

Yes, except if it happens to be the sidebar that's already visible when you load.
