### ISSUE TITLE
[ Aesthetics ] Match the look of the Sidebar's header

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#151]
- "CONTROLLER" label on the left
- Icon buttons in the right 
- Line divider
- filter / selection options in the bottom line 

---

**Mockup:**

![a002b](https://github.com/user-attachments/assets/03abfda1-2556-40c7-86f0-b596da628bc2)

---

**Original:**

![a001b](https://github.com/user-attachments/assets/4cbc383a-1ae5-4848-97ee-ebca9a1d7c7d)

---

**Original** ( Sidebar ) :

![a0](https://github.com/user-attachments/assets/93bdbd44-59e6-40ff-88c9-e866f9ad8494)

**Comment by LukeG89** [comment]
For the advanced controls I would suggest to replace the tickbox with a switch.

**Comment by JorgeR81** [comment]
This is "**_closed_**" and "**_completed on branch_**".

But, I don't see it in the `single_column` branch.
