### ISSUE TITLE
[ feature ] lock column scroll up, while scaling down nodes ( to prevent feedback loop ) 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#156]
When we use the "resize handle" to reduce the size of an image or prompt node, and the column is not scrolled all the way up, it creates a "feedback loop" that scales down the node, very fast, with just a small mouse movement.

Can the column scrolling be stopped, while we're scaling down the nodes ?
The column scroll could be adjusted only on click up.

While increasing the node size, this does not seem to be necessary ( no feedback loop is created )

---
Here, I tried to scale down the image just a bit.

![s1](https://github.com/user-attachments/assets/2bdea49b-a420-40c6-b191-47665e3d27ad)

---

But, the column started scrolling up, at the same time.
And the image was resized very fast, with just a small mouse movement, until the column was scrolled all the way up.

![s2](https://github.com/user-attachments/assets/cad594d0-180c-48f8-9ba5-ac3eed6b5b80)

**Comment by LukeG89** [comment]
I'm having problems resizing text fields and images: 

- sometimes they won't keep the new size
- when I edit a parameter on nodes with both text and widgets, the text field is reset to previous size
- sometimes they resize is extreme


https://github.com/user-attachments/assets/6967b6e8-6061-4540-b76a-cea2f66a878e


https://github.com/user-attachments/assets/cf55717c-c6be-4115-aa05-992c12faf1b1

------

Similas issue when resizing images.


https://github.com/user-attachments/assets/bd32e336-14d6-4aa9-8c5c-b5aeb7867094

**Comment by chrisgoringe** [comment]
yes, resize save has been broken by another fix. Working on it.

**Comment by chrisgoringe** [comment]
should be fixed now

**Comment by LukeG89** [comment]
@chrisgoringe Yes, now everything is working great! I only experience extreme resizing with the latest text field at the bottom

**Comment by LukeG89** [comment]
Ah, and I see that resizing images is pretty lagging

**Comment by JorgeR81** [comment]
I also noticed that if you stop dragging up for a second ( while reducing image size ), it will trigger the "click up event", even when you're still pressing down.

Sometimes this also happens when increasing the image size, if I drag too fast.

**Comment by chrisgoringe** [comment]
Consequence of fixing the crazy resize :). But I think I can improve it

**Comment by LukeG89** [comment]
Now resizing seems to work pretty great! This issue can be closed

**Comment by JorgeR81** [comment]
Yeah, it's working perfectly now.
