### ISSUE TITLE
Make scrollbars consistent (color)

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#159]
![377375327-01af57d4-8c6f-4a44-a024-649ed9f3bfa1](https://github.com/user-attachments/assets/1097baeb-335e-4ed0-a13f-ca8066022a23)

**Comment by chrisgoringe** [comment]
I don't seem to have a scrollbar in the node tree. 
![Screenshot 2024-10-18 203315](https://github.com/user-attachments/assets/c50af1a2-1d82-4743-9216-4437febb428a)

It scrolls on the scrollwheel; but that is intended for sliders.

I've made the scrollbar a little smaller; that's probably it.

**Comment by LukeG89** [comment]
@chrisgoringe Scrollbars are implemented in 1.3.18 frontend

**Comment by JorgeR81** [comment]
> I've made the scrollbar a little smaller

If you  can also change the colors, it would look very similar, to the "native" one.

With darker colors it wouldn't stand out as much.

![bb1](https://github.com/user-attachments/assets/b8b66fa9-d5af-47af-8ccc-aa4721abd526)

**Comment by JorgeR81** [comment]
> It scrolls on the scrollwheel; but that is intended for sliders.

We could use `Ctrl + scrollwheel` to change slider values ( https://github.com/chrisgoringe/cg-controller/issues/86 ), and keep `scrollwheel`, for the scrollbar

And maybe, if the scrollbar is disabled ( e.g. when less panels are used ) the `scrollwheel` could also work on the sliders.

**Comment by JorgeR81** [comment]
> It scrolls on the scrollwheel; but that is intended for sliders.
> > 
> > We could use Ctrl + scrollwheel to change slider values ( https://github.com/chrisgoringe/cg-controller/issues/86 ), and keep scrollwheel, for the scrollbar
> > 
> 

Ah, you meant that the `scrollwheel` will only be used to scroll the column, when we mouseover the scrollbar.

Yeah, that would also work. And it would be more intuitive.
