### ISSUE TITLE
TextArea shows through

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#162]
![Screenshot 2024-10-19 210045](https://github.com/user-attachments/assets/8e7e1397-8fc7-4f08-a6f2-b05987d443e1)

**Comment by LukeG89** [comment]
Maybe this issue is caused by broken DOM element clipping in frontend? https://github.com/Comfy-Org/ComfyUI_frontend/issues/1172

**Comment by chrisgoringe** [comment]
Yes

**Comment by JorgeR81** [comment]
Have you noticed that the TextArea does NOT show through the new pinned Controller Header !

Can you use this as a workaround to fix the issue ?

![fix](https://github.com/user-attachments/assets/c5cdc59e-8f7f-429f-a844-ed1f3860a0cf)

![fix2](https://github.com/user-attachments/assets/5ecc1f66-a542-4765-9212-3b0db7521116)

**Comment by chrisgoringe** [comment]
Well that is interesting...

**Comment by chrisgoringe** [comment]
Odd. For me it does show through...

![Screenshot 2024-10-22 122103](https://github.com/user-attachments/assets/b7a418c5-806e-4b46-80ec-4ac8938b90dc)

**Comment by JorgeR81** [comment]
> Odd. For me it does show through...

I'm using Google Chrome.
Windows 10

----

You have this `completed on branch`

But I still have this issue in 1.0-rc2

**Comment by chrisgoringe** [comment]
Hmmm. I'll look again, using chrome

**Comment by LukeG89** [comment]
Yeah, the problem is not solved

![dom_widget](https://github.com/user-attachments/assets/098f9d4a-7ffc-427d-86a4-349ee9fdf744)

**Comment by chrisgoringe** [comment]
Can you get the js console up, then right-click on the textarea which is showing through and select 'inspect', and see what the element.style is showing? Looks like this:

![Screenshot 2024-10-22 222248](https://github.com/user-attachments/assets/060e3012-7500-49b2-ad6a-e6a901148603)

or

![Screenshot 2024-10-22 222251](https://github.com/user-attachments/assets/925f07ce-d369-42f4-ac46-c2306733a6ac)

I'm really interested in the value z-index in there - the code should be setting it to 0...

**Comment by JorgeR81** [comment]
![insp](https://github.com/user-attachments/assets/be7e0d89-0e4f-474a-9beb-2ef02b9da4b3)

**Comment by LukeG89** [comment]
![console](https://github.com/user-attachments/assets/a7885756-d1b2-45c6-8834-d0a2f136477d)

**Comment by JorgeR81** [comment]
> the code should be setting it to 0...

My `value z-index` is 31. 

And it's crossed out, like @LukeG89's

![insp3](https://github.com/user-attachments/assets/dbab99fb-1135-4ae0-b24e-af221bf6d352)

**Comment by LukeG89** [comment]
Same on Edge

![console_edge](https://github.com/user-attachments/assets/27ecb2b0-e531-4519-9983-f52b31221c07)

**Comment by chrisgoringe** [comment]
Odd. I'll look again (but I'm not going to consider this blocking...)

**Comment by chrisgoringe** [comment]
Try updating and see what it looks like now.

The z-index being crossed out is very strange. It means something else is overriding the css setting, but element.style should be the absolute top priority.

I've changed it from "0" to "auto !important". If that doesn't work I'm stumped!

**Comment by LukeG89** [comment]
Yay! It's working! 🎉 

![ok](https://github.com/user-attachments/assets/2c215b1a-b223-41be-83ff-7f9a232a2555)

**Comment by JorgeR81** [comment]
Also works for me !

**Comment by chrisgoringe** [comment]
Phew.

**Comment by LukeG89** [comment]
@chrisgoringe Ehm... Not all text boxes are fixed... 😅


https://github.com/user-attachments/assets/d1d398a2-7e33-432a-bfd4-2e17a6b974b5
