### ISSUE TITLE
[ aesthetics ] Replace the header "dot" with a square

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#163]
In Comfy UI, when a node has rectangular shape, the "dot" is a square, instead.
 
I think this would also look better in the Controller, with it's rectangular shapes.

![sq0](https://github.com/user-attachments/assets/5c4b9b65-838d-41ca-ac3a-4dcdfe447ced)

---

And also, the Controller's header text seems more readable, to me, if it's in the front of a square shape.

**mockup:**

![square1](https://github.com/user-attachments/assets/0b6df00e-3278-41ef-bdcb-327072a1517c)

---

**original:**

![square](https://github.com/user-attachments/assets/3fb389af-cb97-4556-ac6b-345dd2ad5064)

**Comment by chrisgoringe** [comment]
Agree. Oddly, it seems to be more intuitive that it serves as a collapse/expand button somehow, too
