### ISSUE TITLE
fix rounding in... Overlay height when resizing (was: [ feature ] Allow to resize node panels to an exact size. )

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#164]
Sometimes I have multiple `Load Image` panels ( e.g. for Image2Image and a different image for ControlNet ).

I'd like to exactly match the image size for both, but how would I do that ?

In the graph, I can clone the node, or use "snap to grid".

But in the Controller, I need to place the panels next to each other ( vertically ), and just "eyeball it".

**Ideas:**

- Overlay the size %, while resizing, to use as a reference ? 

- When we clone a `Load Image` added to the Controller, it will show up in the same height ( instead of full height ).

---

These features could be used on any node panel that can be resized.

**Comment by JorgeR81** [comment]
I's working, 
and it looks good !

![sz](https://github.com/user-attachments/assets/90c558e0-651f-48b7-a239-44ed6320677d)

**Comment by LukeG89** [comment]
It displays some strange values to me...

https://github.com/user-attachments/assets/ac796b25-0c1b-4dfb-861f-51049a64ee6f

**Comment by chrisgoringe** [comment]
Probably browser dependent. I'll put some rounding in!

**Comment by chrisgoringe** [comment]
should be fixed now

**Comment by LukeG89** [comment]
Yes, it works perfectly! 

Maybe it would be better to make it less transparent?
It is barely visible on images:

![overlay_on_image](https://github.com/user-attachments/assets/78e7a47c-2af3-42a6-8475-02c098c10d64)

**Comment by chrisgoringe** [comment]
tweaked the transparency a bit

**Comment by LukeG89** [comment]
Now it's better! Only on brighter images it is still a little difficult to see (and on white background it disappears)
