### ISSUE TITLE
[Bug+minor visual] Right sidebar position: Graph Canvas Menu over the window and bluebar on the wrong side

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#170]
### Branch:
1.0-rc

### Expected behavior:

When sidebar is on the right, the Graph Canvas Menu should be moved next to the window:
![graph_canvas_menu_ok](https://github.com/user-attachments/assets/d71b09e1-e5d7-4a57-8b93-a7a1c7c86109)

And also the bluebar should appear on the right:
 ![bluebar_right](https://github.com/user-attachments/assets/8a00b56b-bd05-4ef7-a1b1-a88c6d7af44d)

### Actual behaviour:

Graph Canvas Menu over the window:
![graph_canvas_menu](https://github.com/user-attachments/assets/59513574-1b97-44b9-89e2-9e804ba5d71e)

And bluebar on the left:
![bluebar_wrong](https://github.com/user-attachments/assets/18f7f39e-4d77-4a00-9d40-787614fbcc98)

**Comment by chrisgoringe** [comment]
no longer relevant
