### ISSUE TITLE
[Bug] Controller window stays open when opening sidebar windows using shortcuts

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#171]
### Branch:
1.0-rc

### Expected behavior:

When opening other sidebar window using shortcuts, Controller window should close as when clicking on sidebar buttons.

### Actual behavior:

Controller window stays open when opening sidebar windows using shortcuts:

https://github.com/user-attachments/assets/b1403413-0211-4eff-a0f0-5301f786b8ff

**Comment by chrisgoringe** [comment]
no longer relevant
