### ISSUE TITLE
[ bug ][ visual ] Text in dropdown list and Prompt box is aligned to the right

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#174]
Text in Prompt box is aligned to the left

And also the lower border is thicker. It looked better with the same thickness that's on the sides.

![text](https://github.com/user-attachments/assets/410b5c8a-9f74-4fe3-ba93-6c07676c2ea8)

**Comment by LukeG89** [comment]
@JorgeR81 The thicker bottom is not that bad and also helps to better separate from the controller below.

**Comment by JorgeR81** [comment]
> @JorgeR81 The thicker bottom is not that bad and also helps to better separate from the controller below.

This looks asymmetrical and a bit ugly to me.

And it's not even that useful. It just gives less than 1 millimeter of separation

If we users need more separation, they will just end up increasing the prompt box size a bit, anyways, despide having this thicker bottom.

**Comment by LukeG89** [comment]
Dropdown lists were right-aligned before? I can't remember...

![dropdown_lists](https://github.com/user-attachments/assets/50b3a557-fe34-4dd9-b1c4-0b4d9e59f513)


I also noticed the same alignment on buttons:

![buttons](https://github.com/user-attachments/assets/f6f5b7c8-0a11-4243-916b-b1690ea9fa30)

**Comment by JorgeR81** [comment]
> Dropdown lists were right-aligned before? I can't remember...

I don't think so ( I will change the issue name ). 

It's better to alight on the right. Same as Comfy UI.
It's much more readable

![cui](https://github.com/user-attachments/assets/b948e4aa-6bfa-425c-8939-cd32a7c612d4)

**Comment by chrisgoringe** [comment]
You mean better to align left? They are aligned right now...

**Comment by JorgeR81** [comment]
> You mean better to align left? They are aligned right now...

Yeah, sorry, the fix would be alignment on the left :)

**Comment by LukeG89** [comment]
Prompt boxes are fixed, dropdown lists are still on the right

**Comment by JorgeR81** [comment]
For me, dropdown lists are also on the right

**Comment by chrisgoringe** [comment]
pushed a change about 10 minutes ago... make sure you have it!

**Comment by JorgeR81** [comment]
It's working !

**Comment by LukeG89** [comment]
Yes, it's fixed!
