### ISSUE TITLE
[ bug ][ visual ] disconnected vertical line in the slider bar

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#175]
I noticed the slider bar was shifting was I scrolled. 

It seems to be the vertical line from the old slider design.
I think you can just remove that.

![bv](https://github.com/user-attachments/assets/3f6ea8f4-4280-4938-a03f-7e9dbb5e4ab3)

**Comment by chrisgoringe** [comment]
Actually, that's there intentionally, to deal with scrolling less than one step (a visual hint that something is working)

But if I change the scroll wheel to be one step per click I'll make it go away.

**Comment by JorgeR81** [comment]
> But if I change the scroll wheel to be one step per click I'll make it go away.

Yeah, I don't see it anymore.
