### ISSUE TITLE
[ Aesthetics ] Same vertical distance between widgets  

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#176]
The distance between 2 widgets is double the distance between a widget and the panel's top and bottom edges. 

![d1](https://github.com/user-attachments/assets/4c41ba4e-ad73-496e-8828-feaf9bfdfd9c)

Can we have half the separation 2 between sliders ? 

---

**original:**

![k1](https://github.com/user-attachments/assets/75c39ddc-232a-4fcd-8b46-de0b3f655712)

---

**mockup:**

This way it seems the sliders are better grouped together, inside each panel.
And it saves some space.

![k2](https://github.com/user-attachments/assets/ff65bbab-931a-461c-806c-9f9a04b8d971)

**Comment by JorgeR81** [comment]
On second thought this may be worse close, if we have multiple sliders, with full positive sliders.

---

**original**

![v1](https://github.com/user-attachments/assets/743f12f6-a6dd-4a37-ab1d-7e089f1f0ac5)

---

**mockup** ( worse )

![v2](https://github.com/user-attachments/assets/5737517e-0082-401f-b927-57d6ce114c31)

**Comment by LukeG89** [comment]
Nice and compact!
