### ISSUE TITLE
[ Aesthetics ] Same height for colored panel headers. 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#177]
The colored panel header is a little shorter. 

I think it's because of the lack of a separation line

Maybe you could also add an "invisible" separation line, of the name color as the header.

![vis](https://github.com/user-attachments/assets/b1b16b4e-bf7f-4082-a1f4-cf8472bfa15f)

**Comment by LukeG89** [comment]
This seems fixed
