### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by MzMaXaM** [chrisgoringe/cg-controller#18]
Would you please add shortcuts to turn it on and off. 
I'm used to "ctrl+Enter", "ctrl+alt+Enter".

**Comment by chrisgoringe** [comment]
"Enter" gets captured by comfy. I've gone with a setting that lets you choose 'c' 'shift-c' 'p' or 'shift-p' to try to avoid clashes.

**Comment by MzMaXaM** [comment]
Shift+P
Is great I think!

**Comment by chrisgoringe** [comment]
Ah, P gets captured as well... Changing it to 'O' and 'C'.
