### ISSUE TITLE
Can't move slider with scroll if step less than precision (was: Setting to require shift-scroll for sliders)

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#181]
By default the sliders respond to the scrollwheel.

This can be changed to make it so they require the shift key to be pressed.

**Comment by LukeG89** [comment]
I think there is a problem with the cfg, I can change all the other sliders except for cfg ones...


https://github.com/user-attachments/assets/1e758142-b02f-4071-9c6c-9ffff0d5c514

**Comment by JorgeR81** [comment]
> I think there is a problem with the cfg, I can change all the other sliders except for cfg ones...

It's working for me.

Maybe that's a custom node ?

The `shift` key as another function on one of my custom nodes ( https://github.com/chrisgoringe/cg-controller/issues/188 )

**Comment by LukeG89** [comment]
> Maybe this is caused by a custom node ?

@JorgeR81 It can't be since the problem only occurs on CFG sliders. 

> The Shift key as another function on one of my custom nodes ( https://github.com/chrisgoringe/cg-controller/issues/188 )

This is a frontend function.

**Comment by LukeG89** [comment]
It doesn't work even in always mode, to it's not due to shift key

**Comment by LukeG89** [comment]
Could it be related to the default step size of 0.01?

![step_size](https://github.com/user-attachments/assets/042229e3-af1c-4eaa-aef0-799250c9a04c)


(I tried scrolling as much as I can but it doesn't change a single value...)

**Comment by chrisgoringe** [comment]
I'll look at it. My guess is that there is a clash between step size and rounding (if it's rounded to 1 decimal place, but taking steps of 0.01).

**Comment by chrisgoringe** [comment]
Yup. There is a weird interplay between precision, round, and step. I think I've got it working...

**Comment by JorgeR81** [comment]
> Yup. There is a weird interplay between precision, round, and step. I think I've got it working...

After this fix, the other 2 issues I had are also fixed !

https://github.com/chrisgoringe/cg-controller/issues/61#issuecomment-2430375907
https://github.com/chrisgoringe/cg-controller/issues/61#issuecomment-2430408215

**Comment by JorgeR81** [comment]
Ah, but now there is a different problem:

When dragging the slider, the new step interval is not used. It's only used with scroll.

**Comment by LukeG89** [comment]
Cfg now it's working, but they are all 2 decimal digits instead of 1

**Comment by JorgeR81** [comment]
This with the latest update:

- When dragging the slider, the new step interval ( 0.05 ) is not used. - **NOT FIXED**

- The widget arrows, in the node, don't use the new step interval. - FIXED

**Comment by chrisgoringe** [comment]
Added 192

**Comment by chrisgoringe** [comment]
Resolved 192

**Comment by JorgeR81** [comment]
Everything seems to work:
- I can apply the new step size to multiple nodes.
- The new step size is applied, when scrolling and dragging sliders or using the widget arrows.
- The new min / max are applied to the widgets
