### ISSUE TITLE
[ Aesthetics ] Taller headers ( and slightly larger header font )

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#187]
![size](https://github.com/user-attachments/assets/d618feee-a413-4c8a-9744-45b07f53d186)

In ComfyUI nodes, the header is taller than the`widget + margins`.

I think we should do the same.

The `header + line divider` should be about as tall as a `widget + margins`. 

And the text should be larger. 
But not as much, only slightly. To leave larger margins without text, in the header ( like ComfyUI ).

This would help differentiate the panel areas. 
( With the full width widgets, it's a little harder to do that ).

Another advantage is that the header would be easier to mouseover ( to drag or collapse ).

---

**mockup:**

![slx1](https://github.com/user-attachments/assets/37ee2437-6b0f-41a9-a135-436d710e4941)

---

**original:**

![slx2](https://github.com/user-attachments/assets/61901710-b7bd-47aa-9480-ecdf8f98c6e3)

**Comment by chrisgoringe** [comment]
Title bar and (no-rescaling) entry widgets are now all 24 pixels in total. Font is slightly larger, as is the drag area.

![Screenshot 2024-10-23 095334](https://github.com/user-attachments/assets/1df0c313-e4c2-4d3a-83e5-f62785681e6b)

**Comment by JorgeR81** [comment]
Looks good !

---

But now when they are colapsed the colored header is taller.

Can you make it smaller ( and single color ), like the grey one.
I think I would look better like that.
The colapsed headers don't need to be as tall.

![header](https://github.com/user-attachments/assets/47812901-2e1c-4788-8076-a242af628032)
