### ISSUE TITLE
[ feature ] `Ctrl+scroll` and `Ctrl+click` as alternatives keybinds

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#188]
`Shift+scroll` and `Shift+click` are working.

But it seems the `Shift` key is already being used by a custom node to do something else !

Can we have user settings to use `Ctrl+scroll` and `Ctrl+click` as alternatives ?

----
**normal:**

![11](https://github.com/user-attachments/assets/36443084-c386-4874-aa6b-d16dc2901c27)

---
**while the `Shift` is pressed:** 

( this does not happen in I disable all custom nodes )

![s1](https://github.com/user-attachments/assets/89bebdd4-37d6-4bdc-bb15-67f0e53190aa)

**Comment by JorgeR81** [comment]
As @LukeG89 mentioned, this is a frontend feature, that uses the `Shift` key

https://github.com/Comfy-Org/ComfyUI_frontend/pull/1157

So maybe we should have `Ctrl+scroll` and `Ctrl+click` as default, in the Controller.

**Comment by chrisgoringe** [comment]
Both click and scroll can now be set to use shift- or ctrl-

**Comment by JorgeR81** [comment]
It's working.
