### ISSUE TITLE
[Feature Request] Group color labeling

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#189]
Currently it is difficult to tell which group each controller belongs to, inside the window.

I propose a way to better identify them: Group color labeling.

Next to each Controller there is a bar with the same color of its group.
This is useful especially in `All Group` mode and with the upcoming `Multi Pick` feature https://github.com/chrisgoringe/cg-controller/issues/168 (included in the mockup).

Original:
![ref](https://github.com/user-attachments/assets/374b11fd-0045-43be-a5a7-83a4a865e5e8)

Quick mockup: 
![group_controller_identification](https://github.com/user-attachments/assets/f8f57e0f-1305-4412-9e41-54b3c99e151a)

_Idea originally posted in https://github.com/chrisgoringe/cg-controller/discussions/160#discussioncomment-11007636_

**Comment by JorgeR81** [comment]
Yes, this could be an independent feature from `Multi Pick`.

My sugestions:

- The gap between the sidebar and the panel is wide enough, for the color labeling bar.
No need to change the Controller dimensions. 

- Add an user setting to disable `Group color labeling`.

- No color labels for nodes without groups, or in groups with "no color".

- For black groups use very dark grey or black color ( see mockup )

---

![lb](https://github.com/user-attachments/assets/4afe023b-dc6e-402f-a0de-a98c31728129)

**Comment by LukeG89** [comment]
Colors must be coherent to groups; if pitch black is set, the label must also be pitch black.
Otherwise it would be confusing. Also, what happens if you have a actual gray group?

**Comment by JorgeR81** [comment]
But the true color of the "back" group is actually "dark grey".

It's only pure black in the selector. 
But all the colors in the selector are different when used in groups.
All the main colors have more muted color tones in the groups, to give nodes more visibility.

![color](https://github.com/user-attachments/assets/1fe77c10-21dd-4d34-9363-f6897e8290fa)

![black](https://github.com/user-attachments/assets/f3d3e932-30e0-4f78-987d-5b96dd4d292d)

**Comment by JorgeR81** [comment]
Look for instance at the "green" color.

The green color in groups is more muted / soft, than the green used in the nodes. 
That's the softer color that we are using, in the Controller.  

![green](https://github.com/user-attachments/assets/4acd7b56-c9c6-4534-8540-3481afa6fcb3)

**Comment by LukeG89** [comment]
> But all the colors in the selector are different when used in groups.

Yeah, but you need to think about the selector, especially when Groups buttons will be implemented; those colors are the reference when you use Controller.

> All the main colors have more muted color tones in the groups

So all labels should be muted tones, not just the black one.
And the colors of the selectors/buttons should also have the same muted tones.

**Comment by JorgeR81** [comment]
The Controller already uses the muted / soft tones for all colors, including for the "black" groups.

![b2](https://github.com/user-attachments/assets/4fea7a20-ec40-4e0f-863d-49c3f0e515b1)

We can use the same color, in the "black" label. 
It looks more "gray", but it has decent visibility. 

![lb2](https://github.com/user-attachments/assets/0708b1b3-1f87-423b-bd4a-c791a8b6f815)

**Comment by LukeG89** [comment]
@JorgeR81 I think the labels will have the same color as in the selector, so... We discussed a problem that doesn't exist 😆

**Comment by JorgeR81** [comment]
Yeah, the best colors are probably this last mockup. The ones we have already :)
