### ISSUE TITLE
[ bug ] Controller is closed when switching workflows 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#193]
This happens even if both workflows have a Controller.  

I think we had this issue before, but I'm not sure where it was discussed.

**Comment by chrisgoringe** [comment]
How are you swtiching workflows?

**Comment by JorgeR81** [comment]
In the workflow tabs. 

You may need to enable this in the settings.

![tabs](https://github.com/user-attachments/assets/47fda4c4-33e0-4810-8cbd-a40183ab1670)

**Comment by chrisgoringe** [comment]
Right. I use the sidebar, so closing is expected behaviour.

I've updated the title of this bug. Probably not going to look at for 1.0, but it should get fixed sometime.

**Comment by chrisgoringe** [comment]
no longer relevant
