### ISSUE TITLE
[ bug ] image size is reseted after saving, if not visible 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#195]
When I save an workflow in ComfyUI, if the `Load Image` nodes are not visible, then the panel height is reseted ( to the max. height ), when I close and open the workflow again.

By "not visible", I mean if the panel is minimized, or in a non displayed group, or hidden in the advanced controls. 

I think this was working before. But it got broken at some point.

**Comment by chrisgoringe** [comment]
memo to self - this is probably because when the node is made "not visible" the change observer records a zero value for the height in the widget properties

**Comment by JorgeR81** [comment]
I think this fix created a bug

The controller starts small, but keeps increasing after adding a node.

![bug](https://github.com/user-attachments/assets/01be08de-4555-4564-80bc-5ed57c8b2ff8)

**Comment by chrisgoringe** [comment]
separate issue. Can you see if it's still happening?

**Comment by chrisgoringe** [comment]
This is #197 related to horizontal recapping of the controller. I believe it is now fixed (and you can change the controller width...)

**Comment by JorgeR81** [comment]
> and you can change the controller width...

Can we do this in this version ?

----

> I believe it is now fixed 

This is mostly fixed,

In one of my workflows, it does not and it decreases size, by itself.

But this is an older workflow that also has other issues ( perhaps related to been created in an older version ? )

In this workflow, I was not able to save the image size even when the image was visible. 


![tx](https://github.com/user-attachments/assets/ee739fc8-de13-4b3f-8289-f87ff8e17e06)

---

**Comment by JorgeR81** [comment]
It may be a bug ... but it does look good in the narrow layout ... 

![na1](https://github.com/user-attachments/assets/fad44f34-b140-4f70-ba46-a15992a4c6e4)
