### ISSUE TITLE
[ Aesthetics ] Replace "Advanced controls" checkbox  with an icon button

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#198]
When the Controller is very narrow the label "Advanced controls" takes 2 lines.

Can you make it fit 1 line.

---

Another solution would be to replace the checkbox with an icon button, next to the refresh button.

If we mention this in the documentation, we don't need a text label, just an icon.

**Icon examples:** 
https://www.veryicon.com/icons/education-technology/radio-and-tv-cloud/advanced-setting.html
https://www.freepik.com/icon/advanced-options_15515
https://uxwing.com/quality-control-icon/

If the controls are hidden, the icon would be white.
And when we click to enable the Advanced controls, the icon would turn blue.

This way it would look better, more similar to ComfyUI.
And we also have more space for longer group names.

![adv](https://github.com/user-attachments/assets/e927286d-7981-481f-9869-a943444c1c03)

**Comment by chrisgoringe** [comment]
with tooltip...
![Screenshot 2024-10-24 115655](https://github.com/user-attachments/assets/9cd57d3e-ea0b-4e86-99f6-cfeb852ea6ef)

**Comment by JorgeR81** [comment]
Awesome !

**Comment by JorgeR81** [comment]
I was playing with the new button.
After toggling multiple times, a part of the Controller was gone, in the area of the sidebar.
The advanced controls were also triggering the sidebar, so that may be related.

Refreshing the browser fixes the issue. 

I took an image, but I was not able to replicate the issue.

![l1](https://github.com/user-attachments/assets/2abd85ca-08c8-4571-98b9-dd3371087df3)

**Comment by chrisgoringe** [comment]
I believe this was an issue with some code I briefly committed incomplete. Shouldn't recur.

**Comment by LukeG89** [comment]
It still happens: https://github.com/chrisgoringe/cg-controller/issues/138#issuecomment-2434785150

**Comment by LukeG89** [comment]
About the button, I like it! No more checkbox! 😆
