### ISSUE TITLE
[ bug ] Controller changes size, after switching workflows.

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#199]
This sometimes happens when I open the Controller, after switching workflows. 

The width starts normal and then decreases to the minimum. 
But it's fixed, if I resize manually. 

Also, the workflow's Controller "saved width" is not lost.
If I close and open the workflow again, the "saved width" is still there.

**Comment by JorgeR81** [comment]
Since the latest update, the Controller can also return to the default width, when it's opened ( instead of decreasing size ).

But my saved width is still there, if I re-open the workflow ( and the issue does not repeat itself ).

**Comment by chrisgoringe** [comment]
OK, I've reproduced this....

**Comment by chrisgoringe** [comment]
...and I think it's fixed.

**Comment by LukeG89** [comment]
Now everything seems fixed.

**Comment by JorgeR81** [comment]
Yes, this also seems fixed for me.
