### ISSUE TITLE
Default size to match other sidebar menus

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#201]

**Comment by LukeG89** [comment]
Perfecly matches!

**Comment by JorgeR81** [comment]
Now that auto-hide was reverted, this needs to be adjusted.

The Controller Sidebar is a little wider now.

The scrollbar width needs to be subtracted, from the total width.

**Comment by chrisgoringe** [comment]
I'm going to leave this as is, since it's a pretty minor issue, and the width has proven more fragile than expected. When the scrollbar is replaced it should all work.
