### ISSUE TITLE
[ bug ] Controller may resize if, scrollbar is toggled ( with adv controls )

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#203]
This can happen if I toggle adv controls, and it triggers the scrollbar.  

But it's hard to replicate. 
It only happened twice.
Once the Controller started to increase width and on the other time it started to decrease, to its minimum size.
 
When it was increasing in size, it would probably have reached max. size, to fit the entire screen, but you can stop it by  just grabbing the resize handle and changing it back. 

I think I also had this before.
But I'eve made a new issue to differentially form the other one:  https://github.com/chrisgoringe/cg-controller/issues/199 ( witch seems fixed )

**Comment by LukeG89** [comment]
Yes, happened to me a couple of times as well.

Could it be the scrollbar auto-hide the cause?

**Comment by JorgeR81** [comment]
> Yes, happened to me a couple of times as well.
> 
> Could it be the scrollbar auto-hide the cause?

This also happened to me in other cases, even before auto-hide.

But they are random, "one off" events. 

For instance, it happened in a previoues version, the first time I enabled the rghree progress bar. ( https://github.com/chrisgoringe/cg-controller/issues/149#issuecomment-2432731464 )

**Comment by chrisgoringe** [comment]
That's really my worry. Unpredictable one off bugs are the true enemy.

**Comment by JorgeR81** [comment]
In a future version, maybe if you also replace browser rescale, with a custom element, so that you have more control over it. 

It may be worth it now  (  https://github.com/chrisgoringe/cg-controller/issues/146#issuecomment-2416392414 )

This way it would allow users to click and drag across the whole border of the Controller ( not only the bottom ).

**Comment by chrisgoringe** [comment]
> > The rescale is provided by the browser. The cost/risk/benefit of replacing it seems unlikely
> 
> ( [#146 (comment)](https://github.com/chrisgoringe/cg-controller/issues/146#issuecomment-2416392414) )
> 
> In a future version, maybe you could also replace browser rescale, so that you have more control over it. 
> 
> It may be worth it now.
> 
> This way it would also allow users to click and drag across the whole border of the Controller ( not only the bottom ).

Yes, that was what I meant by "allow horizontal drag on the gutter" in #204

**Comment by LukeG89** [comment]
I'm testing many weird resizing stuff, but Controller window seems stable.
Maybe the bug is somehow solved?

**Comment by JorgeR81** [comment]
> I'm testing many weird resizing stuff, but Controller window seems stable.
> Maybe the bug is somehow solved?

Yeah, the only width inconsistency I notice is now, is due to reverting auto hide: https://github.com/chrisgoringe/cg-controller/issues/201#issuecomment-2435211388
