### ISSUE TITLE
Resize by dragging edges (was: Replace scroll bar with custom one)

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#204]
To have full control of appearance, certainty over the width, and allow horizontal drag on the gutter.

**Comment by LukeG89** [comment]
Maybe for the moment the auto-hide feature can be reverted? It's more troublesome than uselful in my opinion

**Comment by chrisgoringe** [comment]
Yes. #205

**Comment by JorgeR81** [comment]
Ideally a custom "auto-hide" scrollbar:

- allows to keep panel size, when visible 
- does not cover panels, when visible 

But how would this work in the Controller ?

Maybe an auto-hide "floating" scrollbar outside the Controller Sidebar.

Could this be possible ?

![bar](https://github.com/user-attachments/assets/0a2d10a0-cb06-4f94-9615-4032f26ca96e)

**Comment by chrisgoringe** [comment]
Yes, I think that could be possible... and it would look cool 😎

**Comment by chrisgoringe** [comment]
Combine with #282

**Comment by chrisgoringe** [comment]
I think the option to have the scrollbar or not is sufficient. So this is now changing to be 'allow resizing by grapping edge'
