### ISSUE TITLE
[ Aesthetics ] add margin between bottom slider and KSampler preview 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#207]
The full width `denoise` slider looks too bright next to the KSampler's preview image.

Is it possible to add a margin, like in ComfyUI

---

**Controller**

![prev](https://github.com/user-attachments/assets/9961b4b8-0233-4b88-8d81-f38dd1762a01)

---

**ComfyUI**

![prev2](https://github.com/user-attachments/assets/90281bdd-0d97-4a63-be48-dd2472d025a9)

**Comment by JorgeR81** [comment]
A better solution is just to have the margin on top of the image, instead of on the bottom.

That's what ComfyUI does.

And I just realised the Controller also worked like that !

That was before the margins between the sliders were reduced
It's in my image, that you've posted in the documentation. 

![m2](https://github.com/user-attachments/assets/b0601589-40a4-450d-b48c-05bd4b31a043)

**Comment by chrisgoringe** [comment]
done I think

**Comment by JorgeR81** [comment]
Symmetrical margins on top and above. Perfect !

![ks](https://github.com/user-attachments/assets/bc8976f1-2225-47a5-9a94-5e54186d80ff)
