### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#211]
https://github.com/chrisgoringe/cg-controller?tab=readme-ov-file#advanced-controls

> **Advanced controls**
> If there are nodes that you only occasionally need to interact with, you can designate them as 'advanced controls' when you add them to the controller. Advanced controls will only be shown if the 'Advanced controls' `checkbox is ticked`, and the node in the workflow gets an open circle in place of the dot in the top right.

- replace  `checkbox is ticked`, with `icon button is blue`

- maybe add an image of the icon or mention: `'gears' icon button is blue`

---

https://github.com/chrisgoringe/cg-controller?tab=readme-ov-file#images

> **Images**
> The Controller works with Load, Save and Preview image nodes, as well as the `imagwe` previews shown on the sampler node.

- fix typo

---

https://github.com/chrisgoringe/cg-controller?tab=readme-ov-file#settings

> **Settings**
> In the main settings menu are a few things you can tweak - `scrollwheel sensitivity`, hiding control_after_generate, and a keyboard shortcut to show or hide the Controller. There's also a debug setting that I might ask you to use if you report a problem!

- remove `scrollwheel sensitivity`
- mention keybinds for `Edit slider limits` and `scrolling`

**Comment by chrisgoringe** [comment]
thanks. done.

**Comment by JorgeR81** [comment]
The the main page image, I've noticed that your "live preview" looks very low quality.

![lq](https://github.com/user-attachments/assets/a0e262eb-12c3-479c-9d70-e7af9f715c1e)

I think you said you don't use this "live preview", right ?

In case you want to test it further, you need to add some files to ComfyUI models, get good quality previews:

https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#how-to-show-high-quality-previews
