### ISSUE TITLE
[ feature ] Open the `MaskEditor` from the Controller 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#214]
Now we can add `Load Image` nodes to the Controller. It works great.

But if we want to open the `MaskEditor`, we still need to find the node, in the the graph canvas. 

Can we have an icon button ( in the node header ) or a simple right click menu, to do that, from the Controller ?

---

This would be extra useful, if you have other extensions, that make your node's right click menu very large.

![rc](https://github.com/user-attachments/assets/5a37eb45-1567-41ba-98f7-039c532a518d)

**Comment by chrisgoringe** [comment]
done on 1.5 (ctrl-click the image)

**Comment by JorgeR81** [comment]
It's working !
