### ISSUE TITLE
long names in option can overflow when window shrunk

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#218]
![Screenshot 2024-10-28 083728](https://github.com/user-attachments/assets/5cd5f560-742f-4442-b617-f9f00043cb6b)

worse with larger font 

![Screenshot 2024-10-28 083844](https://github.com/user-attachments/assets/03cc60d5-8093-412c-9c82-014fba040817)

**Comment by JorgeR81** [comment]
If possible do what Comfy does:

![ddd](https://github.com/user-attachments/assets/47f11c85-28ea-4d95-b182-a31727e7a7b8)

----

And, can you also add an user option to hide the `.safetensors` part ?
