### ISSUE TITLE
[ bug ] Controller not updated if "advanced controls" are changed. 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#221]
The Controller is not updated, if I add a node to the "advanced controls", if that node was already added to the Controller. 
This issue only happens, if the "advanced controls" are disabled, when I make the change.

The Controller's refresh button does not update the changes, either.  
Only the browser's refresh button does.

---

Here, I made "Load checkpoint" an "advanced control", but it's still being displayed. 

![bug1](https://github.com/user-attachments/assets/e3febbc7-82fe-4541-a68c-9d056880afc3)

**Comment by chrisgoringe** [comment]
I can't reproduce this (on 1.1 branch),. Could you check, and if you can reproduce, give me a step-by-step?

**Comment by JorgeR81** [comment]
Sure:

- close all workflows, so that you can get the default workflow 

- add KSampler to the Controller, with `Include this node` ( this works correctly )

- add KSampler to the "Advanced controls", with `Include this node as advanced control` 

---

The KSampler is still shown, despite "advanced controls" being toggled off

![r1](https://github.com/user-attachments/assets/b8c33af9-ea61-43d2-8a81-568b2c219498)

---

Refreshing the browser, fixes this. 

![r2](https://github.com/user-attachments/assets/3694d10f-44cc-4289-9994-44f88c4613f0)

**Comment by chrisgoringe** [comment]
thanks, I'll check that out

**Comment by chrisgoringe** [comment]
Still can't reproduce...
![GIF 29-10-2024 12-38-43 PM](https://github.com/user-attachments/assets/7889307f-734e-4008-80dd-f085b4d58af7)

But I think I might have found the cause anyway. Let me know if it's still happening.

**Comment by JorgeR81** [comment]
It seems to be fixed now.

It's related to the Frontend. I did some more testing:

- This does not happen in the Frontend ( `v1.3.11` ) that ships with ComfyUI 

- It happened in the latest version ( `v1.3.25` ), I was using.

- But it seems it just got fixed with `v1.3.26`, released about 1 an hour ago :) 

- I reverted to  `v1.3.25` and the bug happens again.

**Comment by JorgeR81** [comment]
From now on, I will test with the Frontend that ships with ComfyUI
