### ISSUE TITLE
[Feature Request] Toggle button on topbar to show/hide Controller

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#227]
Floating Controller is always visible, even if you don't use/need it.

Would be better adding a simple toggle button on topbar, similar to the previous `Image Feed` but with the slider icon:

![image_feed_toggle_button](https://github.com/user-attachments/assets/43ffad5c-9937-448c-a7a5-d76322aba0e3)

This would also be useful for this kind of situations: https://github.com/chrisgoringe/cg-controller/discussions/219#discussioncomment-11075621

**Comment by chrisgoringe** [comment]
Using the sliders icon from before. Also reinstated the keyboard shortcut. Icon changes color for visible/hidden

![Screenshot 2024-10-29 115012](https://github.com/user-attachments/assets/237e036a-946b-48ab-a92b-659f80f66e2a)

**Comment by LukeG89** [comment]
I would only adjust the style (dark button, rounded corner, white icon when turned off) to match the other ones:

![comparison](https://github.com/user-attachments/assets/c1ef3801-cdb9-47db-bcd1-4e82b0215c9e)

**Comment by LukeG89** [comment]
> But, on second thought ...
> 
> - The current style allows to show the on/off state much better
> - It's a better match for the "native" and newer Queue buttons
> 
> It makes no sense to change our style, if it's a better match for the native style, right ?

Controller is an external extension, it can't be the only one with a different style. It seems like a ComfyUI controls button.

**Comment by JorgeR81** [comment]
> Controller is an external extension, it can't be the only one with a different style. It seems like a ComfyUI controls button.

Yeah, maybe the 2 buttons could be inside a similar dark box with rounded corners, to signal, they are from the same extension.

**Comment by JorgeR81** [comment]
About the top bar, I think I've seen a comment from you, about the large gallery button.

You can disable it in the Frontend extension settings.
This will disable the whole Image Feed, but we don't really need it now, with the queue sidebar.

![gal](https://github.com/user-attachments/assets/18fd23fe-f0ec-4e22-8dce-803c7ad1f3d2)
