### ISSUE TITLE
Snap to 

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#228]
Controller window snaps to edges of the window or other controller windows.

This is 'sticky' - repositioning due to changing window size should retain 'stick' wherever possible.

Think through whether 'stuck' controllers should move together.

**Comment by chrisgoringe** [comment]
See discussion https://github.com/chrisgoringe/cg-controller/issues/224#issuecomment-2442889597

**Comment by JorgeR81** [comment]
> 1 - If a Controller border touches a canvas border, it will always do so, unless the user changes this ( by dragging it or resizing it )
> 
> 2 - The position for the Controller will be changed, when needed, to to follow rule 1
> 
> 3 - If changing the position is not enough to fulfill rule 1, dimensions will be changed.
> 
> This last one is in case the Controller has full height ( if 2 opposite canvas borders are touched by the controller ).
> To fulfill rule 1, then you need to increase height.

---

To update this for multiple Controllers we need 2 extra rules:

4 - If controllers share borders, they will be considered as a single controller, in respect to the previous rules. 

5 - If rules 3 and 4 are applied, the dimension change will be splitted across these controllers.

The practical example would be having Controllers stacked vertically in 2 rows, across the full height.
If I go fullscreen I would want both rows to increase proportionally. 

Use case example:
( I would use this configuration to optimize space, because slider panels require less width )

![panels](https://github.com/user-attachments/assets/cce1cdbe-1a09-40f7-8617-a3998ccc3d46)

**Comment by chrisgoringe** [comment]
Yup.

What about if I move a controller which has other controllers snapped to
it? I think they move together? But then there needs to be a way to
separate them...

**Comment by JorgeR81** [comment]
> Think through whether 'stuck' controllers should move together.

> What about if I move a controller which has other controllers snapped to
> it? I think they move together? But then there needs to be a way to
> separate them...
> 

---

- To drag multiple windows snapped together, I would drag the window on the top / left. 

- To split them apart, I would drag one of the other windows.

**Comment by chrisgoringe** [comment]
yes, that's a neat solution.

**Comment by chrisgoringe** [comment]
What about size? I'm assuming that two controllers stuck together will be independantly resizable. 

But I'm not sure if that's right for resizing perpendicular to the 'stick' direction (ie width of vertically stacked, height of horizontally  stacked)

**Comment by JorgeR81** [comment]
Snapped windows would only resize together, if the added shape is as rectangle.

Like this:

![rs](https://github.com/user-attachments/assets/55044c46-4ae8-429a-8243-a5ea272b5d2a)

**Comment by JorgeR81** [comment]
To resize Controllers independently, in an overall rectangle shape, you could change the interior's border position.
But the overall dimension remains the same.

![rs1](https://github.com/user-attachments/assets/118f1bc8-ee91-47a3-a809-c8587100f2b2)

**Comment by chrisgoringe** [comment]
I think this will need some clear visual hint that windows are snapped together!

**Comment by JorgeR81** [comment]
> I think this will need some clear visual hint that windows are snapped together!

Do you mean always or only when we are dragging ?

**Comment by JorgeR81** [comment]
Maybe the best it to just to just stick with these 2 simple rules:

1 - Windows snapped together and always resized independently.

2 - The only expansion to rule 1 is if the canvas does not allow more space.

---

So in this case the blue border would move, because it has space to do so.

**Comment by LukeG89** [comment]
> In this case, if I drag an interior border ( red arrow ) what will happen ? Will the blue border also be displaced automatically ( blue arrow ) ?
> 
> What would make more sense / be more usefull ?

The red internal resizing should not affect the blue one, but if you grab the blue border you should resize sliders (proportionally?) and image preview at the same time.

**Comment by JorgeR81** [comment]
> I think this will need some clear visual hint that windows are snapped together!

---

If we make it clear, in the documentation, that we have a snapping feature, I think the users would just assume that adjacent windows forming rectangle, are snapped, 

![tabs17](https://github.com/user-attachments/assets/d5f951de-48ed-4391-b259-5c46471cae65)


---

While moving or resizing the whole rectangular shape, we could show a highlight around it.

![tabs17h1](https://github.com/user-attachments/assets/bb14decb-0044-43ce-98cd-a054666c57e9)


---

To resize internal borders ( while keeping the overall dimensions ), we have a highlight line in between the window borders.
Maybe in a different color ( here I have the blue accent color used by Comfy UI )

![tabs17h2](https://github.com/user-attachments/assets/ec20ebdf-3574-4bf2-93ed-b1318d3f3fae)

**Comment by JorgeR81** [comment]
> I think this will need some clear visual hint that windows are snapped together!

When Controller windows are snapped together they could share the same border. 

This is not a mockup. 
We can get this effect, in version `1.2`, moving the windows slightly on top of each other, and it looks good ! 

---

![cn2](https://github.com/user-attachments/assets/2c13d05f-7e3d-491f-bb08-99c2a0d5280a)

**Comment by LukeG89** [comment]
What about this effect when resizing windows?

- https://github.com/Comfy-Org/ComfyUI_frontend/pull/1414

**Comment by JorgeR81** [comment]
> What about this effect when resizing windows?

Looks good !
