### ISSUE TITLE
Controller on top of side menus

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#230]

**Comment by LukeG89** [comment]
It's still under the menu

![Controller_under_menu](https://github.com/user-attachments/assets/8a60553e-914d-45a3-ba98-852586d7ade3)

**Comment by chrisgoringe** [comment]
I think that's correct behaviour? Anyway, those controls and the drop down menus are on the same layer, so can't be over one and under the other!

**Comment by LukeG89** [comment]
@chrisgoringe Just reported it because the title says "Controller on top of side menus", you meant another thing?

**Comment by chrisgoringe** [comment]
No, that was what I meant. But on further investigation I concluded it
wasn’t wrong.

Also the side control is on the same layer as the drop down menus, so can’t
be on top of one and under the other!

I think this is the best (or to make it better would be way too much work!)

**Comment by LukeG89** [comment]
Yeah yeah, I don't mind it! Also, minutes ago they implemented "Focus Mode" in the next frontend release, it would be useful to get rid of all the menus!
