### ISSUE TITLE
[Bug] Toggle on/off doesn't work in 1.2 Controller 

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#234]
https://github.com/user-attachments/assets/07848946-2753-43a6-9c0c-9eabafb55a99

**Comment by chrisgoringe** [comment]
can you (a) check you have the latest version and if so (b) check the javascript console.

**Comment by LukeG89** [comment]
a. It wasn't. I updated and now the toggle button is gone:

![no_icon](https://github.com/user-attachments/assets/7d2fa5e9-f480-45cb-a56b-0af5cf235d14)


b. Errors in console:

![console_error](https://github.com/user-attachments/assets/b944cd00-cc97-4241-ad54-4255e388ed18)
