### ISSUE TITLE
[ feature ] move refresh button to the top bar

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#236]
When we have multiple windows, it does not make sense to have a refresh button in each window.

**Comment by LukeG89** [comment]
Makes sense, but this would occupy other space on topbar...

Obviously not as much as this nonsense😠

![show_image_feed](https://github.com/user-attachments/assets/96a4d94b-9aa8-4697-85b3-133386755bf6)


But this is my topbar with all the extension buttons:

![topbar](https://github.com/user-attachments/assets/80e58d15-010f-4dad-9de8-78ac5beb0d85)

We should consider carefully if it is necessary to place another button in there! 😅

**Comment by JorgeR81** [comment]
> Makes sense, but this would occupy other space on topbar...

Yeah, but the free space in the Controller window will be much smaller and more valuable.

---

And you can hide the gallery button in the front end extension settings  
With the new Queue sidebar, we don't need the gallery.

![gal](https://github.com/user-attachments/assets/f03ef3d4-cf34-4d33-8ac2-ae2556353012)

---

I also hide the rgthree buttons. 

![rg3](https://github.com/user-attachments/assets/d0b2cd54-4f81-43c7-8c05-bdb829ad3522)

---

And the Manager buttons will be smaller in the future

https://blog.comfy.org/making-new-ui-the-default-option-on-2024-11-15/

**Comment by LukeG89** [comment]
> And you can hide the gallery button in the front end extension settings
> With the new Queue sidebar, we don't need the gallery.
> 
> I also hide the rgthree buttons.

I know that, I just activated them all to show the situation of many users. It's limited out there, better keep the little icon on the main window.

**Comment by JorgeR81** [comment]
I've made a mockup with the 2 buttons, in the current style.

![qm](https://github.com/user-attachments/assets/0d3c7c52-f236-4968-8e69-43b603c6cee1)

**Comment by JorgeR81** [comment]
> better keep the little icon on the main window.

I propose this :

- have the button in the top bar by default 
- have an user option to hide it ( like rgthree does )
- never don't show the button in the windows

See the mockup.
It would look silly to have this button duplicated 3 or 4 times across the GUI
The same button will affect all the windows. It would not make sense.
And we barely have space to fit 2 tabs, in each window.  

![tabs17](https://github.com/user-attachments/assets/87c328a4-75f2-40e6-aa60-5a2a5e2a1b9e)

**Comment by LukeG89** [comment]
> I've made a mockup with the 2 buttons, in the current style.

Ok, I can live with that!

> I propose this :
> 
> - have both buttons in the top bar by default
> - have an user option to hide the sidebar buttons ( like rgthree does )
> - add a shortcut to refresh ( ComfyUI already uses r to refresh the nodes; we could have e by default )
> - don't show the button in the windows

Only if there are no easier alternatives (like "auto-refresh" on changes)

**Comment by JorgeR81** [comment]
> Only if there are no easier alternatives (like "auto-refresh" on changes)

At some point this was being done. But some cases were not updating.

The button is just for non essential changes like color and title name.
And any interaction with the Controller will also update it.
I think it wastes resources to keep looking for these changes ( more CPU usage ? )

**Comment by chrisgoringe** [comment]
Yes, exactly. To update whenever anything changes is a heavy load (the UE
nodes struggle with that!). And if you just try to follow some things,
you’ll miss some!

It could be done by toggling the controllers off then on, if we wanted to
save real estate, or with a right click menu. But they aren’t as obvious.

**Comment by LukeG89** [comment]
@chrisgoringe At this point a button on topbar is the easiest choice 👍
