### ISSUE TITLE
Have "Not in group" option

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#237]

**Comment by LukeG89** [comment]
Have you removed the "Ungrouped" option? It doesn't appear anymore when adding a group

![groups](https://github.com/user-attachments/assets/9f57aea9-a33b-4588-8a84-99b5e37e0359)

**Comment by chrisgoringe** [comment]
Do you have any controller nodes not in a group? It should appear but only if there are any

**Comment by LukeG89** [comment]
Yes, tested again

![test](https://github.com/user-attachments/assets/6a29c643-400c-41df-bfcc-5488b962bf81)

**Comment by chrisgoringe** [comment]
Ah, silly me. Fixed.

**Comment by LukeG89** [comment]
Yes!
