### ISSUE TITLE
[Bug] Controller disappears in Focus Mode (New frontend feature)

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#239]
Branch 1.2

Controller completely disappears when you enter in Focus Mode, and doesn't appear again when you exit.
You need to refresh the page.

https://github.com/user-attachments/assets/07dec241-5d3c-4ae2-a8be-0f833f61871f

**Comment by LukeG89** [comment]
@chrisgoringe Are you using the nightly frontend? If so, you can press F.

**Comment by chrisgoringe** [comment]
No. I use the frontend released with Comfy main releases.

**Comment by LukeG89** [comment]
Ah ok, this is a brand new feature. They will probably implement it in ComfyUI in a week

**Comment by JorgeR81** [comment]
Once this is fixed, maybe you can add an user setting to:

- `Hide controller in Focus mode`

Some people may want use this new mode just to see the nodes.

**Comment by LukeG89** [comment]
> Once this is fixed, maybe you can add an user setting to:
> 
> * `Hide controller in Focus mode`
> 
> Some people may want use this new mode just to see the nodes.

People can do it by hiding controller before entering Focus Mode.

**Comment by JorgeR81** [comment]
> People can do it by hiding controller before entering Focus Mode.

Yesh, but this way it will be a single press.

Now we would need to press 2 keys.  
And press 2 keys again, to return to normal mode.

**Comment by chrisgoringe** [comment]
The real bug is that the controller doesn't appear again, so that's what I'll fix here.

#308 added to allow an option.

**Comment by chrisgoringe** [comment]
Fixed on dev. Currently the controller does not appear in focus mode; that will become possible (as an option) with #308

**Comment by LukeG89** [comment]
It works this the shortcut, but Controller doesn't appear when using the new toggle button to Focus Mode (added in 1.3.36 frontend)


https://github.com/user-attachments/assets/60534c1d-52b7-4190-9a50-ce7c3044e029

**Comment by JorgeR81** [comment]
>  (added in 1.3.36 frontend)

Yes, released just 10 hours ago ... that's probably why they moved the refresh button ... 

https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.3.36

**Comment by chrisgoringe** [comment]
Does it appear again for you if you then click on the canvas (or do more or less anything)? It does for me...

**Comment by JorgeR81** [comment]
> Does it appear again for you if you then click on the canvas (or do more or less anything)? It does for me...

Ah yes, it does that !

**Comment by chrisgoringe** [comment]
in that case, I think I've fixed it properly. See if the latest dev works properly.

**Comment by JorgeR81** [comment]
It's working.
