### ISSUE TITLE
[Bug] Fullscreen and Console stack Controller windows (one-time issue) 

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#241]
Branch 1.2

Same issue reported by @JorgeR81 https://github.com/chrisgoringe/cg-controller/discussions/232#discussioncomment-11093663

https://github.com/user-attachments/assets/c3940d25-248a-4123-be49-c3bfb8e67c33

The issue is fixed when you refresh the page.

**Comment by chrisgoringe** [comment]
How are you going fullscreen there?

**Comment by LukeG89** [comment]
Pressing f11

**Comment by chrisgoringe** [comment]
I can't reproduce this problem...

**Comment by LukeG89** [comment]
Try this:

- Create new default workflow (don't save or anything)
- Create new controllers and move them apart
- Go fullscreen or open console

If you can't reproduce this way, it's possibly the frontend version (I'm on 1.3.28)

**Comment by JorgeR81** [comment]
> Try this:
> 
> - Create new default workflow (don't save or anything)
> - Create new controllers and move them apart
> - Go fullscreen or open console

> If you can't reproduce this way, it's possibly the frontend version (I'm on 1.3.28)

Yeah, now I can reproduce the issue..

An there is a way to "fix" it:

- save de worflow.
- close the worflow
- open it again ( now the issue does not happen )

**Comment by LukeG89** [comment]
@chrisgoringe This issue is not fixed yet, it still happens to me (sometimes also when I switch tabs in browser)

**Comment by chrisgoringe** [comment]
Any reliable way to reproduce?

Also, next time it happens, please immediately look for errors in the javascript console.

**Comment by LukeG89** [comment]
> Any reliable way to reproduce?

Same instructions as before:

> - Create new default workflow (don't save or anything)
> - Create new controllers and move them apart
> - Go fullscreen or open console

> Also, next time it happens, please immediately look for errors in the javascript console.

I don't get any errors


https://github.com/user-attachments/assets/e174d428-c94e-4e7b-95fe-0d6a3fa809b9

**Comment by LukeG89** [comment]
Seems fixed in 1.4!
