### ISSUE TITLE
nodeblocks can be moved between controller panels (was [Bug] You can move controllers from one window to another)

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#244]
Branch 1.2

Is it a normal behavior?

https://github.com/user-attachments/assets/9ec09145-e912-4956-b928-235c8d590489

**Comment by chrisgoringe** [comment]
Hah. No. That shouldn't be permitted. All sorts of nasty things might be unleashed.

**Comment by LukeG89** [comment]
This is fixed, but the fixing introduced this new bug: https://github.com/chrisgoringe/cg-controller/issues/247
