### ISSUE TITLE
[Bug] KSampler seed widget doesn't change when reaching high values through Controller

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#245]
Branch 1.2

https://github.com/user-attachments/assets/6f519ef9-7ee8-47b8-a07f-553cbb6d671c

**Comment by LukeG89** [comment]
The max value that KSampler seed can reach seems to be: 1125899906842624

**Comment by JorgeR81** [comment]
I think that's just the limit rgthree has set for the node.

If I disable the Controller ( in the Manager ) I also have this limit.

We are noticing it now, because with the sliders it's much easier to reach higher seed values. 

![rg3](https://github.com/user-attachments/assets/4eae6475-e958-4965-9b96-fac9bef16750)

**Comment by LukeG89** [comment]
> I think that's just the limit rgthree has set for the node.

I have not used rgthree in my testing, I think it's a global limit in ComfyUI.

> We are noticing it now, because with the sliders it's much easier to reach higher seed values.

@chrisgoringe The max. default value of the seed should be changed.

**Comment by JorgeR81** [comment]
OK, so we can set a higher value, but it's changed when we click to generate.

But this also happens to me, even if the workflow does not have a controller.

**Comment by chrisgoringe** [comment]
There are some issues around the maximum integer permitted in javascript (or rather, the maximum 'safe' integer).

I think this should now be working on 1.2

**Comment by LukeG89** [comment]
Yes it's working! So now with Controller the limit is overwritten? It reaches 9007199254740991 and you can generate with it!
