### ISSUE TITLE
[Bug] Can't rearrange Controllers (after fixing #244)

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#247]
Branch 1.2

Bug introduced after fixing this issue: https://github.com/chrisgoringe/cg-controller/issues/244

https://github.com/user-attachments/assets/70bfc19c-4801-4f7a-8258-4e24c940f5eb

**Comment by chrisgoringe** [comment]
Try now

**Comment by LukeG89** [comment]
It's working again!
