### ISSUE TITLE
[ feature ] group selection via tabs

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#249]
I noticed we don't have an issue for this.

The controller window could look similar to the mockup, but with:

- round tabs
- a tab for nodes that are `Not in group` ( https://github.com/chrisgoringe/cg-controller/issues/237 )
- maybe no refresh button ( https://github.com/chrisgoringe/cg-controller/issues/236 )
- maybe a bypass button ( https://github.com/chrisgoringe/cg-controller/issues/89 )

The icon set ( https://www.primefaces.org/diamond/icons.xhtml ) does not have a bypass icon,
( https://www.svgrepo.com/svg/503241/bypass ).

So maybe we could use of these:
( Because we are "skipping" over the bypassed nodes ).

![ico](https://github.com/user-attachments/assets/3a8a1858-18e6-4eef-a9e5-2d4bd06b15ae) ![ico2](https://github.com/user-attachments/assets/c0de1713-e6a7-4d1d-b099-3b319d92c96a)

---

![tabs167b](https://github.com/user-attachments/assets/be4a0114-b921-451b-a328-8c8161f88b84)

**Comment by LukeG89** [comment]
Other alternative icons could be:

![ban](https://github.com/user-attachments/assets/b7dc832f-9f9b-4f1a-b41a-4dbe743db2b5)
![power_off](https://github.com/user-attachments/assets/fc42a16c-e6f9-41e6-9bf0-7d49979346c4)
![pause](https://github.com/user-attachments/assets/10b29cd8-40a0-4431-96d6-9b58f7f122eb)

**Comment by JorgeR81** [comment]
Yeah, a round icon may look better next to the bolt.

 But `power off` would not make sense ( it's the oposite ).

The `ban` icon could work.
And instead of getting blue, it could get the bypass color !

**Comment by chrisgoringe** [comment]
Trying to think through groups and multiple controllers and tabs...

I think the proposal is to eliminate the current drop-down element, and instead select the group using tabs.

Question: what tabs should be available on a controller?

Option 1 would be to have all of them (like the current drop-down list). That seems to go a little against the idiom of tabs (especially if you have two controllers - they all show all the tabs) and is also a waste of space (again, especially with multiple controllers all showing all tabs)

Option 2 would be that each controller only has tabs that have been added to it somehow. I'm thinking maybe something like this:

- a new controller gets the "All" tab
- the '+' creates a new tab by popping up a drop down menu to choose which group it should be for
- each tab has an 'x' on it (like browser tabs) to close that tab
- close the last tab and the controller closes (so maybe no need to have the controller 'X' any more)
- when minimised, the currently selected tab forms the title, and only the 'expand' (and bypass) icons are available

thoughts?

**Comment by chrisgoringe** [comment]
There's an initial version of this (option 1, because that's simpler to do first), on the 1.3 branch

**Comment by LukeG89** [comment]
Love the design!

![tabs](https://github.com/user-attachments/assets/3b1e3502-4b8a-42d2-bedd-22de96192dbe)

Definitely option 2. Doesn't make sense to have all tabs open. People should be able to keep specific tabs open on each Controller windows.

**Comment by JorgeR81** [comment]
Looks great !

Yeah, option 2 would be the best.

**Comment by LukeG89** [comment]
I would also make them rearrangeable by adding a small handle (3 vertical dots) to the left of each tab, to grab them individually (and perhaps move them from one window to another).

**Comment by JorgeR81** [comment]
> I would also make them rearrangeable by adding a small handle (3 vertical dots) to the left of each tab, to grab them individually (and perhaps move them from one window to another).

I'd like that.

But, if we have multiple rows, rearranging tabs will not be very useful.
Because tabs change positions when they are selected.

We could have an user option to always keep tabs in a single row:
- the text would be partially hidden, if there is not enough space ( like on the browser )

---

And to save tab space, ( for both multi-row and single-row modes ): 

- Instead of 3 dots, we can grab the whole tab to move it.
- To move a Controller, grab it by the buttons area.

and maybe:

- No the "x" button. To remove a tab, drag it out of the Controller ( on to the graph canvas area )

**Comment by chrisgoringe** [comment]
Don’t think I’m going to make the tabs draggable as a priority - seems
pretty low benefit/cost…

**Comment by JorgeR81** [comment]
> Don’t think I’m going to make the tabs draggable as a priority - seems pretty low benefit/cost…

And what do you think about a "single row" mode ?

**Comment by chrisgoringe** [comment]
Yeah, that's fairly simple. Might be best just to make it always like that (having lots of tabs probably isn't going to be normal)

**Comment by JorgeR81** [comment]
> Might be best just to make it always like that (having lots of tabs probably isn't going to be normal)

Yeah, and also having tabs changing places is bad for "muscle memory" when we use the GUI.

And with group colors, we probably just need to see the first letter of a group name to recognize it.

**Comment by JorgeR81** [comment]
Remember this old Chrome tab design:
https://www.reddit.com/r/chrome/comments/11sfwca/remember_this_layout/

I realise this is probably not possible to do here.
Just wanted to share the idea / mockup.
 
It would make the active tab more noticeable, and it would look cool :)

![dt4](https://github.com/user-attachments/assets/c17c7801-68cb-4012-a22e-8ac5950966a1)

![dt](https://github.com/user-attachments/assets/e9fb7c17-bc46-482b-a2e7-360442ce8235)

**Comment by LukeG89** [comment]
I prefer the current design (color highlighting + horizontal line are more than enough to notice them)

**Comment by JorgeR81** [comment]
> I prefer the current design (color highlighting + horizontal line are more than enough to notice them)

Yeah, the current tab design is functional. 

And I suspect the other design will be very hard to do.

But, if it's easy, we could have it as an option.

**Comment by LukeG89** [comment]
To improve the current design, the bottom corners could be made smoother between the tabs.

![hard_tabs](https://github.com/user-attachments/assets/86f6d6a4-55de-48ed-9148-7e30da3d57bc)

![smooth_tabs](https://github.com/user-attachments/assets/e303e4fa-6f6a-4b5d-b649-a208d52d46b2)

**Comment by chrisgoringe** [comment]
Yeah, outflares like that turn out to be very non trivial...

**Comment by JorgeR81** [comment]
> To improve the current design, the bottom corners could be made smoother between the tabs.

> Yeah, outflares like that turn out to be very non trivial...

Yeah, that's why I thought the other design would be hard to make.

**Comment by JorgeR81** [comment]
What if the non-selected tabs were "floating tabs" ?

This design would be easier to do, and it would make the selected tab more noticeable.  

---

![dt6](https://github.com/user-attachments/assets/f4b5a469-1561-4b5d-bc69-7a3be8283ddd)

![dt](https://github.com/user-attachments/assets/63de454f-2351-4153-b281-b2cf6366ab2b)

**Comment by chrisgoringe** [comment]
That looks possible... I'll take a look.

But I also want to get into the snapping :)

**Comment by chrisgoringe** [comment]
![Screenshot 2024-11-02 003114](https://github.com/user-attachments/assets/6516c360-9a16-4f81-91f8-49d6f9412d7c)

**Comment by JorgeR81** [comment]
Looks good !

**Comment by JorgeR81** [comment]
Now even the multi row layout seems easier to understand !

Perhaps we should keep it as an option, if it does not make the code music more complex. 

![mc](https://github.com/user-attachments/assets/35ce7dfc-ae1c-49eb-b171-84b33c62469b)

**Comment by LukeG89** [comment]
Group buttons are back! 😆

**Comment by JorgeR81** [comment]
Yeah, with buttons maybe we don't even need the colored line at the bottom.
This just distracts from the active button. 

![tb4b2](https://github.com/user-attachments/assets/cedd481e-1355-4b33-993d-303549b13981)

**Comment by LukeG89** [comment]
There are too many icons in my opinion, especially if you want to keep a single row.

I would do like Chris said:
> - each tab has an 'x' on it (like browser tabs) to close that tab
> - close the last tab and the controller closes (so maybe no need to have the controller 'X' any more)

But I would make the “x” appear only on mouseover (or even when the mouse hovers on the right side of the tab/button?)

**Comment by JorgeR81** [comment]
> There are too many icons in my opinion, especially if you want to keep a single row.
> - each tab has an 'x' on it (like browser tabs) to close that tab

Yeah, but if we make all tabs larger to fit the 'x' buttons, we have even less space for a single row.

> But I would make the “x” appear only on mouseover (or even when the mouse hovers on the right side of the tab/button?)

That could be a good solution, but when we mouse hovers the tab it would need to increase size to fit the button.
And the button text may also need to shift to accommodate the "x" button.
That may somewhat confusing ... I would need to try it ...

**Comment by LukeG89** [comment]
> Yeah, but if we make all tabs larger to fit the 'x' buttons, we have even less space for a single row.
That could be a good solution, but when we mouse hovers the tab it would need to increase size to fit the button.
And the button text may also need to shift to accommodate the "x" button.

I would simply make the x appear on top of the title, no need to reserve a space for it

**Comment by JorgeR81** [comment]
> I would simply make the x appear on top of the title, no need to reserve a space for it

That could work !

And it could also show the button to bypass.
The omitted group tab could use the bypass color  ( on the whole tab or maybe just as highlight ) ( not pictured ).

If mouseover it's not possible, we could use Ctrl+click to show it, like the slider edit menu.

![x1](https://github.com/user-attachments/assets/16760f1a-7053-4456-8b4c-3097a6eb7845)

**Comment by LukeG89** [comment]
> I would simply make the x appear on top of the title

Honestly, I meant another thing with my comment, I should have said "over the title" (the x still inside the tab)

But I like the concept you made (and removed 😆 )! More space and less visible icons!

**Comment by LukeG89** [comment]
What if all icons (except for +) are moved to a new bar right under group tabs/buttons?

![concept_group_bar](https://github.com/user-attachments/assets/ef36e21f-486e-4543-9c2f-2b96523cdcfe)

**Comment by JorgeR81** [comment]
> What if all icons (except for +) are moved to a new bar right under group tabs/buttons?

I think a row just for buttons would waste a lot of space.

I would probably need 3 rows, just to have 3 tabs.

![x1z1](https://github.com/user-attachments/assets/e4ba749e-9b53-452e-8bc2-4728bd774c12)

**Comment by LukeG89** [comment]
Well, it's not that bad! Buttons would waste space anyways, at least this way they are more accessible.

P.S. You forgot the X in the mockup

**Comment by JorgeR81** [comment]
> P.S. You forgot the X in the mockup

Ah, OK, so this would replace all overlaid buttons.

Here it is:

![x1z2](https://github.com/user-attachments/assets/2d7cdbc3-199c-4f43-943e-a0cff7457887)

---

Here is a single row, with all 5 buttons. 

![tab6](https://github.com/user-attachments/assets/7b333b67-131a-41f9-9cca-ee1882268fb8)

**Comment by LukeG89** [comment]
Nice!

Maybe in the future there will be space for other buttons, like show/hide hidden widgets!
-  https://github.com/chrisgoringe/cg-controller/issues/143

(Pythongosssss made a PR for this feature in ComfyUI)
- https://github.com/Comfy-Org/litegraph.js/pull/250

**Comment by chrisgoringe** [comment]
Yes.

Hopefully Pythongosssss's PR will get adopted and we can just riff off that!

**Comment by chrisgoringe** [comment]
I implemented (just visually) and I find the minimise and remove ( _ X ) buttons being on the second row really feels wrong (they are window actions, they are always top right).

So it's slightly less tight use of space, but this just feels better:

![Screenshot 2024-11-02 100208](https://github.com/user-attachments/assets/93d79f31-c3f5-481e-a84a-8ee3073f5354)

will see what it's like with multiple tabs...

**Comment by JorgeR81** [comment]
> So it's slightly less tight use of space, but this just feels better:

Yes, it does look better.
I think it's worth it to lose that extra space.

**Comment by JorgeR81** [comment]
> There is enough space for other buttons in the future, like show/hide hidden widgets!

Do we really need a separate button for that? 

If you want to see "advanced nodes", you would probably also want the "advanced widgets".
The bolt icon could enable both at the same time.

If we had 2 buttons I feel like I would just mistake one for the other, all the time.

**Comment by chrisgoringe** [comment]
OK, this is now on 1.3

**Comment by chrisgoringe** [comment]
One thing I've added having used it:

if there is only one tab, clicking on it allows you to select a different tab

This is because I find I kept on adding a tab and then switching back to remove the old one (esp. on new controllers)

**Comment by LukeG89** [comment]
Awesome! 🎉 

![test](https://github.com/user-attachments/assets/4fbe7528-2cda-4b82-9b23-c8f55af4c13c)

____

> > if there is only one tab, clicking on it allows you to select a different tab

> I'm not able to do this.
> Clicking on the ( single ) tab, has no effect.

Same as @JorgeR81 

> But a better solution could be to have a button to replace tabs.
> It could work even if there are multiple tabs.

Yeah, that would be nice, especially if you opened many tabs and you want to replace the first one

____

I found a bug: the image in previous Controller get resized when you create and click on a new Controller window


https://github.com/user-attachments/assets/6cd1b050-c119-4119-a765-a9622432c43f

**Comment by chrisgoringe** [comment]
Sorry - I hadn't pushed my latest changes.... updated now!

**Comment by chrisgoringe** [comment]
Raised #264 for the image resize bug

**Comment by JorgeR81** [comment]
> if there is only one tab, clicking on it allows you to select a different tab

This works very well. We could keep this.
 
And the 'replace' button will only show up, if there is more than 1 tab, in the Controller.
( Just the same way as the "Advanced Controls" button only shows up, if there are advanced control nodes, in the group ).
