### ISSUE TITLE
If min set to zero limits not applied (was [ Bug ] the native widget's range is overridden by slider edit, was slider min/max are overridden...)

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#251]
I if set the KSampler `steps` slider min. to 0, then I can go beyond the slider limits, using the scroll wheel. 

![bb1](https://github.com/user-attachments/assets/d7ee08a4-9e4a-4c04-b95f-79629d0fc3a8)

![bb2](https://github.com/user-attachments/assets/12edd265-2ca9-4523-a819-80d0c9b0e128)

![bb3](https://github.com/user-attachments/assets/b2d7cc8f-5ff1-4ab9-8806-72a80f7653b6)

**Comment by JorgeR81** [comment]
I think the main issue there is that the "native" widget limits are not being respected.

The Ksampler step size min. is 1

But in the controller I can set it to zero or a negative value.

( e.g. I can set it to -3, and all KSamplers will use this range, even if they are not connected to the controller ).

**Comment by chrisgoringe** [comment]
Overriding the widget limits is by design. Sometimes you want to be able to do it.

The set to zero should now be fixed.

**Comment by chrisgoringe** [comment]
Added #252 as an idea - keep the limits as a warning, and have a 'reset' button

**Comment by JorgeR81** [comment]
OK, scroll beyond ten limits is fixed. 

> Added https://github.com/chrisgoringe/cg-controller/issues/252 as an idea - keep the limits as a warning, and have a 'reset' button

Yeah, I think this is a good solution.
