### ISSUE TITLE
[Bug] Load Image not updating the preview

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#255]
Branch 1.2

https://github.com/user-attachments/assets/36a51728-7f46-4a96-af59-365e20d6adaf

**Comment by JorgeR81** [comment]
I also have this issue.

I need to click the Controller's refresh button, to fix it.

**Comment by chrisgoringe** [comment]
fixed on dev

**Comment by LukeG89** [comment]
Yes it's working!
