### ISSUE TITLE
[ bug ] sliders flicker when the controller is refreshed  

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#256]
Sliders flicker when I click the refresh button.
But this does not happen in all controllers. 

It seems the last controller to be created it's the one that flickers. 

---

Here, I took a screenshot, when I was clicking on the refresh button.
The Controller on the left does not flicker, but it still updates successfully.

![flick](https://github.com/user-attachments/assets/1cba221a-b2e6-4684-b627-eca7c19d76a5)

----

Even wih the same nodes, only some Controllers flicker.

![cn1](https://github.com/user-attachments/assets/834bd544-d6f6-43f6-bffd-d74bf6c30c63)

**Comment by LukeG89** [comment]
I can confirm, I created 4 windows displaying the same KSampler, and always the last one is flickering.


https://github.com/user-attachments/assets/54ec5a8d-7c7f-47d0-be80-8be9067ccb3d

**Comment by chrisgoringe** [comment]
should be fixed on dev

**Comment by LukeG89** [comment]
Tested on dev, seems fixed!
