### ISSUE TITLE
[Bug] Loaders update only when mouse leaves Controller

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#260]
Branch 1.3

https://github.com/user-attachments/assets/7f7a83e6-0492-4a11-b697-68b6ce99a787

**Comment by LukeG89** [comment]
Same thing in KSampler dropdown widgets

**Comment by chrisgoringe** [comment]
Hmm. Thought I'd fixed that. Possible I haven't push that code yet!

**Comment by chrisgoringe** [comment]
Try now

**Comment by LukeG89** [comment]
Fixed!
