### ISSUE TITLE
Progress bar or similar

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#261]
Maybe ask rgthree if we can borrow theirs!

**Comment by JorgeR81** [comment]
I'm using the rgthree progress bar it right now!

I don't think we need to replicate this functionality.

![rg3](https://github.com/user-attachments/assets/145ae52b-b937-4d7d-b72b-1bdafac81d8f)

---

You've thought about this, in case people use the Controllers to cover the whole GUI, right ? ( https://github.com/chrisgoringe/cg-controller/discussions/232#discussioncomment-11101640 )

To have a traditional GUI experience.

But for this use case, there's a more usefull feature: https://github.com/chrisgoringe/cg-controller/issues/263

**Comment by JorgeR81** [comment]
Instead of a large progress bar, it would be better to show a small progress in each node's header, like ComfyUI.

**Comment by chrisgoringe** [comment]
done on dev

**Comment by JorgeR81** [comment]
Looks good !

But I think it could be thicker, for better visibility.

Here is at 1920 x 1080 resolution.

It could be 4 px ( insteed of 2 ).
It could be at the same level of the header line 

![bar01](https://github.com/user-attachments/assets/26a0a8b0-dbf0-4b33-8c83-720b6635d7bb)

**original:**

![pp1](https://github.com/user-attachments/assets/60c0a3b7-b2e9-4025-b2f5-7ff9ab6768b1)


**mockup:**

![pp2](https://github.com/user-attachments/assets/8f68d3e4-2382-4da0-b8d3-dfe0e15ae22a)

**Comment by JorgeR81** [comment]
By the way the colored nodes, now have a "border effect".

But I like the way it looks !

![c2](https://github.com/user-attachments/assets/c1f903e3-6b05-4a19-95c5-dc4c1cef5ac0)

![c1](https://github.com/user-attachments/assets/97d4962c-154b-4438-bfbe-d4f915664e25)

**Comment by chrisgoringe** [comment]
tweaked a little

the borders was an accidental by-product of highlighting the active node, but I like it :)

**Comment by JorgeR81** [comment]
Looks great !
