### ISSUE TITLE
[ Bug ] The slider edit menu does not close after saving

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#267]
You can still save your changes, but the menu is not closed.

You need to click "Cancel" to close it.

**Comment by LukeG89** [comment]
I don't have this problem, it works to me

**Comment by JorgeR81** [comment]
I tried again and it works now !
I can't replicate it. 

I think I had multiple workflows and other programs opened, at the time. 
I will reopen, if it happens again.
