### ISSUE TITLE
refresh controllers don't always refresh when comfy refreshes node definitions

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#268]
to pick up new options in the loaders

**Comment by chrisgoringe** [comment]
I’d really like to make the refresh button redundant anyway, by picking up
changes as they happen. Some of the stuff I’ve been doing recently has been
towards making that possible.

**Comment by chrisgoringe** [comment]
done on dev

also - refresh button now gone. I think it's now redundant.

**Comment by JorgeR81** [comment]
I'm on `dev`, and updated, but I don't have this.

**Comment by chrisgoringe** [comment]
do you still have the update button?

**Comment by chrisgoringe** [comment]
If you have Use Everywhere nodes installed, could you make sure they are updated as well? There might be a conflict.

**Comment by JorgeR81** [comment]
> do you still have the update button?

Yes, now it's gone. 
The Comfy UI refresh also works in the Controller.

**Comment by chrisgoringe** [comment]
Ok, you must have been one update behind :).

**Comment by JorgeR81** [comment]
I tested again and it was working, but it was a bit slow to update. 

So I restarted ComfyUI, to see if it would improve. 
But after restarting, it did not work again. 

I have this log after refreshing the nodes, when it does not work. 

![log](https://github.com/user-attachments/assets/8e4f1547-ae74-4d6c-9e80-9e4dca681223)

**Comment by chrisgoringe** [comment]
If you still have the problem, could you next time scroll back up the log to see if there are any other messages mixed in with the 'replacing...' ones, and also to see what is immediately before they start?

**Comment by JorgeR81** [comment]
> could you next time scroll back up

Before clicking I cleared the console.
These are all the messages that show up when I refresh the nodes. 
( You can see that there is no scroll bar in the console, for these messages )

**Comment by chrisgoringe** [comment]
what browser? 

There *definitely* should be more messages off the top - one 'replacing node type' line gets generated for each node type when you refresh.. I don't have a lot of custom nodes and I get 450 'replacing' messages!

**Comment by chrisgoringe** [comment]
Just had an idea as to what might be going on. Could you update from dev and see how it behaves now?

**Comment by JorgeR81** [comment]
I updaded all.

I tried in Chrome and Edge, and still have this issue.

Here is the log in Chrome, when I refresh the nodes.
It's much larger now ( see the scroll bar ).

Here is top an botton scroll:

![top](https://github.com/user-attachments/assets/719b7b5e-bb58-4017-9a1d-3b9ae5db87a5)

( ... )

![log](https://github.com/user-attachments/assets/1faa57a9-e611-4e9d-b0d5-093ee06ae1c2)

**Comment by chrisgoringe** [comment]
Ok, I don't know why it's happening, but at least now I know what is happening! The update request is there right at the top, even though it's after an await command. So it's refreshing before the nodes get updated.

I can do a hack solution, I think, by adding another update with (say) a two second delay. But I'd really like to work out what's going on!

**Comment by JorgeR81** [comment]
Wait ! ... now it works. And its fast !

( I don't recall changing anything ?! )

Here is the log:

![lz1](https://github.com/user-attachments/assets/f42ca230-252c-4354-8b8a-e64338ecb9bd)

( ... )

![lz2](https://github.com/user-attachments/assets/ef3575b2-8d02-4d06-ba1c-f7c83e0b981b)

**Comment by JorgeR81** [comment]
I restarted ComfyUI and it's broken again !

I don't know what I did to make it work before ?!

**Comment by chrisgoringe** [comment]
Those on_change lines are what I get all the time, don't know why you sometimes don't get them. I think there must be some timing issue that determines whether or not it gets initialised properly.

That's at least a hint to follow...

**Comment by JorgeR81** [comment]
> I think there must be some timing issue

Yeah, yesterday, when it worked, it had about a 2 second delay, after clicking the button. 

This last time today, when it worked, it has no noticeable delay.

**Comment by chrisgoringe** [comment]
hopefully now it will refresh after a delay if it doesn't initially....

**Comment by JorgeR81** [comment]
Unfortunately, it is still not working.

Log:

![l0](https://github.com/user-attachments/assets/5dfbef47-bc23-4687-8e03-864c86e1ecdf)

( ... )

![l1](https://github.com/user-attachments/assets/23d8f889-d6d2-47a6-ab05-40864dafabf4)

**Comment by chrisgoringe** [comment]
Could you set a breakpoint for me? To do this, in the dev tools window, find the "Source" tab, find controller.js, go to line 121, and click just to the left of the '121' (where the left red dot is in the image - the dot should appear). Then press the refresh button in Comfy. 

What ought to happen is that the browser will pause with a message like "Paused in debugger", and that line will be highlighted in the dev tools window. You can then click the red dot again to make clear it, and press the 'play' button (or just reload the page)

![Screenshot 2024-11-08 105116](https://github.com/user-attachments/assets/c4b55521-93e9-46f6-a5a0-5fbab517ec05)

Then, as another test, I'd like you to go to the console and type `app.refreshComboInNodes` and screenshot what it says. Like this:

![Screenshot 2024-11-08 105718](https://github.com/user-attachments/assets/2b85afef-a9a3-47be-bfef-60dacf057e43)

(btw, what browser are you using?)

**Comment by JorgeR81** [comment]
I will be using Chrome, to test this.
I can also try Edge

**Comment by JorgeR81** [comment]
**Test 1 - on Chrome.**

I've found the line, click on it and a blue arrow shows up.
But when I refresh Comfy, nothing happens.
I've also ticked the 2 checkboxes in the breakpoints section, but still nothing happens.

![t1](https://github.com/user-attachments/assets/ac1a78f8-ec8c-437f-902e-e429ddd39080)

**Comment by chrisgoringe** [comment]
jsut confirming - when you 'refresh comfy', you mean clicking the refresh button, yes?
![Screenshot 2024-11-08 111436](https://github.com/user-attachments/assets/53fa84c0-1c02-44c2-87e7-80295a9cb4f6)

**Comment by JorgeR81** [comment]
> jsut confirming - when you 'refresh comfy', you mean clicking the refresh button, yes?

Yes. 

And I also tried test 1 on Wdge, and nothing happens. 

I will try test 2

**Comment by JorgeR81** [comment]
**test 2**

![paste](https://github.com/user-attachments/assets/d5456f4e-f11d-4e40-95b7-6b8621691cb9)

**Comment by chrisgoringe** [comment]
OK, getting close. I just need you to do a search... in Edge you do it like this: in the 'Sources' tab, right click on 'extensions' and select 'Search in Folder'
![Screenshot 2024-11-08 112259](https://github.com/user-attachments/assets/65f70e8f-f13f-4a39-9908-fff75b2523d7)

A search area will pop up at the bottom: type `file:extensions refreshComboInNodes` into it (file:extensions will probably already be there)
![image](https://github.com/user-attachments/assets/1834eb92-71c1-4076-be75-fb95806d74d9)

Screenshot the result (you might need to scroll to see everything)

**Comment by JorgeR81** [comment]
There it is:

( test 2 as the same result in Edge, by the way )

![edge1](https://github.com/user-attachments/assets/1bd147e4-8700-4f3c-a88a-14bda6f9053c)

**Comment by chrisgoringe** [comment]
Thanks. I'm fairly sure I now know what's happening. Do a git pull and see if it works for you

**Comment by JorgeR81** [comment]
It works !

**Comment by chrisgoringe** [comment]
OK, it was a clash with ComfyUI-Custom-Scripts. They've hijacked the refreshComboOnNodes, which we were also doing, but in a way that wasn't safe.

But in the process I've discovered that there is actually an 'official' way to do it, which we are now using.

**Comment by JorgeR81** [comment]
I just tried in the new Frontend and it also works.

---

I also just noticed that today they moved the refresh button to a drop down list !

https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.3.36

![fe1](https://github.com/user-attachments/assets/01fae53b-a125-4045-a854-ef02c864f314)

**Comment by chrisgoringe** [comment]
Yeah, I saw that. 

I've just offered a PR on ComfyUI-Custom-Scripts to make the same change as I did.
