### ISSUE TITLE
Don't show a Sampler preview, if we already have it in an Image Preview on that same Controller. 

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#273]

**Comment by JorgeR81** [comment]
I think it would be better to have an icon/button in each sampler to toggle live preview.
This would give more flexibility.

We could use the eye icon. It already has a crossed variation.

![02b](https://github.com/user-attachments/assets/0c041398-1c2f-42a2-bea4-e004f2a263de)

**Comment by JorgeR81** [comment]
Maybe this is not necessary after all. 

The Controller is very flexible, so we have good alternatives. 

----

I can get images from all Sampler "stages" in the "big preview area". 

![p001](https://github.com/user-attachments/assets/38f20b79-3839-402e-b677-6faef97bd60e)

----

And I can also add a `Preview Image` as "advanced control", in each Sampler group.


![p00](https://github.com/user-attachments/assets/fbc34da5-410c-4ba3-adf0-e9c54cc36f52)
