### ISSUE TITLE
Images forget their size 

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#275]
see discussion https://github.com/chrisgoringe/cg-controller/issues/263#issuecomment-2453474790

**Comment by chrisgoringe** [comment]
Ah, this is effectively a duplicate of #264

**Comment by JorgeR81** [comment]
For me this happened when I used a tiled upscaler.
I still have this after the latest update ( with `1.3` being moved `dev` ) 

The preview for the tilled upscaler was square, so it changed the height of the original `Image Preview` node ( optimized for a portrait aspect ratio ).

Do you have` UltimateSDUpscale` ?  ( https://github.com/ssitu/ComfyUI_UltimateSDUpscale )
Try this simple workflow and you can test it: [tiled test.json](https://github.com/user-attachments/files/17612647/tiled.test.json)

But, if it can't be fixed, there's no problem. It's a minor issue. 

---

The Image height adjusted for Portrait images

![z1](https://github.com/user-attachments/assets/6c4af746-fafb-4f02-9935-189ed32bc646)

---

When the tiled preview starts, the Image height changes. 

![z2](https://github.com/user-attachments/assets/dc4df359-2357-4b63-96d3-e43119a1ff66)

---

The `Image Preview` keeps that same height, and now it's smaller.

![z3](https://github.com/user-attachments/assets/8992b40c-d19a-4f32-a0cd-23e9cf025a1c)
