### ISSUE TITLE
[ Bug ] When we switch workflows, we get the Sampler Preview from the previous one.

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#278]
Refreshing the Controller does not fix this.
We need to refresh the browser.

![prev](https://github.com/user-attachments/assets/31963c52-8767-4f19-8173-f17e945bcdfe)

**Comment by chrisgoringe** [comment]
Memo to self: need to initialise the image manager when swapping workflows.

**Comment by LukeG89** [comment]
This is fixed!
