### ISSUE TITLE
bypassed Preview Image node got filled with the live preview ( JIFIF file ) when enabled, even before I generated any image with that stage.

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#280]

**Comment by chrisgoringe** [comment]
See https://github.com/chrisgoringe/cg-controller/issues/274#issuecomment-2453625672

**Comment by chrisgoringe** [comment]
(this is because it is receiving the interim images it would display if not bypassed, just not showing them)

**Comment by JorgeR81** [comment]
Yeah, having the behavior is not a big problem.  
If you don't have a good way to change it, better leave it as is.
