### ISSUE TITLE
[ Feature Request ] Don't include nodes without widgets or images 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#284]
When we select multiple nodes ( doing a "box selection" with the cursor ), we may include by accident, nodes that are are not needed in the Controller ( e.g. `VAE Decode` )

![vae](https://github.com/user-attachments/assets/25038b65-3299-40bd-801e-87568c4992b0)

**Comment by LukeG89** [comment]
This made preview nodes disappear (they only appear after the first generation)

**Comment by JorgeR81** [comment]
> This made preview nodes disappear (they only appear after the first generation)

Yeah, we need to see them, even when they don't a have picture, in case we want to change the position.

**Comment by chrisgoringe** [comment]
try now

**Comment by JorgeR81** [comment]
It's working.
