### ISSUE TITLE
[ Feature Request ] "Grey out" the toggle button in the top bar, if no Controller was added.

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#285]
If we haven't added a Controller, the toggle button can be blue, but we don't see anything.

![bt](https://github.com/user-attachments/assets/c330acde-50e8-4315-9cda-efe523072dac)

This can be confusing, as we can see in the ComfyUI repo discussion:

> I just get buttons in the panel that are clicked, but nothing happens, even in the main version

https://github.com/comfyanonymous/ComfyUI/discussions/5408#discussioncomment-11142444

----

> @rollingcookies I think you just need to create a New Controller with the right-click menu. You can create multiple windows.

https://github.com/comfyanonymous/ComfyUI/discussions/5408#discussioncomment-11142581

**Comment by chrisgoringe** [comment]
Greying the button would imply you can't use it... I think better would be to automatically add the first controller

**Comment by LukeG89** [comment]
> I think better would be to automatically add the first controller

I agree, but I would start with the button disabled, and only if you enable it, a window is created.
(to avoid a controller popping up everytime you create a new workflow)

**Comment by JorgeR81** [comment]
> > I think better would be to automatically add the first controller
> 
> I agree, but I would start with the button disabled, and only if you enable it, a window is created.

Yes, this would be a better solution.

**Comment by LukeG89** [comment]
Works good! And no more refresh button! 🎉
