### ISSUE TITLE
[ Feature Request ] Support batch in `Image Preview` node

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#289]
If we have a batch of images in an `Image Preview` node, it only displays the first one.

This would be very useful in workflows with IPAdaper / FaceID

If this is possible, try to add a small margin between the images. 

![batch](https://github.com/user-attachments/assets/01d7db4f-808a-4e19-bfff-1cd09048970c)

**Comment by chrisgoringe** [comment]
Yes. Right now we explicitly select just one image, so this should be on
the roadmap

**Comment by JorgeR81** [comment]
This is working, but the clicking area, on the left, is not disabled at `1/n`
So you can click it to get `0/n`


---

![r11](https://github.com/user-attachments/assets/16cadea7-206e-48f1-acce-80fb11bb323f)
![b2](https://github.com/user-attachments/assets/f1f8503c-ff25-47fe-aac0-cfac15f0d7b1)

---

**Comment by JorgeR81** [comment]
It's fixed.

**Comment by LukeG89** [comment]
Nice! 🚀

**Comment by LukeG89** [comment]
Maybe the last thing I would add is the ability to start over from the beginning when you reach the last image and vice versa.

**Comment by chrisgoringe** [comment]
yeah, thats nicer. Done.
