### ISSUE TITLE
button in top corner of nodes with images to keep them at maximum size (full width of controller)

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#290]

**Comment by chrisgoringe** [comment]
done on dev

![Screenshot 2024-11-05 134342](https://github.com/user-attachments/assets/d8c3ac0c-446f-49db-b0a9-c10e38a5ec49)

**Comment by JorgeR81** [comment]
This feature works, but now I can't colapse the images.

Even when it's disabled.

**Comment by JorgeR81** [comment]
Alo, can you try this icon an see how it looks.

The current one it's OK, but it seems that's for moving the image or something.

![wm](https://github.com/user-attachments/assets/287ea024-2b85-4fb1-80b8-7016371045bd)

**Comment by chrisgoringe** [comment]
Fixed the blocking of minimise on dev.

the pi-window-maximize is normally used to pop something out to fullscreen (which I'd quite like to add!). How about:

![Screenshot 2024-11-06 101243](https://github.com/user-attachments/assets/71723e25-4fc6-4c42-a0ed-2e391546eeb3)

Also, now we have the pin, there is no reason to have the maximum height constrained, so I'm removing it.

**Comment by JorgeR81** [comment]
Yeah, the pin icon is better. It looks good.

It has a more recognizable and simple shape, than the maximize icon.
