### ISSUE TITLE
[ bug ] The Controller is not refreshed when clicking the bypass button  

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#291]
The button works, but the Controller is not refreshed. 

![cup](https://github.com/user-attachments/assets/0773f3cf-0f53-4a2d-a3c8-9a36eb61003c)

**Comment by chrisgoringe** [comment]
On dev? It's working perfectly for me.

If you have Use Everywhere nodes installed, could you make sure they are updated as well? There might be a conflict.

**Comment by JorgeR81** [comment]
> If you have Use Everywhere nodes installed, could you make sure they are updated as well? There might be a conflict.

I saw the conflict warning. After updating it's gone. 

But I still have this issue.

**Comment by chrisgoringe** [comment]
Please do the following:

- turn controller debug level up to 'verbose'
- get the js console up
- click the bypass button on the node and note any *new* lines added to the console when you do so

**Comment by JorgeR81** [comment]
When I click the button, I see no logs in the console.
But the group is being bypassed. 

![log](https://github.com/user-attachments/assets/a1bacdce-8148-4fc5-bf2b-aba7825f394c)

**Comment by chrisgoringe** [comment]
OK, that helps. Could you now:

- update from the dev branch (I've just added some more debugs)
- double check that debug level is verbose
![Screenshot 2024-11-06 112435](https://github.com/user-attachments/assets/ecf3fc0f-677d-4aa8-933e-ac3c5658929c)

- reload the webpage and look for any lines in the console that start '***'
- click bypass and look for any lines in the console that start '***'

**Comment by JorgeR81** [comment]
This is after opening the workflow.

After clicking the button, there are no additional logs.

---

![log1](https://github.com/user-attachments/assets/0f342b06-6141-4284-ac26-92c148ea7ca5)

**Comment by chrisgoringe** [comment]
very very odd

update and try again!

**Comment by JorgeR81** [comment]
It works !

![log2](https://github.com/user-attachments/assets/d2b2aa65-2947-4115-a8b3-fb21c17d3ea2)

**Comment by chrisgoringe** [comment]
yay
