### ISSUE TITLE
Add a setting to determine default state of copy to other nodes checkbox. was:. In the default range selection popup for the slider, turn off the “Apply to similar nodes” checkbox

### ISSUE THREAD

**Issue by rollingcookies** [chrisgoringe/cg-controller#292]
Can I accidentally click and apply an unnecessary range to existing nodes?

![image](https://github.com/user-attachments/assets/cb332d38-a2b5-4d0e-8a9e-f186e65098f4)

**Comment by JorgeR81** [comment]
We could have an user setting to hide it, in all edit menus.

---

Or maybe, the menu could be a bit taller to have more separation between the options ?

**mockup:**

![mn](https://github.com/user-attachments/assets/eb5b6b3a-e385-4363-a4de-46f29e888f8e)

**Comment by rollingcookies** [comment]
> We could have an user setting to hide it, in all edit menus.
> 
> Or maybe, the menu could be a bit taller to have more separation between the options ?
> 
> **mockup:**


If it's easier to make a custom setting to disable such a checkbox (by default), I'm all for it ) My problem won't be solved, if only to make distances between elements bigger - it won't save from accidentally clicking [Save] when the checkbox is enabled.

**Comment by chrisgoringe** [comment]
Happy to add a setting to specify if the box is ticked or not by default, is that sufficient?

**Comment by rollingcookies** [comment]
> Happy to add a setting to specify if the box is ticked or not by default, is that sufficient?

Yes! 😄

**Comment by chrisgoringe** [comment]
@rollingcookies added on the dev branch

**Comment by rollingcookies** [comment]
@chrisgoringe Does not work, the Controller settings section is no longer displayed

**Comment by LukeG89** [comment]
@rollingcookies What do you mean?

![setting](https://github.com/user-attachments/assets/5420fd48-95b1-4da1-a277-8e46a0383994)

**Comment by LukeG89** [comment]
@rollingcookies You don't have Controller settings, but Controller is working? 😕

**Comment by rollingcookies** [comment]
> @rollingcookies You don't have Controller settings, but Controller is working? 😕

Yep

**Comment by chrisgoringe** [comment]
Please take a look at the JavaScript console (f12) immediately after loading the webpage

**Comment by rollingcookies** [comment]
![image](https://github.com/user-attachments/assets/a29f1e34-cfb8-4fc2-930c-2306905f9f8d)

**Comment by chrisgoringe** [comment]
Thanks. Looks like there's a clash with another custom node - I should be able to do a workaround

**Comment by chrisgoringe** [comment]
Please update and try again - again, if it fails, post screenshot from console immediately after loading the page

**Comment by rollingcookies** [comment]
Настройки Контроллера так и не появились!

![image](https://github.com/user-attachments/assets/6f3d82a3-43e6-4e26-8119-485a4f46d310)
![image](https://github.com/user-attachments/assets/4bd85beb-fd61-4e7c-826f-4cd1ed65ff0a)

**Comment by chrisgoringe** [comment]
You have updated? On the dev branch?

**Comment by chrisgoringe** [comment]
You see near the top of the first image, where it says CG-controller method setup and then has "object" "object" with little triangles? Could you click on those and see if they expand to give more information?

**Comment by rollingcookies** [comment]
Is that enough?

![image](https://github.com/user-attachments/assets/d1a0fd35-0987-4319-b02e-4d0a1519acb3)
![image](https://github.com/user-attachments/assets/d8779b4e-f476-4e00-9e33-c8bb6a3e78f3)
![image](https://github.com/user-attachments/assets/be4de8f0-8654-4989-b432-f5aaf3698515)

**Comment by JorgeR81** [comment]
@rollingcookies, you could also try to disable your extensions one by one, in the Manager, to find which one causes the conflict.

This could make it easier to fix the problem. 

You don't need to uninstall, just "disable" and restart ComfyUI.
Once you've found it, you can enable them all again at the same time.

![ds](https://github.com/user-attachments/assets/aec75b05-005b-4a2d-b632-610af1a8acf4)


These are my extensions, so they should be fine. You can try some of the other ones you have.
Maybe start with the ones that also have a settings tab, because they are probably more complex

![set](https://github.com/user-attachments/assets/47803693-5146-447e-a445-44cec8e109de)


```
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-controller
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Cutoff
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\aegisflow_utility_nodes
   0.1 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.1 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.3 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.3 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Detail-Daemon
   0.5 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI
   0.6 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.7 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
   0.9 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   2.4 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
```

**Comment by rollingcookies** [comment]
I refuse to do that, I have 100500 nodes 🙂

**Comment by chrisgoringe** [comment]
What has the number of nodes got to do with it?

**Comment by rollingcookies** [comment]
I have 106 nodes installed, for each one I will spend 2-3 minutes to check <= ~300 minutes

But you're right, it's not just about the number of nodes. During our already long correspondence I feel that my vision of how the product should look like and how it should work is very different from yours. That's why I constantly encounter a lot of objections, to which I have no motivation or strength to write or answer anything. So, guys, I'll probably stay out of the way.

**Comment by JorgeR81** [comment]
You don't have to participate if you don't want to.
But in case you need to check for extension conflicts, in the future:

You don't need to restart ComfyUI 106 times.
Each time, you can disable half the extensions, and see if the conflicting extension is still enabled. 

You just need to restart 5 or 6 times, with half the extensions, each time:

50
25
12
6
3
