### ISSUE TITLE
In one controller, but on different tabs “Ungrouped” and “Group name”, when I change the order of widgets in “Group Name” the order of widgets on the “Ungrouped” tab is changed randomly

### ISSUE THREAD

**Issue by rollingcookies** [chrisgoringe/cg-controller#293]
In one controller, but on different tabs “Ungrouped” and “Group name”, when I change the order of widgets in “Group Name” the order of widgets on the “Ungrouped” tab is changed randomly

**Comment by LukeG89** [comment]
I think what you are experiencing is that when you create a new window (Ungrouped or not), the order of the widgets is set to a default position and doesn't follow the order you choose in other windows.

Widgets keep the new position only in that specific window, but if you create other windows, the "default" position is used (in Ungrouped it can also change when you reorder nodes in graph)

Here's a test:


https://github.com/user-attachments/assets/6ee73ff3-c92d-4d2b-85bc-ecc6212628b7

**Comment by rollingcookies** [comment]
No, I wrote exactly about working with tabs in one window! But your variant of widgets' behavior in different windows also seems strange, because if you set the order for some group or ungrouped widgets in one window and then open a new window and open a previously created group or ungrouped widgets there, it would be convenient for the user to keep the previously set order.


https://github.com/user-attachments/assets/e908b56d-fcc5-44e7-b7d7-7dffd78c6db8

**Comment by JorgeR81** [comment]
I also have this.

But I also happens when I switch between 2 groups.

**Comment by chrisgoringe** [comment]
Thinking about what the best behaviour would be...

For a given group, before any controller has viewed it, there is a default order determined by the group.

When you view a group for the first time in a given controller the controller saves the order, and updates with any changes.

Suppose that order was also saved globally, to be the default for a new controller. That makes sense.

- It gets more complicated when you have a third, if the first and second have both been rearranged and are different... but that's probably rare enough that imitating an unspecified one of the others would be ok.

Then there are some other issues, like if you drag a node out of a group and then back in again... or drag it to a different group, rearrange the view there, then drag it back...

I'm thinking that maybe the best approach would be to have complete orderings of all the nodes in the workflow - one such ordering that is global, and one for each controller. When you create a controller it clones the global order; when you move a node it changes the order for itself and for the global. New nodes would be added at the end of the list. That way a new controller should pick up the most recent ordering.

This would give a consistent behaviour, I think.

**Comment by JorgeR81** [comment]
Do you mean disabling the ability of moving nodes in the Controller ?
And following the node's ID number ?

In principle, that is an "elegant" solution.

But in practice, it would make it extremely complicated to make small changes to the Controller's layout, as we expand the workflow.

I would have to delete and rebuild complete new sections of the workflow, to change this order, right ? 

And new users are probably not even aware this order exists. The Controller's order would not make sense to them !

---
![nodes](https://github.com/user-attachments/assets/92aa980b-6b54-449c-8016-ebe035bf4f73)

**Comment by chrisgoringe** [comment]
No, no.

The workflow order would be the starting point. When you create a controller it makes a copy of that order. You can then rearrange as much as you like, just like now.

The difference would be that when you rearrange, the changes would also be applied to a sort of "shadow order" associated with the workflow, not the controller. Changes made in any controller would be made in the shadow as well (but not the other way around - the controllers are independent).

If you then make a new controller, instead of starting with the workflow order, it starts with a copy of this shadow. That means that in general it will be sorted like the existing controllers - the order that you have chosen in one controller becomes the default for new ones. 

But again, you can change every controller just how you like. 

This whole thing is really about two things:

Getting a better default order

Having a way to handle nodes moving in and out of groups consistently.

**Comment by JorgeR81** [comment]
> If you then make a new controller, instead of starting with the workflow order, it starts with a copy of this shadow.

So, If I change the order of group in a  Controller, that group would have the same order, in other Controllers.

This would be great !

**Comment by LukeG89** [comment]
@rollingcookies Guidelines come from [ComfyUI Custom Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts)

![guides](https://github.com/user-attachments/assets/1edbf4b2-5dd0-4690-9165-445c2b5c7e65)

**Comment by chrisgoringe** [comment]
> > If you then make a new controller, instead of starting with the workflow order, it starts with a copy of this shadow.
> 
> 
> 
> So, if I change the order of group in a  Controller, that group would have the same order, in other Controllers.

In any future new controller, yes.

**Comment by chrisgoringe** [comment]
See how the latest version on dev (just pushed) works for node ordering.

**Comment by JorgeR81** [comment]
OK, it seems to be working. 

The order is kept, when we switch groups, inside the Controller.
And if we add a new Controller, it gets that same order for that group.

**Comment by rollingcookies** [comment]
Thanks, guys! It's working for me too!
