### ISSUE TITLE
In ComfyUI locked mode (Comfy.Canvas.ToggleLock), disable the ability to move controller windows, as well as their closing, minimizing, deleting ([Trash], [X], [_])

### ISSUE THREAD

**Issue by rollingcookies** [chrisgoringe/cg-controller#297]
In lock mode, hide the [Trash], [X], and [_] controls, as well as the ability to change the position of controller windows

**Comment by LukeG89** [comment]
Seems to work really well!

**Comment by rollingcookies** [comment]
The controls are still displayed, even though they are not active for pressing

![image](https://github.com/user-attachments/assets/34b4dbf5-b7e6-449b-970e-20c0ee570204)

**Comment by chrisgoringe** [comment]
Yes. Like in comfy, no visual change

**Comment by rollingcookies** [comment]
Well, in general, in Comfy the mouse cursor changes. But in our situation we need to make inactive elements semi-transparent or hide them.

**Comment by LukeG89** [comment]
@chrisgoringe There is a little issue: the icon in graph canvas is not changing when in Pan mode, it keeps the "arrow" icon instead of the "hand" icon. Disabling Controller solves the problem

![icon](https://github.com/user-attachments/assets/b7e41396-dd02-4796-9edc-bf6a0af24353)
