### ISSUE TITLE
[Feature Request] Zoom in/out images using Shift (or Ctrl) + Scrollwheel (if possible)

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#301]
After the implemetantion of https://github.com/chrisgoringe/cg-controller/issues/290 , you can now overcome the window limitation and zoom the images as much as you want.
However, it is pretty tedious to use the handle for that purpose.

Would be more convenient if we can zoom in/out images using Shift/Ctrl + Scrollwheel.

That would improve image browsing, combined with these two:
- https://github.com/chrisgoringe/cg-controller/issues/298
- https://github.com/chrisgoringe/cg-controller/issues/289

**Comment by JorgeR81** [comment]
I think we should keep the resize handle, in case people want to use it. 
It's better if you want to make the images smaller.

And have an option like `Scrollwheel zooms images` ( with the same options as `Scrollwheel changes sliders` ).

Potentially, we could even use the basic `scrollwheel` action for everything, depending on the mouseover area.
Or we could have 3 separate shortcuts, for sliders, scrollbar, and images.  
I think all options could work. Just give the user the choice. 

![sel](https://github.com/user-attachments/assets/d042f4af-e701-47af-9f7c-99aecd409e41)

**Comment by LukeG89** [comment]
> I think we should keep the resize handle, in case people want to use it.
> It's better if you want to make the images smaller.

Yes, the handle can stay, this is just to make zooming easier.

> And have an option like Scrollwheel zooms images ( with the same options as Scrollwheel changes sliders ).

> Or we could have 3 separate shortcuts, for sliders, scrollbar, and images.  

That would be confusing, because you should need to remember what key triggers what.

> we could even use the basic scrollwheel action for everything, depending on the mouseover area.

Yes, definitely.

**Comment by JorgeR81** [comment]
> > Or we could have 3 separate shortcuts, for sliders, scrollbar, and images.
> 
> That would be confusing, because you should need to remember what key triggers what.

Yeah, I think it could work just with the basic `Scrollwheel` action for everything. 
We could still mouseover the column header to scroll the column, like we do now.  

But if we decide to keep the shortcut options, we should give all the choices. 
The user would only have 3 separate shortcuts if he wants to step it up this way. 
It would be even more confusing to try to prevent some shortcut combinations.
