### ISSUE TITLE
[ Feature ] have an indication that a group is bypassed, when not selected.

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#302]
If we have multiple groups in a Controller we can't know which ones are bypassed, without selecting them. 
Especially if we are using the whole canvas for controllers.

I think we should also use the bypass color as an indication. 

If we use it in the button's borders, I'm not sure that's going to be noticeable enough.
And I it may be just confusing, with too many colors.
 
I think we should change the color of the whole button.
When a group is bypassed, it's mostly the bypass color we notice in the graph, anyways. 

![bp1](https://github.com/user-attachments/assets/3bc4acef-44c6-4336-a490-dbef850e2c74)

**Comment by JorgeR81** [comment]
> You can not beget colors, but make an icon - the same as now in the graph with nodes, in the form of an eye or an arrow with a dot!

Do you mean this:

![ico](https://github.com/user-attachments/assets/055f03b4-4d02-48d2-9d45-6c8a8ca84637)

---

This is an rgthree feature.
This icon is not part of the set used in ComfyUI.

We are trying to use only icons from this set: https://www.primefaces.org/diamond/icons.xhtml

That's why we've chosen this icon to bypass:

![ban](https://github.com/user-attachments/assets/528b9311-f04b-4290-a33f-2d432ad6eb7e)

**Comment by chrisgoringe** [comment]
Closing this - roll it into #303

**Comment by rollingcookies** [comment]
> > You can not beget colors, but make an icon - the same as now in the graph with nodes, in the form of an eye or an arrow with a dot!
> 
> Do you mean this:
> 
> ![ico](https://private-user-images.githubusercontent.com/72734038/383738460-055f03b4-4d02-48d2-9d45-6c8a8ca84637.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjE2NDIsIm5iZiI6MTczMDk2MTM0MiwicGF0aCI6Ii83MjczNDAzOC8zODM3Mzg0NjAtMDU1ZjAzYjQtNGQwMi00OGQyLTlkNDUtNmM4YThjYTg0NjM3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA2MzU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNDc1MzEyNzU3OThkYjI5ZGY0YzJhOTIzZjI5MzI4ZWYxZWU4ZjFlZmY5NTg3OWE1MDcxODYwN2U2YWRmMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LF282nOPubkC-ImHpvQjgqVYjFKvrzufp715CcyOKlM)
> 
> This is an rgthree feature. This icon is not part of the set used in ComfyUI.
> 
> We are trying to use only icons from this set: https://www.primefaces.org/diamond/icons.xhtml
> 
> That's why we've chosen this icon to bypass:
> 
> ![ban](https://private-user-images.githubusercontent.com/72734038/383739107-528b9311-f04b-4290-a33f-2d432ad6eb7e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjE2NDIsIm5iZiI6MTczMDk2MTM0MiwicGF0aCI6Ii83MjczNDAzOC8zODM3MzkxMDctNTI4YjkzMTEtZjA0Yi00MjkwLWEzM2YtMmQ0MzJhZDZlYjdlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA2MzU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZTE5YzYyOWZmZWM1M2VlM2QyYzkxZWIzNjBhM2RjZjMyNTdjODUyOTA0ZDYzOGI0ZDUwNmM5Mjg2MzljYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rT-i1ADNWAMSSOIDGgckkcYNeyTyvGjuyxwkSeCUxco)
> 
> We could put an icon in front of the group's name, but that would take space and be visually confusing if we have multiple bypassed groups.
> 
> I would leave this "view" as is, and have an user option for a view with multiple rows: [#303 (comment)](https://github.com/chrisgoringe/cg-controller/issues/303#issuecomment-2460842784)

It's not clear why you only use Bypass mode for groups and don't use Muted mode? This is fundamentally wrong, both modes are important for groups and, I think, are used equally in operation depending on the needs!

Considering that ComfyUI doesn't have icons for these modes, it is correct to stick to the historically existing situation, not to mislead the user by inventing new icons - it is more correct to use the icons that Rgthree invented! Besides, they are quite informative, though not very aesthetic.

**Comment by chrisgoringe** [comment]
Because bypass is part of ComfyUI, and mute comes from an extension.

**Comment by JorgeR81** [comment]
> I use this all the time in large workflows with multiple work options, as there is an automatic switch where if something is not passed to one input, it is on the other input (Any switch from Rgthree). And without muting this option will not work. I think this is a must have for large workflows.

Yeah, the `Any switch` from Rgthree, would be a good use case for "mute".

I think we could have it. Now we have much more space for buttons :)

But if we have both "mute" and "bypass", I think the current bypass icon would look better for "mute".

Here are some icon suggestions, for bypass : https://github.com/chrisgoringe/cg-controller/issues/303#issuecomment-2462012185

**Comment by chrisgoringe** [comment]
As I commented elsewhere - AFAIK, mute is not core Comfy functionality, but is added by other custom nodes. So the right approach is to allow those nodes to operate within the controller, NOT to imitate their functionality.
