### ISSUE TITLE
Toggle node bypass

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#305]
Could use the same icon and colors as for the group

**Comment by JorgeR81** [comment]
You mean having the bypass icon the node's header. Like the the pin header.

![bb](https://github.com/user-attachments/assets/8b3050ac-0955-4630-9f13-f58d7b59b5c9)

----

That would be great !

But it may not be needed in all nodes. For instance, nodes without inputs ( e.g. Loader nodes, or image nodes ).

**Comment by JorgeR81** [comment]
It works nicely !
- I like the icons on the left.
- I like the `?` icon

Just a tiny aesthetic adjustment.
The bypass and black colors on top of the nodes, could be a little stronger.

But, just slightly, I like this faded look.
It doesn't need to be as strong as on the node's graph. 

![ico](https://github.com/user-attachments/assets/0fe6bf16-b3bb-419c-aacb-b61b64ad2f00)

**Comment by LukeG89** [comment]
Yeah, because now bypassed and muted groups/nodes look very similar

However, don't you feel like the button on nodes is quite hidden between "collapse" and the title?
Why not placing it on the other side?

**Comment by JorgeR81** [comment]
> However, don't you feel like the button on nodes is quite hidden between "collapse" and the title?
> Why not placing it on the other side?

I like that it's closer to the name.
But a disadvantage is that these buttons are very small and they very close to each other.

@chrisgoringe, can you try placing it on the other side, to see how it feels ?

**Comment by JorgeR81** [comment]
Maybe make it an option ?

**Comment by JorgeR81** [comment]
**Crazy Idea :**

- Remove the square 
- Keep the buttons on the right 
- You can click the rest of the header to collapse 
- If you drag, after click down, collapse is canceled

**Comment by chrisgoringe** [comment]
I originally thought to do collapse by double-clicking the header. We went to the square to imitate Comfy nodes...

Single click to collapse (unless you drag) is certainly an option. It's actually how the tabs work - if you click a tab and drag, you move the controller, click without dragging selects the tab.

(many, many years ago, back in MacOS 8 I think, there was an extension called WindowShade that did that - double click any window top bar and it shrunk down to just the top bar...)

**Comment by chrisgoringe** [comment]
This is how it looks on the right.

![Screenshot 2024-11-08 123341](https://github.com/user-attachments/assets/73c71fab-c008-49e3-aa42-0512042a71f3)

**Comment by JorgeR81** [comment]
> This is how it looks on the right.

Yeah, this is how I wanted this to be. 
But after seeing it I don't think it works very well.

The buttons are too disconnected from the title. 
The rgthree buttons worked on the groups, because groups are far apart from each other. 
The Controller is much more compact, so the buttons need to be closer to the nodes name.

**Comment by JorgeR81** [comment]
I think we should remove the square.
If  `single click` to collapse does not feel good, we could try `double click`.

This case, I think imitating ComfyUI is holding back our GUI.
We should recreate the overall ComfyUI style, not make a blind copy.

**Comment by JorgeR81** [comment]
This would also take care of this issue:

- https://github.com/chrisgoringe/cg-controller/issues/281

We would only need a custom pointer, for the bypass/mute button.

The drag/colapse area in the header will be is quite large, so we could use the regular pointer.

**Comment by chrisgoringe** [comment]
Single click actually feels quite good to me. See what you think.

**Comment by JorgeR81** [comment]
I think it's better in every way.
It's looks better, it feels less cluttered, and it's faster to navigate the GUI. 
The new buttons really look like they belong in there.

The bypassed and muted panels are also more visible, and the red mute icon has more contrast. 

![z1](https://github.com/user-attachments/assets/04c1492b-cbed-4737-b9a0-c95043f6e9c7)

**Comment by JorgeR81** [comment]
By the way, bypass/mute a single node is slightly slower to update, than bypass/mute on the whole group. 

Is that expected ?

**Comment by JorgeR81** [comment]
The only change I would do is moving the text slightly to the right, to give a bit more separation.

Just 1 pixel.

---

**original:**

![t1](https://github.com/user-attachments/assets/4bef86ae-7df5-4d73-bf3f-df87421a5ffa)

---

**mockup:**

![t2](https://github.com/user-attachments/assets/3773119d-d6b7-4a02-812e-9ed4f20a4ffc)

**Comment by chrisgoringe** [comment]
moved 1 more pixel, and closing this!
