### ISSUE TITLE
Controller in focus mode

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#308]
Currently focus mode does not show the controller; it could be made a user option

**Comment by LukeG89** [comment]
Works good!

**Comment by LukeG89** [comment]
I just found a couple of problems

- Windows are not resized when you enter and exit focus mode (the handle is hidden)
- There is no limitation when resizing, and you can stuck the windows at the bottom


https://github.com/user-attachments/assets/7fa81771-8d9e-48bc-8cbc-6e073934aca2

**Comment by LukeG89** [comment]
@chrisgoringe Sorry, I spoke too soon! 😆

**Comment by LukeG89** [comment]
> - There is no limitation when resizing, and you can stuck the windows at the bottom

I just noticed you need to go fullscreen to reach the bottom of the window
