### ISSUE TITLE
[Bug] Manual editing widgets has some problems

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#311]
I encouter some problems when manually editing widgets:

- Numbers are not auto-selected
- Field stays black after editing
- Controller doesn't hide (you need to refresh the page)

https://github.com/user-attachments/assets/87986240-8760-42ae-9ec9-f0a2f50d5c2d

**Comment by chrisgoringe** [comment]
try now

**Comment by JorgeR81** [comment]
I just updated and it seems to be working fine.

**Comment by LukeG89** [comment]
Works perfectly!
