### ISSUE TITLE
[ feature ] display groups alphabetically in the drop down list

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#316]
This would be especially useful if we may have many groups, and use only 1 group per controller.

In this case, I want all the "Preview" groups to be together. 
But "Preview4" as added later, and now it's on the bottom

![sort](https://github.com/user-attachments/assets/f748eff4-62ba-4689-af9a-e98f68ec087b)

**Comment by chrisgoringe** [comment]
Done on dev. Alphabetical except that 'All' will always be first.

**Comment by LukeG89** [comment]
Nice!
