### ISSUE TITLE
Improving performance when we bypass individual nodes

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#324]
When we click the header button to `bypass/mute` individual nodes, it takes about a 1 or 2 seconds to update. 

But when we toggle whole groups it is much faster. 

Is it possible to improve the individual toggle speed ?

Having the lag, may confuse new users. 
So they will click twice, and nothing will happen ( because they will just revert the "first click", before the update happens ).

![by](https://github.com/user-attachments/assets/3283ec05-1d11-492d-82e5-7eef40ada502)

**Comment by chrisgoringe** [comment]
I don't experience this... could you see what comes up in the JavaScript console when you click the node bypass?

**Comment by JorgeR81** [comment]
Each time I click I have this:

![b1](https://github.com/user-attachments/assets/43b9bd65-9597-4af9-9507-fcad8bf1d615)

**Comment by JorgeR81** [comment]
I just tried on Edge and it seems to work fine. Almost no delay.

I only have a noticeable delay in Chrome.

---

But now I've tried in Chrome again and it's also fast ! 
It's not instantaneous, but it's much better.

Is this just a coincidence?
Or did Edge fix Chrome somehow ?

I never tried on Edge before. 
And I always had the delay in Chrome, ever since this feature was implemented.

**Comment by JorgeR81** [comment]
After using Chrome for a little while now, it seems the delay is getting noticeable again.

When I had the other performance issues ( https://github.com/chrisgoringe/cg-controller/issues/315 ), they also seemed to get worse with time.

**Comment by chrisgoringe** [comment]
Those messages are good.

It sounds like a resource leak. I'll investigate
