### ISSUE TITLE
Doesn't refresh when switching in and out of read_only

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#326]

**Comment by chrisgoringe** [comment]
refreshes on the next on_change, so not really a problem

**Comment by LukeG89** [comment]
I just found a strange bug with unpinned preview images when switching to Pan Mode:


https://github.com/user-attachments/assets/e99ebb94-ac88-45fe-8c39-50fd4013f367

**Comment by chrisgoringe** [comment]
Could you raise this as a new issue, thx
