### ISSUE TITLE
[Bug] Pan Mode expands unpinned preview images

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#328]
When entering Pan Mode, all unpinned preview images are expanded.

https://github.com/user-attachments/assets/e99ebb94-ac88-45fe-8c39-50fd4013f367

**Comment by LukeG89** [comment]
Sometimes after the expansion, this also happens:



https://github.com/user-attachments/assets/7864d75a-50c9-4a1e-a9ed-498046d345b8

**Comment by chrisgoringe** [comment]
#398 may be related

**Comment by chrisgoringe** [comment]
Fixed on dev I think

**Comment by chrisgoringe** [comment]
@LukeG89 close this if it's working for you!

**Comment by LukeG89** [comment]
Seems fixed! 🎉
