### ISSUE TITLE
Snap to bottom and right

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#334]

**Comment by chrisgoringe** [comment]
So I'm wondering if the right behaviour is not to snap to the bottom or right, unless you are also snapped to the opposite edge? So full height (or width) controllers resize with the window, but smaller (or bigger) don't.

**Comment by JorgeR81** [comment]
> So I'm wondering if the right behaviour is not to snap to the bottom or right, unless you are also snapped to the opposite edge? So full height (or width) controllers resize with the window, but smaller (or bigger) don't.

Yeah, I agree. 

Try this as the basic behaviour. And we will see how it feels.

**Comment by JorgeR81** [comment]
This seems to be working.

Snapping to top and bottom works with a single Controller, as intended.
It still works when we go fullscreen, but not when we hide the menus.

But we may also want to create a Snapped column with 2 controllers. This would also be nice to have.

![s1](https://github.com/user-attachments/assets/980cd3aa-0bf4-4775-8c22-1dc9ebf03a72)

**Comment by JorgeR81** [comment]
Snapping to the right is also partially working ( with a single full width controller ).
I can see that because the border it's adjusted automatically.
But opening the Sidebar still pushes the Controller out of the screen.

![sr](https://github.com/user-attachments/assets/0f53b2d3-df46-4419-8182-dfa3fafe0c28)

---

I'd also like to have snapping to the right, with multiple vertical columns.
This way all columns would be kept on the screen, when I change the widths.

**Comment by JorgeR81** [comment]
> But which window should be resized when you enter or exit fullscreen/focus mode? The bottom one? All of them

Maybe all of them, proportionally.

---

> > But opening the Sidebar still pushes the Controller out of the screen.
> 
> How should the behavior be like when opening sidebar windows?

I think, opening for resizing the Sidebar should result in the **`same behavior`**, as resizing a Controller ( placed the left side ).  

- If the Controllers are snapped to the right, all Controllers would be scaled proportionally. 
- If not, they could be pushed out of the screen. 

And snapping to the `right/bottom` should only happen, when we interact directly with the Controller that snaps:

- So we can move or resize the Controller placed on the right, to snap it to the canvas right edge.
- But, opening the Sidebar ( or resizing a Controller placed on the left ), should only lead to resizing all Controllers, if they are already snapped to the right edge.

**Comment by LukeG89** [comment]
> Maybe all of them, proportionally.

> I think it would be more intuitive if Controllers always resize, if they are snapped to the right.

Yeah, makes sense. It would be like resizing the entire browser window, Controller windows should proportionally adapt both vertically and horizontally.

**Comment by chrisgoringe** [comment]
So once we start snapping a stack (eg two controllers connected vertically) to the bottom, there suddenly emerge all sorts of other questions.

How do they share the resize?

What happens if there is another controller connected to the side (but not snapping to the top or bottom). Does it move? resize? What if it is connected to a stack on one side, and a full height controller on the other?

This really isn't core business for the controller, and I could spend a long time fiddling with it and we would keep finding cases that should behave differently, not to mention introducing and having to find bugs.

I would need a lot of convincing...

**Comment by chrisgoringe** [comment]
So... I'm going to close this. Feel free to start a topic in the discussions (like we have for aesthetics) if you want to try to work out exactly how it would work in an ideal case...

**Comment by JorgeR81** [comment]
Yeah, once we test this and create more configurations, we could see if it needs some improvements. 

I haven't yet settled on an ideal configuration.
