### ISSUE TITLE
[ Aesthetics ] Small header adjustments ( v1.4 )

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#340]
In relation to the way headers look in`1.4`, I would only do this:

- add 1 pixel below the text 

This will center the text in the header, improving readability.

---

**mockup:**

![p1b](https://github.com/user-attachments/assets/d021fe29-d062-4c19-a998-43dcab53b6d3)

---

**original:**

![p1](https://github.com/user-attachments/assets/33b14a59-bec5-4fd5-aa5c-01a46d18300f)

**Comment by chrisgoringe** [comment]
Up one pixel...

![Screenshot 2024-11-15 193742](https://github.com/user-attachments/assets/d59a71df-ae5f-43b5-b20b-2435b58ae7b9)

**Comment by JorgeR81** [comment]
I also meant increasing header height, by 1 pixel.
Now we are 1 pixel short above the text

![pix](https://github.com/user-attachments/assets/681f3290-917c-49bb-bf64-189844b85cfa)

**Comment by JorgeR81** [comment]
Yeah, since we increased height from 18 to 21 pixels, now the text is a bit off center.

It's better to have 22 pixel height. 

Then it will be pixel perfect :)

**Comment by chrisgoringe** [comment]
done

**Comment by JorgeR81** [comment]
Yeah, it looks good.
