### ISSUE TITLE
[ Aesthetics ] Match border thickness

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#341]
Some slight adjustments:

- Increase the node's ( bottom and side ) border from 3 to 4 for pixels.
This way, it will match the distance between the sliders.

- Increase the ( horizontal ) distance from the node to the controllet's gutter, from 4 to 5 pixels.
This way, it will match the ( vertical ) distance between nodes.

---

![m3](https://github.com/user-attachments/assets/a3264b63-ce8e-48e2-9612-64b29f24b28c)

---

**mockup:**

![gg2x](https://github.com/user-attachments/assets/284f8628-3984-4e8d-8c0f-1df1b72e3533)

---

**original:**

![gg1](https://github.com/user-attachments/assets/bf2e5b84-8067-4cca-83ed-a70a4cc745c3)

**Comment by JorgeR81** [comment]
The thicker border will also make the Prompt nodes stand out more, if we give them another color.

---

**mockup:**

![p02](https://github.com/user-attachments/assets/e5b5f3f5-3600-4f8b-a105-97f8ee0c0582)

---

**original:**

![p01](https://github.com/user-attachments/assets/14a9db3d-0d66-4330-90f4-71f9784978b9)

**Comment by chrisgoringe** [comment]
done, I think, on dev

**Comment by JorgeR81** [comment]
Looks good !
