### ISSUE TITLE
[ bug ] The scrollbar is activated, when there is still free space.

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#344]
The scrollbar is activated, when we still have free space in the Controller.

![sb1](https://github.com/user-attachments/assets/0a5b0167-933e-407c-82ba-0c671da7ecc4)

---

We need to increase the Controller's height ( more than what it should be necessary ) in order to disable the scroll bar.

![sb2](https://github.com/user-attachments/assets/26597129-e91f-4b4b-b3b4-adcfa60671b1)

**Comment by LukeG89** [comment]
That's because there is space at the bottom that makes windows still scrollable.

https://github.com/user-attachments/assets/800dc05c-b8fe-4091-abb6-40577757616c

**Comment by JorgeR81** [comment]
> That's because there is space at the bottom that makes windows still scrollable.

This space could probably be reduced, to be just a few pixels.

**Comment by chrisgoringe** [comment]
There is a trade off here. That space is required to prevent a feedback loop when resizing an internal element in a scrollable space (a notoriously tricky ui issue).

It can probably be shrunk a little safely.

**Comment by JorgeR81** [comment]
Yeah, it looks better now. 

And I didn't notice any issues.
