### ISSUE TITLE
[ Rollback ] Show all nodes in the Controller

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#346]
Now that we have bypass buttons, we need to show all nodes ( even the ones without widgets ). 

Some nodes are useful to have in the Controller, just to bypass.
For simplicity, it's probably better to just show all nodes, instead of going case by case. 

---
**Example:**

If I bypass a `Bach Images` node , I can exclude its image from a bach.
But if I bypass the `Load Image` node, I get an error.

![bb0x](https://github.com/user-attachments/assets/ae2603a0-b979-4de2-939b-4a8524341282)

![bb2x](https://github.com/user-attachments/assets/04278eea-a99f-4f77-9fe3-dba933c3a585)

![bb4x](https://github.com/user-attachments/assets/dee3e1bc-a06c-4bea-8289-a86552eb72c4)

**Comment by chrisgoringe** [comment]
Yes, I was just coming to the same conclusion.

**Comment by chrisgoringe** [comment]
Done. By default they are minimised, since that looks better when there are no widgets.

**Comment by JorgeR81** [comment]
It's working.
