### ISSUE TITLE
[Bug] Updating doesn't work with subgroups

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#349]
I tested how Controller updates when there are subgroups.

Controller doesn't update when: 
- Moving in or out a subgroup from a group
  - Even refreshing node def doesn't update it (it will update when you make a change) 

https://github.com/user-attachments/assets/c5f9fcf4-bdb7-4117-a8e0-108c0d2ff4d5

- Moving a node from a group to its subgroups
  - You need to move the node from canvas or an external group to access a subgroup

https://github.com/user-attachments/assets/f4bb8c23-d9cf-4965-ae84-97296021014e

**Comment by LukeG89** [comment]
> I haven’t even looked at how subgroups work 😀

It's the first time I've looked at it too! 😆
I encountered some update problems while testing this [#347](https://github.com/chrisgoringe/cg-controller/issues/%E2%80%9Chttps://github.com/chrisgoringe/cg-controller/issues/347%E2%80%9D), so I further investigated 🔍

**Comment by JorgeR81** [comment]
Yeah, "group nesting" is also causing this issue: https://github.com/chrisgoringe/cg-controller/issues/347#issuecomment-2480505295

**Comment by LukeG89** [comment]
Now it's perfectly working! I think after fixing this issue:
- https://github.com/chrisgoringe/cg-controller/issues/356


https://github.com/user-attachments/assets/9cbf40f4-e15b-4f16-861d-c123ecdae06c

**Comment by chrisgoringe** [comment]
Yes, I did those two together.
