### ISSUE TITLE
[ feature ] Display free node inputs

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#350]
We could have an user option to display free inputs in the Controller, in each node's header.

Some free inputs may result in an error.

This will allow to check for free inputs in the Controller. 

It could be even easier than to do it in the graph !

----

![diplay free inputs](https://github.com/user-attachments/assets/68c47e0b-ee24-44ce-b9ff-76bf0585125f)

**Comment by LukeG89** [comment]
How about optional inputs?

![opt](https://github.com/user-attachments/assets/d45ff596-8265-451e-89a1-e75df3a11c23)

**Comment by JorgeR81** [comment]
> How about optional inputs?

These inputs could also be displayed with a hole inside the dot, to differentiate from the other ones.

**Comment by chrisgoringe** [comment]
This seems fairly non-core?

**Comment by JorgeR81** [comment]
> This seems fairly non-core?

The optional inputs ( with a hole inside the dot ) are ComfyUI core.

Try adding a new `Apply ControNet` node ( the old one still exist, but it's deprecated ),

It has an optional VAE input ( required for SD3 and Flux ).


![cn](https://github.com/user-attachments/assets/259ef736-3a8a-4d54-994a-4fbfd48e1409)

**Comment by chrisgoringe** [comment]
sorry, I meant not really core to the Controller....

**Comment by JorgeR81** [comment]
Yes, I agree this is a non essential feature.

But I think it's still related to the Controller, because it also gives information about the node status. 

Not only about widget values or bypass/mute state, but also about the connection status.
This is really the only type of information we still miss in the Controller.

If it's not very complex to add, it may be worth having it.

**Comment by JorgeR81** [comment]
I'm not sure you can see the mockup image via phone / e-mail.

I think it looks clean. It does not clutter the GUI.

**Comment by LukeG89** [comment]
> I think it looks clean. It does not clutter the GUI.

That's depends. How would look a node with a long name + many non-connected inputs?

**Comment by JorgeR81** [comment]
> That's depends. How would look a node with a long name + many non-connected inputs?

Yes well, I guess the name would be partially covered. 

But this feature does not need to be always "on".

It may work better like the node "node highlight" feature.
Like an "utility" that we just want to turn on sometimes, to check the graph status, once it's built. 

It could also have a GUI button.

If enabled in the user settings, we would have a new Topbar button.

Maybe this one ?

![bt](https://github.com/user-attachments/assets/66feb8c3-3d40-4ceb-bb29-459f8c889258)

**Comment by chrisgoringe** [comment]
One complication would be working with use everywhere nodes or similar, that connect inputs that aren't really connected.

If only we had access to the developer of those nodes...

**Comment by LukeG89** [comment]
> It could also have a GUI button.

> If enabled in the user settings, we would have a new Topbar button.

No please! Not another button on topbar!! 😭

**Comment by LukeG89** [comment]
An alternative could be using a dropdown list like it was the save button in 1.2 frontend.
This way you can add all the buttons you want

![dropdown](https://github.com/user-attachments/assets/e6ad2ce9-e864-4fc7-aa75-0c5f1501f40c)

**Comment by JorgeR81** [comment]
> Yeah, but you need to consider smaller monitors and buttons from other extensions.

My monitor it's only 1920 x 1080, so it's also not on the larger side.

The Topbar is designed to work with multiple rows, exactly for these reasons.

Removing 4 or 5 icon buttons will only give you an extra workflow tab.

----

> An alternative could be using a dropdown list like it was the save button in 1.2 frontend.

If this is possible, I don't mind having that.

**Comment by LukeG89** [comment]
> > An alternative could be using a dropdown list like it was the save button in 1.2 frontend.
> 
> If this is possible, I don't mind having that.

In case this “disconnected input” feature is added as a new button, I would consider implementing the dropdown list.

**Comment by JorgeR81** [comment]
Also for the sake of simplicity, I think this one can be closed too, because:

- ComfyUI already indicates the nodes with missing inputs, when there is an error.
- The nodes that are not in the Controller could not be checked anyways.
