### ISSUE TITLE
[Bug] Canvas freezes after "download missing model" dialog

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#353]
Just found a strange bug.

Step tu reproduce:

- Enable `BETA Show missing models warning` option in Settings
- Open a template
- A missing model dialog appears
- Close it
- Canvas is frozen

You need to refresh the page to unfreeze it.

Everything is working if Controller is disabled.

https://github.com/user-attachments/assets/f708810d-6d1d-4bb0-85f8-88dcf01017a5

**Comment by JorgeR81** [comment]
Yeah, it can reproduce this.

For me the bug only happens if the Controller was toggled "off", in the previous workflow.

If it is toggled "on", it will be toggled "off", but the canvas will not freeze.

**Comment by chrisgoringe** [comment]
I think this is fixed on dev

**Comment by JorgeR81** [comment]
It's fixed for me.

**Comment by LukeG89** [comment]
Yes, it's fixed!
