### ISSUE TITLE
[Bug] Micro movements | [Feature] Pinning windows

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#355]
Especially when switching tabs, there are micro movements that make the windows unstable.

https://github.com/user-attachments/assets/4269aa1d-634b-4884-a2d2-a931a0bac605

Currently the way to avoid this is to be careful when switching tabs or to lock the canvas.

____

Possible solution: How about a pinning feature to fix windows position? (and maybe sizing?)

This way you can block all Controller windows after you arrange them.

**Comment by JorgeR81** [comment]
> Possible solution: How about a pinning feature to fix windows position? (and maybe sizing?)

If we can have dropdown buttons in the Topbar ( https://github.com/chrisgoringe/cg-controller/issues/350#issuecomment-2480559208 ), we could have one for that.

We already used the "pin" icon, so maybe this one:

![lock](https://github.com/user-attachments/assets/6e35670b-93ba-4a15-b02c-b91fcfcc3150)

**Comment by chrisgoringe** [comment]
I’ve got an suggested feature of snap to grid, which might help?

**Comment by chrisgoringe** [comment]
Or we could make it so that a window doesn’t move at all until a threshold
is met.

**Comment by LukeG89** [comment]
> I’ve got an suggested feature of snap to grid, which might help?

> Or we could make it so that a window doesn’t move at all until a threshold is met.

Yeah, let's see if these two can make windows more stable.

**Comment by chrisgoringe** [comment]
Add a threshold on dev - see if it helps.

**Comment by LukeG89** [comment]
Yes! Windows are very stable now!
