### ISSUE TITLE
[ feature ] option to scroll Controllers by node 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#358]
When I scroll a Controller column with the mouse wheel, I'd like to scroll 1 node at a time ( instead of a fixed amount ).   

This way I can align similar nodes between controllers. 

Can we have a user option for this ?

---

![node](https://github.com/user-attachments/assets/2580bc07-7582-4934-b93d-294faa3dee64)

**Comment by JorgeR81** [comment]
Why is this not possible ?

Is it because it would not work well with dragging the scroll bar ? 

I wouldn't mind if it is only available when the scrollbar is hidden.
 
I would work better with the mouse wheel. 
With each turn of the wheel, we can display a new node. 

And it would have better usability.
We would never see nodes partially. So we can always see the node's header.

**Comment by chrisgoringe** [comment]
Not saying it isn’t possible, but at the moment the scrolling is completely
handled by the browser. To do this would require implementing the scrolling
subsystem, which is a fair amount of work and source of future errors, for
what seems a relatively small benefit.

**Comment by JorgeR81** [comment]
Ah, OK, I thought this would be easy to do.

If it adds too much complexity and could result in errors, it may not be worth it.
