### ISSUE TITLE
[ Bug ] Can't bypass groups, the first time.

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#359]
This bug was probably introduced today. 

When I open a new workflow or create a new group, I can't bypass the group in the Controller, for the first time.  

I need to bypass the group, in the graph, first. 
And then it will also work in the Controller.

**Comment by chrisgoringe** [comment]
Anything in JavaScript console (always look!)

**Comment by JorgeR81** [comment]
When bypass is working there's an extra line in the console, at the end:

`on_change, no changes`

----

**Bypass does not work:**

![1o](https://github.com/user-attachments/assets/01f28e61-2fa8-4c58-b38d-812609be2ca2)

------

**Bypass works**

![2o](https://github.com/user-attachments/assets/7d1974f2-d3d5-4def-8f0b-66806bced383)

**Comment by chrisgoringe** [comment]
Thanks. Try now.

**Comment by JorgeR81** [comment]
It's working.
