### ISSUE TITLE
[ Bug ]  Bypass does not update Subgroups, if they are in another Controller

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#360]
When we bypass a group in the Controller, it also bypasses the subgroup in the graph. This works correctly.

But if we have a subgroup in another Controller, it will not be updated. 
This is just the Controller's visuals. It works in the graph.

---

**Example:**

I created a "Preprocessor" subgroup in the "ControlNet" group for the `Preview Image` nodes.

I used the subgroup to display the images in the Controller for the "Big preview area", so that it could be examined in more detail.

But when I toggle the "ControlNet" group in it's controller, the Subgroup is not updated in the other Controller.

![sg](https://github.com/user-attachments/assets/994d382f-d747-417e-9362-db99e1ea5d18)

----

Here I bypassed the "ControNet" group, but "Preprocessors" it's not shown as bypassed.

It only updates if the subgroup is on the same Controller.

![pp](https://github.com/user-attachments/assets/d29cf046-93f0-402e-a8e1-1247bbeb1aca)

**Comment by chrisgoringe** [comment]
fixed on dev (also the opposite case; parent groups weren't updated!

**Comment by JorgeR81** [comment]
Yes it's working. 

But it has a different behavior than ComfyUI.

In Comfy UI if the subgroup is partially outside the group, it's also bypassed.

But in this case, the other Controller is not updated. 

![ppo](https://github.com/user-attachments/assets/5306ed6d-e561-4c73-86f0-a19423f3d29f)
