### ISSUE TITLE
Field positions not being stored when changing group view

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#37]
They were previously :(

**Comment by JorgeR81** [comment]
This works if I just switch between "All groups" and  the main settings, ( "Text2image" ) placed on top.

![m1](https://github.com/user-attachments/assets/ddb2ba7f-6b6a-426c-b0df-0ce7558043aa)

![m2](https://github.com/user-attachments/assets/ccecdcaa-fe39-45b8-ae8d-3dfb318cc518)

**Comment by JorgeR81** [comment]
But I filter some of the extra groups, when I go back to "All groups", the previously shown widget will be on top ( e.g. ControlNet strength ).

Also, the widgets on the other groups will be in a different order ( e.g. "height" and "width" are no longer consecutive ).

![m3](https://github.com/user-attachments/assets/ab77aef8-dc8a-4dbd-819e-b97907b1dfaa)

![m4](https://github.com/user-attachments/assets/7ed03032-5012-4577-ad01-cb2f599e9454)

**Comment by chrisgoringe** [comment]
Ah, that makes some sense. Thanks for the detailed report :)

**Comment by chrisgoringe** [comment]
OK, it was overriding the list of nodes with just the visible ones. Should work now.

**Comment by JorgeR81** [comment]
It's fixed for me.
