### ISSUE TITLE
Some setting changes not saved to workflow when swapping

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#375]
See https://github.com/chrisgoringe/cg-controller/issues/363#issuecomment-2492600652

**Comment by LukeG89** [comment]
Found it!
It's not just the swipping, it's the last edited title that is not saved.

### Step to reproduce:

- Edit a couple of groups
- Save and close the workflow
- Reopen it: the last group tab you renamed has the previous name

I tested this on 1.3.44 frontend with all other extensions disabled.


https://github.com/user-attachments/assets/05f35ce5-02cd-4d0c-84a1-f8fe77c6adf0

**Comment by chrisgoringe** [comment]
I've got a workaround in... bit of a hack... 

On dev

**Comment by LukeG89** [comment]
Yeah, seems to work!

There is only one small exception when editing subgroups: you must save or move a node to apply the change.
But I guess that in 1.4.12 frontend everything will work fine, I see they merged a PR to fix your issue.

**Comment by LukeG89** [comment]
Ok, now in 1.4.13 is perfectly working in every situation! 🎉
