### ISSUE TITLE
Improve ( node bypass ) performance in large workflows

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#378]
In the large Reddit workflow ( https://github.com/chrisgoringe/cg-controller/discussions/365#discussioncomment-11325778 ), bypassing nodes is a bit slower ( about 1 second ).

Can you improve performance even further?

This is 18 controller instances ! 
So probably the most complex case scenario.
I only notice a slowdown when bypassing nodes ( bypassing groups is fine ).

**Comment by LukeG89** [comment]
I just made this ridiculous workflow with 1 group containing 20 subgroups, and created a controller for each group. But I had no performance issue. Maybe I need to generate something, I don't know. But complexity doesn't seem to be the problem.



https://github.com/user-attachments/assets/dca83eb3-d8e1-4f55-a52b-a9cdafe153e0

**Comment by JorgeR81** [comment]
> I just made this ridiculous workflow with 1 group containing 20 subgroups, and created a controller for each group. But I had no performance issue.

In your video there is also a bit of delay.
By the time the bypass button is changing color, the cursor it's already on the next button.

For me it's also usable. It's not a priority issue. 
It's just a reminder that it could still be improved.

The slowing it's just for the node bypass.  All other actions are instantaneous.
I'm not sure if the other improvements were global in scope.
Maybe a more specific improvement could be done just for node bypass ?

**Comment by LukeG89** [comment]
> In your video there is also a bit of delay.
> By the time the bypass button is changing color, the cursor it's already on the next button.

Ah ok, I thought you were talking about a delay between bypassed nodeblock on Controller and bypassed node on canvas.

Yeah, there is _a bit of delay_ when you click the button and the actual bypass, but it's almost unnoticeable (at least in my case). You just made me notice it! 😆

**Comment by JorgeR81** [comment]
Performance improvements are always welcome, but I don't think we need an issue just for this specific case.

Currently it works OK.

I will reopen if I notice performance degradation.
