### ISSUE TITLE
[Bug] Errors when you use "Clear workflow"

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#380]
I just discovered by accident this problem when you clear a workflow.
You have to refresh the page to fix the issue.

I tested 1.5, dev and main branches and from 1.4.8 back to 1.3.44 frontend, and the problem is always present.

In this video I'm on main and 1.3.44 frontend:

https://github.com/user-attachments/assets/7f10737c-1d92-475c-9c87-7633c9a90e81

**Comment by chrisgoringe** [comment]
try now on main

**Comment by LukeG89** [comment]
Ok, it's fixed!
