### ISSUE TITLE
[ Feature ] Display group's dropdown list in multiple columns

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#384]
The group's dropdown list does not fit in the screen.

Could it be possible to display them in multiple columns ?

---

![g1](https://github.com/user-attachments/assets/33dcb5fb-1682-40b5-b3b0-88eb8ae81507)

![g2](https://github.com/user-attachments/assets/19a1e7a2-cfb2-4da1-9c4e-449b401ea4be)

**Comment by chrisgoringe** [comment]
You have crazy workflows, you know that?

**Comment by JorgeR81** [comment]
It will be better once we have multi row headers ( https://github.com/chrisgoringe/cg-controller/issues/303 )

Now I have to use abbreviations for groups, but it's all "normal" stuff.

- 5 image batch
- Image2Image 
- ControlNet Depth + Canny
- InstantID + IPAdapter FaceID + IPAdapter Embeddings
- Model merge
- Loras 
- 2 Prompt Conditioning ( Combine / Concat / average )
- 4 Sampler stages
  - KSampler
  - KSampler ( Refiner / Upscaler )
  - Face Detailer 
  - Ultimate Upscaler ( tiled upscale )

**Comment by JorgeR81** [comment]
For the sake of simplicity, I think this one can be closed too.

I was adding to many extra groups, to just create more tabs in the GUI.

But I learned to optimize the Controller layout, so I need less groups, for the same features. 

And now we also have features, like the "favorites" tab, and the "stacked" tabs, that help with that.
