### ISSUE TITLE
Compatibility with new menu

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#39]
See examples https://github.com/chrisgoringe/cg-controller/issues/30#issuecomment-2395094241

**Comment by chrisgoringe** [comment]
Two issues:
position 
hamburger menu

**Comment by chrisgoringe** [comment]
fixed on branch 0.6

**Comment by JorgeR81** [comment]
Looks good !

![menu](https://github.com/user-attachments/assets/a9edbaa5-8b63-4b9b-9bec-a7e830c85e7c)

**Comment by JorgeR81** [comment]
By the way, in the latest Frontend version, the floating queue menu is now dockable on the top bar.

So the "submit" button in the controller could be optional. 

![tob bar](https://github.com/user-attachments/assets/4fa29daf-272a-42c7-9673-76cdee11cf1c)

**Comment by JorgeR81** [comment]
And actually, we could just drag it to be below the Controller ! 

![drag](https://github.com/user-attachments/assets/bee11c59-1af9-4f1f-a7a7-c52fa9c20bcd)
