### ISSUE TITLE
[ feature ] update bypass/mute state, in the Controller.

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#392]
When we mute/bypass a node the the graph, it's not updated in the Controller.

We need to update the Controller "manually" ( e.g. with the toggle button, in the top bar ).

But we need to consider, if this it's really necessary, if it degrades performance ( like when updating the node's title/color ).

---

![l0](https://github.com/user-attachments/assets/341623f0-2179-4313-bff5-518400941f1f)

**Comment by LukeG89** [comment]
I think this is a bug. Wasn't it working before?

**Comment by JorgeR81** [comment]
> I think this is a bug. Wasn't it working before?

I'm not sure. I've been using the controller, with the whole graph canvas covered. 

I tried the `main` branch, but it also has this issue.

**Comment by LukeG89** [comment]
> I tried the main branch, but it also has this issue.

Yeah, I tried it too. Maybe I remember wrong... 🤔

**Comment by chrisgoringe** [comment]
Bug indeed.

Fixed on dev.

**Comment by JorgeR81** [comment]
It's working.
