### ISSUE TITLE
[ Feature ] Convert numeric switches  ( Impact Pack ) to Combo box

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#393]
This could be an alternative to the `Trung0246` switch.

This way we could also use the `Impact Pack` switch. This is an extension that most users will have.

The slider widget could be converted to a Combo box in the Controller.
And instead on the input number, in the drop down list we could use the title of the connected nodes.
This way we don't even need to rename the switch's inputs.

This is also the same problem we discussed before.

The `Impact Pack` could implement a Combo Box.
But it's the Controller that really needs this feature, because it does not have the visual feedback of the node connections.
If possible, I think it makes sense to use a different type of widget in the Controller , in this case.

---

**mockup:**

![m1](https://github.com/user-attachments/assets/44f8a3f5-a443-4a1f-9f02-5211d203d00f)

**Comment by chrisgoringe** [comment]
Is using the name of the immediately upstream node going to be reliably useful? What if there are two with the same name?

I guess you can rename the nodes...

**Comment by JorgeR81** [comment]
> Is using the name of the immediately upstream node going to be reliably useful? What if there are two with the same name?
> 
> I guess you can rename the nodes...

If you think it's better to use the input names, in the switch, I don't mind that.
Perhaps it will make more sense.

**Comment by chrisgoringe** [comment]
> > Is using the name of the immediately upstream node going to be reliably useful? What if there are two with the same name?
> > I guess you can rename the nodes...
> 
> If you think it's better to use the input names, in the switch, I don't mind that. Perhaps it will make more sense.

Yes, I think so - you can always edit the input name, after all

**Comment by chrisgoringe** [comment]
done on branch 1.6

**Comment by JorgeR81** [comment]
I have the Combo box, but with the original names ( input1, input 2, ... )

Also, the last option can be hidden, because it's always the extra empty input. 

![c1](https://github.com/user-attachments/assets/abeb67c3-dd36-43bb-a38c-e38671164123)

**Comment by chrisgoringe** [comment]
I had hidden the last input option, but the node allows you to select it?

**Comment by JorgeR81** [comment]
> I had hidden the last input option, but the node allows you to select it, so I thought that might be something that could be desirable under some circumstances. Better to reproduce the node's policy of allowing it?

Yeah, I think in the past this had a purpose. 
But it does not seem to work anymore. 

I asked @ltdrdata, about this: https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/846

**Comment by chrisgoringe** [comment]
Fixed the names, and made it so that the unconnected input isn't on the list. If you select the unconnected input in the node, it will show as "Unconnected Input"

**Comment by JorgeR81** [comment]
Seems to be working fine.

This really lets you create your own GUI !

Here I added a new group to combine a 2nd Prompt.
I just need to click the "Combine" group tab and I can type the new prompt and I select the mode in the switch. 

---

![comb2](https://github.com/user-attachments/assets/ae457d00-5bbb-44b1-acc9-2c29f44ca658)
