### ISSUE TITLE
[Bug] Groups collecting nodes

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#394]
Here we go again...

I'm on 1.4.13 frontend btw

https://github.com/user-attachments/assets/46ce3485-58b7-48f1-bcf4-0f2756df3974

**Comment by chrisgoringe** [comment]
I can't reproduce.... but I've just pushed some changes that ought to avoid this arising.

**Comment by JorgeR81** [comment]
I have the latest `dev` update. 

I don't notice this issue.
But I also didn't notice it before.

**Comment by JorgeR81** [comment]
But once thing I noticed while testing, is that nodes are just "in and out" of controllers, when I move the groups around in the graph.

In the screenshot, the `KSampler` node just showed up in the Controller window with the ControlNet group, when I moved its group over the ControlNet group, in the graph.

This is still while clicking down.

And when I move the group back to its place, it's gone again. 

![ks](https://github.com/user-attachments/assets/c70eb52a-5890-4753-8012-01c03eeb56ce)

**Comment by chrisgoringe** [comment]
Yes, this is by design. The idea is you can see how it will look before you let go.

**Comment by JorgeR81** [comment]
> Yes, this is by design. The idea is you can see how it will look before you let go.

Oh, cool ! If it does not cause any issues, it's an interesting visual cue.

**Comment by LukeG89** [comment]
Ok, the issue is fixed!
