### ISSUE TITLE
[idea] allow a note to be attached to a node in a conroller

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#395]
Could appear as a tooltip, with an option to edit - idea is that you could add notes as to how the nodes are being used.

**Comment by LukeG89** [comment]
How do you associate Note nodes to specific nodes? You rename the note with the same name or ID of the node? 🤔

**Comment by JorgeR81** [comment]
Why do we need to associate a note to a specific node ?

Can't we just add a regular `Note` node ?

Then just move it in the Controller.
And to save space we can minimize it.

![note](https://github.com/user-attachments/assets/2eda6035-e6fc-4cf8-aa25-82921ec08911)
