### ISSUE TITLE
Issue with sliders

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#40]
See https://github.com/chrisgoringe/cg-controller/issues/30#issuecomment-2395198657

**Comment by chrisgoringe** [comment]
![373907929-5860a0bd-d032-4116-b1b5-1dbabafe1e59](https://github.com/user-attachments/assets/5cb1d880-e4d7-47c4-8ccc-21306bc30a28)

copy of image from original report

**Comment by chrisgoringe** [comment]
I can't reproduce this. Could you check the javscript console, or share a workflow in which you see it?

**Comment by JorgeR81** [comment]
I tried again with the default workflow.

This time I tried a Primitive and the value rounding worked. 

The rounding issue was with custom float nodes. I tried:
- ComfyUI-Impact-Pack ( form the same developer as the Comfy UI Manager )
- ComfyUI_essentials ( from the same developer as the ComfyUI_IPAdapter_plus )

But the min / max values still don't work, even with a Primitive. 

![test](https://github.com/user-attachments/assets/97e4f768-c5dd-4413-9372-b31304290e1a)

**Comment by chrisgoringe** [comment]
A workflow where it isn't working would be a big help :)

**Comment by JorgeR81** [comment]
OK, this one uses a single Primitive ( no custom nodes ).
The rounding works, but not the min / max values.

[controller_test_1.json](https://github.com/user-attachments/files/17268940/controller_test_1.json)

**Comment by JorgeR81** [comment]
This one uses the node from Impact-Pack.

So it also has the rounding issue. 

[controller_test_2.json](https://github.com/user-attachments/files/17269105/controller_test_2.json)

![c2](https://github.com/user-attachments/assets/d7251552-9d68-4413-aa18-0f3ff162b4eb)

**Comment by JorgeR81** [comment]
The value rounding also works well with the KSampler widgets.

But the min / max values, in the controller settings, don't seem to work either 

Another problem is the seed slider ...

![ks1](https://github.com/user-attachments/assets/77ab8069-4c19-4c79-8897-295c671b08c6)

**Comment by JorgeR81** [comment]
The blender sliders are amazing !

https://forum.qt.io/topic/145406/best-practices-factoring-code-to-create-a-custom-slider

![EQxb4](https://github.com/user-attachments/assets/d1a92514-2654-4bfd-910e-58c70357a9b7)
