### ISSUE TITLE
[ feature ] Add a "favorites" group tab

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#406]
We could have a right click option to `Include this node as a favorite`

And the we would have an additional "favorites" tab, that we could add to a Controller  window.

In a large workflow the "All" tab has too many nodes. So it's not useful. 
This way we could have most of the workflow nodes in their group tabs, and only the more important ones in the "favorites" tab.

---

![c0](https://github.com/user-attachments/assets/c8df6e11-8622-47d6-8271-582fc46b0e25)

**Comment by JorgeR81** [comment]
To save space in the Controller's header, instead of "favorites", the tab could have only an icon:

![ic1](https://github.com/user-attachments/assets/a748750f-16c2-4237-9912-ceb7b0f54394)

**Comment by chrisgoringe** [comment]
done on dev.

Also selecting a different text color for tab titles when required by the accessibility contrast standards

**Comment by JorgeR81** [comment]
Looks good

The only thing I would do is to hide the group bypass button, when the "favorites" tab is selected ( like we do for "all").

![all](https://github.com/user-attachments/assets/f0e79694-685d-45f7-b532-acfaa3cac775)

**Comment by chrisgoringe** [comment]
Good call. Done on dev.
