### ISSUE TITLE
Show image option

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#417]
Now we capture the right-click for open in mask editor, need to add 'View image' (and maybe others)

**Comment by JorgeR81** [comment]
Good idea !

It's so much more convenient to use, with just the essential options !

![m2b](https://github.com/user-attachments/assets/f8b64c8f-0af8-4d8e-89b7-374f43d88235)

![m3b](https://github.com/user-attachments/assets/5a6ffd9d-1ff5-413e-b09a-997141690443)

**Comment by chrisgoringe** [comment]
I wonder if copy (clipspace) and paste from clipspace are used enough to be worth including?

**Comment by JorgeR81** [comment]
> I wonder if copy (clipspace) and paste from clipspace are used enough to be worth including?

I never used these options.
To move images between workflows, I just open them in a new tab, and drag them to a new workflow.

And now we can also use drag and drop with the Queue Sidebar.
