### ISSUE TITLE
Only get two options for Groups. "group" and "ungrouped"

### ISSUE THREAD

**Issue by yovsac** [chrisgoringe/cg-controller#425]
![Screenshot 2024-12-09 112841](https://github.com/user-attachments/assets/f815bed8-fcea-48f7-8b84-5ce75a1d3465)

Hi, I only get two options for Groups. "group" and "ungrouped". Not sure if its me, that's missing something or a bug. 

Thank you in advanced for any help.

Yovan

**Comment by LukeG89** [comment]
If all your groups have the same name, Controller see them as 1 group. Maybe this is your issue?

**Comment by yovsac** [comment]
But I have diferent names....
![Screenshot 2024-12-09 121706](https://github.com/user-attachments/assets/883d152c-ffab-4d9b-adbf-046320a87e94)

**Comment by yovsac** [comment]
ah figured it out. Its because I dont have any paramater from that group in the controller. Silly me....

**Comment by chrisgoringe** [comment]
lol. I’ve made that mistake 😀

**Comment by yovsac** [comment]
hehehe, do you think it would  be possible to add fast groups muter node by rgthree ?
