### ISSUE TITLE
Support fast group muter

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#428]

**Comment by chrisgoringe** [comment]
done on 1.6

**Comment by JorgeR81** [comment]
The `Fast Groups Mutter` it's working.

But we also need the `Fast Groups Bypasser`

It's basically the same node, but to bypass.

**Comment by chrisgoringe** [comment]
From #422 

The only thing I'd do, is to dim the "no" text, like in the node.
And maybe a brighter text in the group name, if enabled.

**Comment by chrisgoringe** [comment]
> But we also need the `Fast Groups Bypasser`

Added on 1.6

**Comment by chrisgoringe** [comment]
> From #422
> 
> The only thing I'd do, is to dim the "no" text, like in the node. And maybe a brighter text in the group name, if enabled.

added in 1.6
