### ISSUE TITLE
[ Aesthetics ] Show brighter group buttons in the dropdown list ( like before )

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#429]
Now the buttons in the dropdown are dimmer.
 
I guess this makes some sense, because they are not selected. 

But it also hurts visibility. 
It's better to have brighter group buttons in the dropdown list ( like before ).

![tbn](https://github.com/user-attachments/assets/822b57a4-e573-4ef6-a2a4-82bf0c781ffd)

**Comment by chrisgoringe** [comment]
done on dev (and merged to 1.6)
