### ISSUE TITLE
[ feature ] Allow to pan zoomed images 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#439]
Since it's possible to "zoom" images ( by increasing the node height ), we should be able to "pan" them, somehow. 

Maybe `Ctrl+click and drag`

----
![z1](https://github.com/user-attachments/assets/9220beb1-5bd3-458b-9acc-a9e285902b7f)

**Comment by LukeG89** [comment]
- https://github.com/chrisgoringe/cg-controller/issues/298

**Comment by JorgeR81** [comment]
Thanks, closing this one,
