### ISSUE TITLE
Shift click an image to show it in a big popup

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#440]
This would also be preliminary work for the new image picker :)

**Comment by chrisgoringe** [comment]
done on 1.6

**Comment by JorgeR81** [comment]
And maybe the grey frame could be in the same color of the Image node.
This way we could make it dark grey or black. 

---

Or, just remove the grey frame, and make the whole background the color of the node.

**Comment by chrisgoringe** [comment]
I think using the node color as the background might be overwhelming.

Classic photo frames tend to be a dark outer frame, a light background, and then (optionally) a dark border immediately around the image. See what you think of how it looks on dev now

**Comment by JorgeR81** [comment]
Yeah, I see the look that you're trying to achieve. It may work well in some cases. 

But can you add an option to completely remove the frame and have black a background, like when we open the image in the browser. 

If we use this view for the image picker, ( or to see multiple batch images ), it may be better to have a simpler look. 

![f0](https://github.com/user-attachments/assets/52b61bda-99a3-47fd-a3cb-d74e5393596c)

![f0](https://github.com/user-attachments/assets/66b5069c-4c8e-46e9-81c5-c99732050b19)
