### ISSUE TITLE
[ Bug ] Sometimes hiding widgets does work in custom nodes  

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#441]
**EDIT:**  just go to the next comment. This seems to be a different issue.

---

I just realized we can hide the "image viewer" in each KSampler, like any other widget !

Then we could replace it with an `Image Preview` node ( and the this feature would be even more useful : https://github.com/chrisgoringe/cg-controller/issues/434 )

![v2](https://github.com/user-attachments/assets/5fc5cda7-bdb5-453a-b7d7-6ff24033e177)

---

But it seems it only works in native Samplers.
It does not work in `FaceDetailer` and `Ultimate SD Upscale`
We have the option, but clicking it does not have any effect. 

![v1](https://github.com/user-attachments/assets/d50e2b94-c1db-4470-9322-7f6cbe482473)

**Comment by JorgeR81** [comment]
OK, that may be a different bug.

After more testing, I noticed that I was not able to hide any of the widgets in the Face Detailer ( not only the "image viewer" ).

But after switching workflows, and trying again the problem seems to be fixed.
Now I can hide any widget in the non-native samplers, including the image viewer. 

So, now I can't reproduce this issue, but I would leave it open, in case you want to take a look at it.

**Comment by chrisgoringe** [comment]
I'll close - if it happens again, reopen or raise a new issue.
