### ISSUE TITLE
[ feature ] Allow to select the `Unconnected Input` option in the `Impact Pack` switch 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#446]
@ltdrdata, has fixed this issue in the switch: https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/846

So now, being able to select the `Unconnected Input`, it's very useful ( especially in the Controller ! )

This allows to simulate unplugging a wire ( from an optionl input ).

---

![j11](https://github.com/user-attachments/assets/90f64ea3-9418-47bd-a5ec-58ff2468a4d9)

**Comment by chrisgoringe** [comment]
done on dev

**Comment by JorgeR81** [comment]
It's working.
