### ISSUE TITLE
[ Bug ] The "live preview" from the first KSampler only goes 1 level upstream 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#447]
The "live preview" from the first KSampler only goes 1 level "upstream". 

In my test workflow have 4 stages ( groups ) + 1 extra group for the "Final Preview" :

- **stage 1** - KSampler
- **stage 2** - Refiner ( 2nd KSampler )
- **stage 3** - Face Detailer 
- **stage 4** - Upscaler
- **stage 5** - Final Preview ( with just an `Preview Image` node )

When **stage 1** it's running, I can only see the "live preview" in `Preview Image` nodes from **stage 1** and **stage 2**

<details>
<summary>screenshot ( bug )</summary>
<IMG src="https://github.com/user-attachments/assets/7ec5cb06-0452-4d8c-9ddd-9c99358f819f"  alt="image.jpg"/>
</details>

---

But, when **stage 2** it's running, I have the "live preview" in all the "upstream" `Preview Image` nodes ( from stages 2, 3, 4 and 5 ), as expected.

In normal usage, all the small `Preview Image` nodes are minimized. 
I use the large one ( **stage 5** ), to see the live previews from all stages.

<details>
<summary>screenshot ( works )</summary>
<IMG src="https://github.com/user-attachments/assets/064b46bc-4350-42d3-85ff-7c854b5dded8"  alt="image.jpg"/>
</details>

---

I've tried the same workflow, in the `main` branch, and it works.
All `Preview Image` nodes have the "live preview", from the first stage.

<details>
<summary>screenshot ( works )</summary>
<IMG src="https://github.com/user-attachments/assets/c83628f3-11fd-4788-8ec8-382aff25f545"  alt="image.jpg"/>
</details>

---

But I'd still have this issue in the `dev` branch, even after this feature was reverted : https://github.com/chrisgoringe/cg-controller/issues/434#issuecomment-2537093041

---

**Comment by JorgeR81** [comment]
I did another test:

In stage 3, I replaced `FaceDetailer `with a regular `KSampler`.

But I still have the same result : the "live preview" from stage 1 only shows up in stages 1 and 2.

So this does not seem to be related to custom nodes.

**Comment by chrisgoringe** [comment]
try now on dev

**Comment by JorgeR81** [comment]
It's working.
