### ISSUE TITLE
[ feature ] better group name abbreviation

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#453]
When we don't have enough space, small and larger names are abbreviated equally.
But when we abbreviate smaller names, they may not be recognizable  ( as you can see in the example image ).
 
It would be better, if the larger names were abbreviated first.

A simple rule could be:

_A name it's abbreviated, when there it's not enough space, and ....
...  **other abbreviated names, have the same number of visible characters.**_ 

---

**Example:**

Here all names visible.

![z1](https://github.com/user-attachments/assets/b9cc7b62-2846-4a47-a3bd-40d49b340d67)

---

Now all names are abreviated ( this is the current behaviour ).

![z2](https://github.com/user-attachments/assets/33b80803-62f8-4d7e-acf7-dc0a6b2b755b)

I would want to abbreviate only **`Conditioning`**, until it's **`Condi...`**

Then I would abreviate both **`Conditioning`** and **`Model`**, until they are **`Co...`** and **`Mo...`**

Only then, I would start to abbreviate **`P1`** , **`P2`** ,   **`P3`** , **`P4`** ,  **`P5`**, ( these are previews for each stage, by the way ).

**Comment by chrisgoringe** [comment]
Because the shrinking etc is all handled by css (to reduce browser dependencies) I can't do the 'simple rule' that you suggest. However, I've implemented some code that causes the bigger tabs to shrink first. See what you think (on dev)

**Comment by JorgeR81** [comment]
It works well:

![c1](https://github.com/user-attachments/assets/8db33f91-b377-4a6f-af22-1201241a72da)

![c2](https://github.com/user-attachments/assets/28f54102-cc8c-4e74-a575-88a991ed5894)

![c2b](https://github.com/user-attachments/assets/e5bfd4dd-bf22-4d29-b57f-5c01aa4dd839)

![c3](https://github.com/user-attachments/assets/c7ddf748-6b5e-49bf-95e6-879afbb21c7a)

---

The only issue is:

- The smaller tabs are not getting any smaller, and the tabs on the right getting behind the window buttons, and the hidden.

![c4](https://github.com/user-attachments/assets/38c4307c-d54b-4e12-a88f-8e0f641d8704)

----

But, to be usable, I don't think tabs should get any smaller.

Tabs should always show at least 2 characters ( or 1 character + **`...`** ) like they do now.

----

Now we have the perfect solution:

- Enable "stacked" tabs automatically, if the tabs don't fit the window.

A bonus feature would be:

- If it's not manually set, by the user ( in the right click menu ) it would return to normal, if we increase the width again.
( in this case, the right click menu setting would never change )

![c5](https://github.com/user-attachments/assets/57e3c212-5a84-4cd4-8664-69175b15d012)

**Comment by chrisgoringe** [comment]
Added a setting for minimum tab width.

Added auto stacking when tabs forced below minimum width.

The context option has been slightly renamed ("Only show active tab" v "Show all tabs if space allows") and is preserved.

**Comment by JorgeR81** [comment]
I like it !

It works really well !
