### ISSUE TITLE
[ feature ] Option to "lock" ( active ) `bypass/mute` buttons, for each node/group.  

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#454]
When we build our own workflows, we know which nodes we can mute/bypass, and it's very useful.

But if we want to share our workflows with less experienced users, it may be confusing for them.
The GUI, it's literally filled with dozens of buttons that could break the workflow. 

So we could have a right click option, to "lock" the mute/bypass button.

---

I think this would work better if the "locked" state it's allways an "active" state, so:
- If a button it's in a "muted/bypass" stated, the right-click Controller option would be to "enable", instead of "locking.
- If a button it's locked, and we mute/bypass that group/node, in the graph, it would be unlocked automatically in the Controller. 

---

For consistency, we could use one of the other "circle" icons, for the "locked" state.

![ico0](https://github.com/user-attachments/assets/f874fcbc-7743-4c2b-89eb-dd6d91c5abad)

---

We could also have all groups locked by default. 

And when we unlock a button, the "play" icon could be blue ( similar to the blue "pin" icon, or the ComfyUI accent color ).

The "locked state" icon would still be white. 
If we use the "circle-on" icon for that, we could have a ( deafult ) look that's similar to the ComfyUI nodes.

And this way, we can highlight the icons/groups that are "active", but can be safely toggled.

**Comment by yovsac** [comment]
rgthree has a very usefull function for running only a certain group. I use it all the time, it would be great to have that in the controller, is that what you mean?

![Screenshot 2024-12-13 134648](https://github.com/user-attachments/assets/14b17b66-eda8-414b-945f-2cff9c315c23)

**Comment by LukeG89** [comment]
> rgthree has a very usefull function for running only a certain group. I use it all the time, it would be great to have that in the controller, is that what you mean?

@yovsac This request is to add an option to block bypass/mute buttons in controller windows. 
About the running button, you can open a feature request for that: https://github.com/chrisgoringe/cg-controller/issues/new

**Comment by JorgeR81** [comment]
> > rgthree has a very usefull function for running only a certain group. I use it all the time, it would be great to have that in the controller, is that what you mean?
> 
> @yovsac This request is to add an option to block bypass/mute buttons in controller windows.
> About the running button, you can open a new feature request for that: https://github.com/chrisgoringe/cg-controller/issues/new

----

In the Controller we have a single button to "mute/bypas", for each group/node.

The white "play" icon, just means the group/node it's in an "active" state ( that's not mutted or bypassed ).

The problem is that many nodes don't need to be muted or bypassed, and this can break workflows.
( e.g. we can mute a `Load Lora` node, but not the `Load Checkpoint` node ).

This feature would allow to "lock" the "mute/bypas" button, in nodes like the `Load checkpoint` node.
And instead of the "play" icon, we could have the another icon like this:


**mockup:**

![z2](https://github.com/user-attachments/assets/25c1d0a9-e263-4c8a-ac5e-fa7aa4c8f24b)

---

**original:**

![z1](https://github.com/user-attachments/assets/872bfc2a-8fc3-44f2-bcc7-160687a08ba4)

**Comment by yovsac** [comment]
> > rgthree has a very usefull function for running only a certain group. I use it all the time, it would be great to have that in the controller, is that what you mean?
> 
> @yovsac This request is to add an option to block bypass/mute buttons in controller windows. About the running button, you can open a new feature request for that: https://github.com/chrisgoringe/cg-controller/issues/new

Great, thank you!

**Comment by JorgeR81** [comment]
I'm also closing this one, for the sake of simplicity. 

We would be adding a switch ... for the switch !

-----

We now have good support for multiple switch nodes. 

I think it would make more sense to have these switches in the workflow, and add them to the Controller.
