### ISSUE TITLE
[ feature ] option to convert group buttons to dropdown ( for each controller )

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#456]
Problem:
--

Now, when we have a single group button we can click it to replace it, and we will see the group dropdown list.  

This is very useful for narrow Controller windows, that can't even fit 2 group buttons, with the full names. 

![z0](https://github.com/user-attachments/assets/b5f18ee7-9f7c-49c6-8963-19d01443f5c6)

The drawback is that we get a large dropdown with many groups, instead of only the buttons we want to see in that Controller window.

![z6](https://github.com/user-attachments/assets/2a3e2070-14a5-4cea-aea0-5febbe569c15)

Solution:
--

We could have a right click option, in each Controller's header, to convert group buttons to a dropdown list. 

Then we will only see the selected group button and the `+` icon.
And we will have 2 versions of the dropdown list:

- if we click the group button we have a shorter dropdown, just to switch between the "selected" groups.

![z4](https://github.com/user-attachments/assets/e83f4a0c-1b6d-4315-900f-18b91c4431a6)

- and if we click the `+` icon, we still have the old, longer, dropdown, with all the "non selected" groups.

![z10](https://github.com/user-attachments/assets/e9740bdd-db52-4ee1-a589-0d8e36b1a6f8)

---

All the other buttons would still work the same way:
- To move a group to the "selected" list, just click it, in the "non selected" list.
- To move a group back to the "non selected" list, use the "trash can" icon button.

**Comment by chrisgoringe** [comment]
I like this idea... turn on and off with a right click context menu?

**Comment by JorgeR81** [comment]
> turn on and off with a right click context menu?

Yeah, I think it would be the best way.

**Comment by chrisgoringe** [comment]
Try the version on dev now. Right click a tab for the option

**Comment by JorgeR81** [comment]
It's working.

But I don't think we need to show the group that's already selected in the dropdown list. 

![w1](https://github.com/user-attachments/assets/468aac1c-7a86-46ef-8bfa-b586252fd845)

---

> I think it needs some graphical indication that there are other tabs - maybe make the tabs look like a stack?

Maybe like this; adding a shadow / volume effect.

![s1](https://github.com/user-attachments/assets/65db76cb-1a1a-44d0-8e0a-d9a2f630bbaa)

**Comment by chrisgoringe** [comment]
How should it behave if there is only one tab? This could come about in a number of ways...

**Comment by JorgeR81** [comment]
> How should it behave if there is only one tab? This could come about in a number of ways...

What do you mean ?

**Comment by chrisgoringe** [comment]
Thinking about it... if there is a visual hint (which would not be shown if there aren't any other tabs) then A is a good option

**Comment by JorgeR81** [comment]
> Thinking about it... if there is a visual hint (which would not be shown if there aren't any other tabs) then A is a good option

Seems good to me.

**Comment by chrisgoringe** [comment]
try now

**Comment by JorgeR81** [comment]
Looks good 

---

![j1](https://github.com/user-attachments/assets/264f3fd5-bb3e-4acc-b5b6-d4347fd756c8)

![j2](https://github.com/user-attachments/assets/9224faf5-15a9-4ae5-8dc2-5fe53a8fdd4b)

![j3](https://github.com/user-attachments/assets/6e8a94d9-9397-4919-8959-960a8749a999)
