### ISSUE TITLE
When swapping between workflows, sometimes controllers revert back to 'All'

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#459]
Two workflows, each with controllers.

Swap workflows.

Swap back.

One controller (the first?) has changed to 'All'.

**Comment by JorgeR81** [comment]
Yeah, I can reproduce this. 

I think this is a new bug.

**Comment by chrisgoringe** [comment]
May be fixed on dev - please report if still occurs
