### ISSUE TITLE
[ Aesthetics ] text indent inconsistency, in node headers 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#476]
It seems the text indent got larger, in the `dev` version:

![dev](https://github.com/user-attachments/assets/5cb38b00-813d-4366-9d7a-111009a87076)

---
But it gets smaller, in image nodes ( when the "pin" icons shows up )

![dev1](https://github.com/user-attachments/assets/cb106b31-9ddc-458f-aa9e-a9a20af8bd18)

---

Was the indent increase intentional?

I think the smaller indent looks good in the `main` branch

![main](https://github.com/user-attachments/assets/2354f100-36a8-4c29-a0a7-675556e75d21)

---

If you want to increase it, for better text readability, maybe an average between the both indents, would look better.

**Mockup:**

- text 4 pixels to the right 

![i1](https://github.com/user-attachments/assets/0dd9b28c-7f33-461e-9682-8ce2799cc273)

**Comment by chrisgoringe** [comment]
Ah, no, that's the result of another change (the pin was getting hidden in narrow controllers)

**Comment by JorgeR81** [comment]
OK, it returned to normal.
