### ISSUE TITLE
Allow image displays to be resized (down only)

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#52]

**Comment by JorgeR81** [comment]
It works well.

But, after reaching the maximum image size, the widget size can still be increased, resulting in a worse layout. 

Can you do something about this ?

![size1](https://github.com/user-attachments/assets/bbff8aed-55bc-47b9-b58d-9df95f09c0bf)

![drag1](https://github.com/user-attachments/assets/413fa302-292c-4905-83d5-73ae797f91f6)
