### ISSUE TITLE
Visual improvements

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#53]
See https://github.com/chrisgoringe/cg-controller/issues/30#issuecomment-2396523313 for details

- change background color
- remove dotted lines
- Use 2 tone colors
- Lower brightness on the font
- Smaller font -- or -- taller space for title text ( not pictured )
- Alight to the left

![374128364-25ce8e8e-f0b9-47ec-a61d-1d6966e01920](https://github.com/user-attachments/assets/400e01e3-c721-4519-ad2c-c4d3ad134480)

**Comment by JorgeR81** [comment]
The fonts look really good !

---

By the way, it's possible to update this for "light mode", when you have the time ?

I personally don't use it much, but it would be a nice detail.
There is a big button in the new GUI for "light mode", and people are going to try it ...

![wf](https://github.com/user-attachments/assets/923671b0-f009-49df-bf6a-9274c4077649)
