### ISSUE TITLE
Specific area for dragging

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#55]
Could it be possible to add a specific area for dragging ?

Sometimes when I try to use the slider I accidentally drag the whole widget.

The new queue menu has a 3 dot area, on the left, for this.

**Comment by JorgeR81** [comment]
It's working for me.
I like the drag area placement, with the 3 lines. 

---

Just a suggestion about the visuals.
I think the transparency effect is not necessary.
It's pretty, but it's makes the GUI layout a bit confusing, when I'm trying to decide where to place a panel.

Can you add full opacity on the dragged panel and remove the duplicated one ?

This is the way it works already, for the Group Nodes manager, and it feels more like moving a node in the canvas.

![gn](https://github.com/user-attachments/assets/9cadb157-21d0-4345-ab12-98abe9a60648)

![drag](https://github.com/user-attachments/assets/c3ad5420-a99d-4986-b44a-8ad1ef9e9752)

**Comment by chrisgoringe** [comment]
So make the thing being dragged solid, and the place it will go empty?

The issue is that it isn't always obvious where it would end up (unlike a node which stays where you drop it)

I'll try some different visual clues.

**Comment by JorgeR81** [comment]
Oh right ! I pictured this with a single column.

But yeah, with 2 columns it could be confusing.

The current method may be the better one for this.

**Comment by chrisgoringe** [comment]
I've created a disussion thread for this, #60, if you have more thoughts on the matter!
