### ISSUE TITLE
Step not saved (clash with precision?) (was: Add step editing (was: Slider min/max/step editing))

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#61]
This is step 2 from https://github.com/chrisgoringe/cg-controller/discussions/59#discussioncomment-10875040

Add the ability to edit the start/stop/round attributes of a slider (triple-click or shift-click, probably, popping up a dialog). This will be saved to a shared table, with options:

- just apply to this slider
- apply to all [cfg] sliders on [KSampler] nodes
- apply to all [cfg] sliders on any node

At this point the old mechanism will be retired (maybe auto converted, maybe not!)

**Comment by JorgeR81** [comment]
> - apply to all [cfg] sliders on any node

Can you detect if a FLOAT or Primitive node is connected to a "cfg" input ?
And also apply the settings to these sliders.

If so, Step 3 ( the global slider table ) may not be necessary.

![cfg](https://github.com/user-attachments/assets/e19b5a75-d879-4089-b901-38224338a6b3)

**Comment by JorgeR81** [comment]
I think it's the lack of a slider editing system, that keeps sliders from being added to ComfyUI.

Because, apparently, you can already add a slider to a specific widget, if you change the code, and add the slider parameters:
https://github.com/Comfy-Org/litegraph.js/issues/193#issuecomment-2424875055 ( but your changes will be lost, the next time you update ComfyUI ).

If ComfyUI adds sliders, the Controller could use the same slider Settings.
But have no idea if/when they will add sliders ( or if they plan an editing system ).
At least they've moved my slider feature request to the litegraph issues ( https://github.com/Comfy-Org/litegraph.js/issues/193 )

**Comment by LukeG89** [comment]
@chrisgoringe In the documentation I suggest adding that the range you set on the controller slider will also be applied on the node widget.

**Comment by JorgeR81** [comment]
I have the new edit GUI.
But the new step size is not applied to the slider.

The step size is not saved. 
When open the edit GUI again, it shows the old step value.

![stp](https://github.com/user-attachments/assets/57f1a936-d551-4091-8041-7e262c752718)

**Comment by LukeG89** [comment]
I can confirm, it doesn't keep the new step size

**Comment by LukeG89** [comment]
I found another issue. When you set a min/max range, it becomes difficult to change values on the widget using the arrows; many clicks to just change of 1 step


https://github.com/user-attachments/assets/0bf4a042-6ac5-462d-a18a-ed31c424d925

**Comment by chrisgoringe** [comment]
Probably related.

Weird.

**Comment by chrisgoringe** [comment]
Now saved

**Comment by JorgeR81** [comment]
The new slider steps are being used in the slider.

But I still can't use the arrows in the node widgets, once the step is changed.

**Comment by JorgeR81** [comment]
> But I still can't use the arrows in the node widgets, once the step is changed.

OK, I can see what's the issue.

I have the slider step size at 0.05, but the arrows change at 0.01 steps, so the resulting value is not allowed. 

When I click down in the arrow it goes from 0.35 to 0.36
But on click up, it returns to 0.35

**Comment by JorgeR81** [comment]
All the issues described above seem solved with the latest update.

**Comment by LukeG89** [comment]
Ehm...

https://github.com/user-attachments/assets/1e738266-bd1b-487e-9cc8-46e3c642b561

**Comment by JorgeR81** [comment]
> All the issues described above seem solved with the latest update.

Now I'm able to save step the slider settings. And they are kept when switching workflows.
And I can also use the widget arrows.

---

But I now have other issues: https://github.com/chrisgoringe/cg-controller/issues/181#issuecomment-2430446870

I tried mostly with min (0), max (1) and step (0.05)

**Comment by LukeG89** [comment]
@JorgeR81 Have you tried saving step to 1 and then lowering to 0.1? Because I got the problem in the video

**Comment by JorgeR81** [comment]
Yes, with Apply ControlNet I can use  `min (0), max (1) and step (1)`, I had not issues

But with `min (0), max (1) and step (0.1)` the rounding is broken.

![cn](https://github.com/user-attachments/assets/062eaf58-a901-4eec-ae86-0fd768c8aa85)

**Comment by LukeG89** [comment]
And also why all CFGs have 2 decimal digits?

**Comment by JorgeR81** [comment]
> And also why all CFGs have 2 decimal digits?

What do you mean ?
cfg was always like that for me.

![cfg](https://github.com/user-attachments/assets/978f70e1-42de-4f1c-ba6c-b4c656356007)

**Comment by LukeG89** [comment]
@JorgeR81 Watch my video here https://github.com/chrisgoringe/cg-controller/issues/61#issuecomment-2428823993, I always had 1 decimal digit

**Comment by LukeG89** [comment]
https://github.com/user-attachments/assets/fb052db4-4503-4ba2-9e98-325d9456a287

**Comment by chrisgoringe** [comment]
Yeah

If you don't set the precision in the main comfy controls, cfg has a precision of 0.1, but a step size of 0.01, which makes no sense at all.

**Comment by chrisgoringe** [comment]
If you set step to 1, it gets confused into thinking the widget is an integer! I'll raise a new issue.

Not sure what's happened with the rounding.

**Comment by JorgeR81** [comment]
> If you don't set the precision in the main comfy controls, cfg has a precision of 0.1, but a step size of 0.01, which makes no sense at all.

So it's best to set this to AUTO ?

![auto](https://github.com/user-attachments/assets/f055391f-6ba4-4a46-91c8-75fd29c1cf00)
