### ISSUE TITLE
Can drag numbers in sliders

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#63]
- If I double click to select the whole text, and then drag, it will also drag the text.

![374904671-52faef01-ee62-43f5-8047-5bffbfd7d721](https://github.com/user-attachments/assets/1175f2e6-14a0-42c4-9274-f13e722e1a5b)

**Comment by JorgeR81** [comment]
This is fixed for me. 

I see that we now have a nice arrow icon when we drag sliders. I like that ! 

![sliders01](https://github.com/user-attachments/assets/cf5d2da2-98d9-4440-8b82-002707786b90)


---

But I still have an ugly rectangle icon below the mouse pointer, when I drag things, in the Controller.

It does not show in the screencap ( like the mouse pointer ).

But it's also there when I drag the widgets in the controller.
And in this case, there is an additional  "plus" icon flashing below the pointer.

Can this be hidden ? ( I just want to see the pointer )

**Comment by chrisgoringe** [comment]
Unfortunate that is generated by the browser when using the drag and drop. I'm experimenting with getting rid of it, but it's persistent...

**Comment by JorgeR81** [comment]
Yeah, I figured it would be hard to make these go away.

Don't worry too much about it ! There are higher priorities :)

**Comment by JorgeR81** [comment]
I noticed an in use. 

The latest 0.9 update creates a black bottom bar with that double arrow icon, from the sliders

I think I haven't noticed that sooner because, below that, I have a back Windows 10 taskbar ...

![bar](https://github.com/user-attachments/assets/4c1212d7-ec91-401a-a90c-042989bb2f75)

**Comment by chrisgoringe** [comment]
I'm actively working on 0.9!

**Comment by JorgeR81** [comment]
> Unfortunate that is generated by the browser when using the drag and drop. I'm experimenting with getting rid of it, but it's persistent...

You were also able to hide that ugly rectangle, below the cursor, when dragging the sliders ! 

Can you also hide it when we drag the Controller panels ?

**Comment by JorgeR81** [comment]
> probably not

Don't worry about it ! ( this is a more rare use case ).
