### ISSUE TITLE
Hide cursor when dragging

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#65]
check if that works visually

**Comment by JorgeR81** [comment]
> check if that works visually

Do you mean from the user's point of view ?

The Blender cursor only shows up when we type text ( check the gif image ).

---
And it also has different color !

![scolor](https://github.com/user-attachments/assets/87130af6-358a-4d66-8578-84ce45d639f3)

If possible, wouldn't mind having another color in the cursor ( or maybe more grey / dimmer ).

Just to better distinguish the number next to it.

![color](https://github.com/user-attachments/assets/0f8f31ea-0ec9-4c44-97f5-5f5705bc138f)

**Comment by chrisgoringe** [comment]
Can I clarify, when you say "cursor" do you mean the mouse pointer , or the text insertion marker?

The mouse pointer is fairly tightly controlled by the browser when dragging, unfortunately. IM still trying to see if I can make it go away!

**Comment by JorgeR81** [comment]
I mean the vertical line ( `|` ) next to the `0.51` value.

We see this `0.51|`, so it makes it look a bit like `0.511`

But, if it can't be removed or changed, don't worry about it !
