### ISSUE TITLE
firefox compatibility issue

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#68]
Hello,

I discovered your node a few days ago. Unfortunately I can't use it because I can't display the control panel.

I suppose there's an incompatibility with one of the many nodes I've already installed (>500). Hard to know which one...

Too bad, because your idea is really brilliant.

_Originally posted by @vincen57 in https://github.com/chrisgoringe/cg-controller/discussions/67_

**Comment by chrisgoringe** [comment]
Believe now fixed

**Comment by vincen57** [comment]
OK, it works for me on FF
