### ISSUE TITLE
Aesthetics

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#71]
https://github.com/chrisgoringe/cg-controller/discussions/59#discussioncomment-10902177

**Comment by JorgeR81** [comment]
Another idea would be to make the slider's negative area a bit darker, if node colors are used. 
Now there is very little contrast between some of the colors.

---

**original**

![z1](https://github.com/user-attachments/assets/2b09dcc5-c7f5-4658-b9f5-582b2a213909)

---

**mockup** ( with the other enhancements  ) :

![b6](https://github.com/user-attachments/assets/5d5a3dbc-0e31-4922-aac3-e8d269827ae8)

**Comment by JorgeR81** [comment]
About the thicker pale blue vertical line : maybe that was not best sugestion !

The thicker line ( similar to Blender ) looks better, but it may hide the slider values a bit more.

Another alternative would be to remove the line altogether. This will interfere with slider values even less.
And there is enough contrast already between the 2 slider main colors. 

But honestly, all these 3 images look good to me. Do what you think it's best here ! 

**original :**
![zb1](https://github.com/user-attachments/assets/d32079ca-2df8-4dd8-8437-0d196f27b993)

**thicker line :**
![zb2](https://github.com/user-attachments/assets/af25496d-4015-407e-b4fc-df8a4f868013)

**no line :**
![zb3](https://github.com/user-attachments/assets/52b2b3d1-e8b4-48ed-a7d8-9c87f495f49b)


---

I looked again at the Blender sliders, and noticed this line it's actually only used as the text insertion marker !

![blender01](https://github.com/user-attachments/assets/2d69a82b-87c9-4479-91ff-b48307e40812)

![blender02](https://github.com/user-attachments/assets/e4337df8-ecb1-4340-b683-d0f43ef69226)

**Comment by chrisgoringe** [comment]
## Done the following:
Use the same color for the prompt box as used in Comfy UI
Use that same color for the COMBO box
Remove borders on widgets 
Same grey color in the title area, if no color is used ( like on the ComfyUI nodes )
Align the sliders with the rest of the widgets
Make COMBO box as tall as sliders

## Also did
Added a thin line between title and main, like the ComfyUI nodes
![Screenshot 2024-10-11 143431](https://github.com/user-attachments/assets/0a740e2b-6463-4d0e-9717-2aa82384d589)

## Decided against
Thicker (or removed) slider value line  - i like the thin line :)
