### ISSUE TITLE
Display bypassed nodes in controller (with visual hint)

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#72]
- Add a toggle button to the Controller title area to bypass the node ( e.g. Apply ControlNet )

Ideally we should be able to select the panels that will have this button ( e.g. the prompt panel does not need this ).
Maybe you could add a right click option to `add bypass toggle `

![bx1](https://github.com/user-attachments/assets/c73aac84-5bd3-41c4-a884-4f5a81cab3e4)

_Originally posted by @JorgeR81 in https://github.com/chrisgoringe/cg-controller/discussions/58#discussioncomment-10902829_

**Comment by chrisgoringe** [comment]
Doing #89 might make this too much. 

But in that case bypassed nodes should be included in the controller, with some indication that they are bypassed.

One choice would be to use colour, like Comfy does, but I have to say I dislike that effect in the main GUI!

**Comment by JorgeR81** [comment]
> Doing https://github.com/chrisgoringe/cg-controller/issues/89 might make this too much.
> 
> But in that case bypassed nodes should be included in the controller, with some indication that they are bypassed.

Yeah, on second thought, it may not be a good idea to give the option to bypass nodes that are not displayed in the Controller. 
It may be confusing.

I think it it's best to just go with a bypass for individual nodes.

**Comment by JorgeR81** [comment]
> One choice would be to use colour, like Comfy does, but I have to say I dislike that effect in the main GUI!

I also don't like that bypass color in the GUI.
I would prefer just a transparency effect. But that may be confused with a "muted" node in the graph.

For now, let's just try icons, and see how it goes.

**Comment by JorgeR81** [comment]
> bypassed nodes should be included in the controller, with some indication that they are bypassed.
> 
> One choice would be to use colour, like Comfy does, but I have to say I dislike that effect in the main GUI!

Now the bypass color is themable, in the frontend ( https://github.com/Comfy-Org/ComfyUI_frontend/pull/993 )

It can be changed with a custom Color Palette.

Maybe you could get the Controller bypass color from here.

If the a user doesn't like the bypass color, he can change it, in the node, and the the Controller, at the same time.
