### ISSUE TITLE
Lock workflow

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#74]
Add a lock that, when activated, prevents any interaction with the workflow except through the controller. To prevent accidental breakage!

**Comment by chrisgoringe** [comment]
#127 is a much better idea.

**Comment by LukeG89** [comment]
Locking canvas is already implemented in the frontend with the Pan Mode:

![pan_mode](https://github.com/user-attachments/assets/28d305b2-2bd9-4ddc-a0a8-d24384904577)
