### ISSUE TITLE
Can't open Controller in new workflows ( and errors in `groups.js` and `resize_manager.js` )

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#76]
Sometimes I have one of these errors when trying to load workflows.
Also, when I have these errors, some of the groups in the workflow are gone ( at least for the `groups.js` error ).

These can also happen when I switch to workflows with no controller enabled ( mostly the `resize_manager.js` error, I think ).
In this case a small empty Controller also shows up.

![test01](https://github.com/user-attachments/assets/816e7fba-2f68-47b2-88f0-3e30ddf232c5)

---

![error](https://github.com/user-attachments/assets/b72ce404-4471-4ebd-b802-90c35b7f9008)

![log3](https://github.com/user-attachments/assets/7cdbd9a4-ea90-4011-ab84-5ba7a6e4918b)

**Comment by JorgeR81** [comment]
I also noticed that the Controller does not show up in new workflows.

I can add nodes to the Controller ( the pink dot is shown ), but nothing happens when I use the right click option to show the Controller. 

The old Controller workflows still work.

**Comment by JorgeR81** [comment]
In the new workflows (  where the Controller does not work ), I'm constantly having these warnings on the browser.

If I disable the Controller ( in the Manager ), they don't show up anymore. 

![332](https://github.com/user-attachments/assets/d0a02d3b-481b-408a-88bd-7cfe278f1ba6)

**Comment by chrisgoringe** [comment]
Just pushed a small change, please try now

**Comment by chrisgoringe** [comment]
> I also noticed that the Controller does not show up in new workflows.

That is expected behaviour

**Comment by JorgeR81** [comment]
Seems fixed :

- I don't have those errors when switching workflows.

- And now the Controller can be enabled in new workflows, that had no Controller ( that's what I meant before ).

---

But I still have those warnings, In workflows without Controllers.  Is that normal ?

![log4](https://github.com/user-attachments/assets/35de1e3f-e815-4bd7-8308-0373a9c8b7f9)
