### ISSUE TITLE
Write proper documentation

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#78]

**Comment by JorgeR81** [comment]
Some bullet points for documentation: 

- The Controller is an extra sidebar tab, which reproduces widget inputs from selected nodes.

- You can add nodes to the Controller, in each node's right click menu. 

- You can also add group nodes.

- The Controller configuration will be saved in the workflow. 

- Each node will be represented in the Controller by an independent "panel", with a header area and a widget area.

- The Controller uses sliders for the value widgets. 

- You can double click the slider to type values. 

- You can click and drag on the panel's header area, to change its position in the Controller.

- You can collapse / expand the panel by clicking the "dot" in the panel's header. 

- You can resize panels that have a prompt box or an image.

- The generation preview image will also be shown in the Sampler panels.

- Use the Controller's refresh button, to update small nodes changes ( title name, color )

- You can toggle the visibility of the nodes added as "advanced controls".

- You can filter nodes by group. The group's color is displayed in the selector's dropdown list.  

- You can add nodes that will be shown in all group views ( e.g. Image Preview ).



- More features to come !

**Comment by chrisgoringe** [comment]
@JorgeR81  I've put a draft of the docs together, take a look...

**Comment by JorgeR81** [comment]
> we'll work to include the most popular custom widgets in future releases!

> Where is the control_before_generate? It's hidden, but you can change that in the settings

As an alternative, to the "native" seed controls, you can mention that `Seed (rgthree)` it's already supported.

**Comment by JorgeR81** [comment]
Even if it's not the best use case, 
if you start with an image of the Controller + default/simple workflow, people will instantly get the idea,
and will understand better the detailed explanations below. 

But fix the prompt text alignment before making one image.
And you could use another prompt, if you have a goof idea for that.

![canvas](https://github.com/user-attachments/assets/27332e2f-cd3b-4362-845c-5546432bd2e6)

**Comment by JorgeR81** [comment]
About the kown visual bugs you're mentioning, this is the only major one:

- https://github.com/chrisgoringe/cg-controller/issues/162

In the documentation, you could recommend collapsing the prompt nodes and adding them to the Controller.
Because, I think this will be one of the best use cases, anyways ( to have the prompt always visible ).

**Comment by LukeG89** [comment]
Just put here a reminder to write in the documentation that min | max | step will also be applied in the node itself, not only on the controller (it is not obvious).
