### ISSUE TITLE
Show KSampler preview on the first generation

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#79]
Minor issue:

The KSampler preview is working, but not in the first generation. 
In the first generation, it only shows a preview image, when the generation ends. 
And after that, its works OK. 

![ks](https://github.com/user-attachments/assets/8e0f6b88-7dc5-45a7-bab2-2dab97edc4b2)

**Comment by chrisgoringe** [comment]
Ah, I don't use the preview.

**Comment by JorgeR81** [comment]
> Ah, I don't use the preview.

Well, it works !

And I can also scale the preview.

![prev1](https://github.com/user-attachments/assets/16ba249b-2f0c-4c38-b450-78cd2b4c7178)

**Comment by JorgeR81** [comment]
**A clarification to this issue:**

This also happens when I refresh the workflow and the preview image is gone. 
So it's not only in the first generation. It's when the KSampler does not have a preview image.

But, it's fixed, if I just move the workflow, even while generating !

Moving the workflow, updates the Controller, ( so it also works on this other issue : https://github.com/chrisgoringe/cg-controller/issues/80 ).

**Comment by JorgeR81** [comment]
By the way, the Controller also works with Group Nodes !

This is KSampler + VAE + Image Preview

( the preview works, but it still has this same issue ) 

![gn1](https://github.com/user-attachments/assets/b83e540d-6e07-492e-b840-ce959cb437bb)

**Comment by chrisgoringe** [comment]
Now preview not working at all on ksampler?

**Comment by JorgeR81** [comment]
> Now preview not working at all on ksampler?

**Clarification :**

It seems KSampler image preview only works, when Image Preview node is also added to the Controller
