### ISSUE TITLE
Scroll wheel

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#86]
Feature suggestion :

Use the scroll wheel to change slider values ( on mouseover ).
This would be a good way to just increase / decrease, a single step or just a few steps, in sliders with a large range of values.
For instance, if I just want to increase the seed value, by 1, in the seed slider.

**Comment by JorgeR81** [comment]
Since we are using using mouse wheel, to to scroll the full Controller :

We could use `Ctrl + wheel `or `Shift + wheel` to scroll the slider.

Or may have this as a user setting, so we can select which one of these binds, we prefer for each action.

**Comment by JorgeR81** [comment]
> So changing slider values only on mouseover? This can lead to accidental changes during scrolling... 😅

We could have an user setting to use `Shift + Scroll`, for either the slider or the column. ( https://github.com/chrisgoringe/cg-controller/discussions/173#discussioncomment-11002853 )

**Comment by JorgeR81** [comment]
We could also have an option to scroll only 1 slider step. ( https://github.com/chrisgoringe/cg-controller/discussions/173#discussioncomment-11003543 )

For instance, to increment the seed value by 1 

This, together with step size editing, would be a great combination ! 

Can you add an extra option to this list: `single step`

![sl0](https://github.com/user-attachments/assets/f141192e-a137-4f0c-9c0d-a35b7d59f8d5)

**Comment by chrisgoringe** [comment]
Actually, I wonder if it should just be single step always, with step size
editing?

**Comment by JorgeR81** [comment]
Actually, I wonder if it should just be single step always, with step size
editing?

Do you mean removing this setting, and making it always "single step" ?

I agree.

Dragging sliders works very well, for larger changes.

**Comment by LukeG89** [comment]
Now with the on | off | shift options it's perfect! This issue can be closed
